## #01. 준비작업

### 1. 라이브러리 참조

In [1]:
from jussam import load_data

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

In [2]:
from helpers import my_qtcheck

### 2. 데이터 불러오기

In [3]:
origin = load_data("diamonds")
origin.head()

📚 다이아몬드를 커팅, 색상, 투명도, 가격 및 기타 속성 조사한 데이터 셋 (출처: https://www.kaggle.com/datasets/shivam2503/diamonds)

    field    description
--  -------  -------------------------------------------------------------------
 0  price    다이아몬드 가격 (USD, $326 ~ $18,823)
 1  carat    중량 (0.2~5.01)
 2  cut      컷 품질 (Fair, Good, Very Good, Premium, Ideal)
 3  color    색상 등급 - J (worst) to D (best)
 4  clarity  투명도 등급 (I1 (worst), SI2, SI1, VS2, VS1, VVS2, VVS1, IF (best))
 5  x        길이 mm (0~10.74)
 6  y        너비 mm (0--58.9)
 7  z        두께 mm (0--31.8)
 8  depth    비율 정보 = z / mean(x, y) = 2 * z / (x + y) (43--79)
 9  table    다이아몬드의 가장 넓은 지점에 비해 상단(테이블)의 너비 (43--95)

   price  carat      cut color clarity     x     y     z  depth  table
0    326  0.230    Ideal     E     SI2 3.950 3.980 2.430 61.500 55.000
1    326  0.210  Premium     E     SI1 3.890 3.840 2.310 59.800 61.000
2    327  0.230     Good     E     VS1 4.050 4.070 2.310 56.900 65.000
3    334  0.290  Premium     I     VS2 4.200 4.230 2.630 62.400 58.000
4    335  0.310     Good     J     SI2 4.340 4.350 2.750 63.300 58.000

## #02. 자료형 점검

### 1. 자료형 확인

In [4]:
origin.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   price    53940 non-null  int64
 1   carat    53940 non-null  float64
 2   cut      53940 non-null  str
 3   color    53940 non-null  str
 4   clarity  53940 non-null  str
 5   x        53940 non-null  float64
 6   y        53940 non-null  float64
 7   z        53940 non-null  float64
 8   depth    53940 non-null  float64
 9   table    53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.7 MB

### 2. 자료형 반환

In [5]:
df1 = my_qtcheck.set_type(origin, as_category=['cut', 'color', 'clarity'])  
df1.head()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   price    53940 non-null  int64
 1   carat    53940 non-null  float64
 2   cut      53940 non-null  category
 3   color    53940 non-null  category
 4   clarity  53940 non-null  category
 5   x        53940 non-null  float64
 6   y        53940 non-null  float64
 7   z        53940 non-null  float64
 8   depth    53940 non-null  float64
 9   table    53940 non-null  float64
dtypes: category(3), float64(6), int64(1)
memory usage: 3.0 MB

   price  carat      cut color clarity     x     y     z  depth  table
0    326  0.230    Ideal     E     SI2 3.950 3.980 2.430 61.500 55.000
1    326  0.210  Premium     E     SI1 3.890 3.840 2.310 59.800 61.000
2    327  0.230     Good     E     VS1 4.050 4.070 2.310 56.900 65.000
3    334  0.290  Premium     I     VS2 4.200 4.230 2.630 62.400 58.000
4    335  0.310     Good     J     SI2 4.340 4.350 2.750 63.300 58.000

## #03. 데이터 중복 점검

### 1. 중복 검사 및 중복 데이터 삭제

In [6]:
df2 = my_qtcheck.check_duplicates(df1)
df2.head()

중복된 행의 수 : 146
중복된 행이 제거되었습니다.

   price  carat      cut color clarity     x     y     z  depth  table
0    326  0.230    Ideal     E     SI2 3.950 3.980 2.430 61.500 55.000
1    326  0.210  Premium     E     SI1 3.890 3.840 2.310 59.800 61.000
2    327  0.230     Good     E     VS1 4.050 4.070 2.310 56.900 65.000
3    334  0.290  Premium     I     VS2 4.200 4.230 2.630 62.400 58.000
4    335  0.310     Good     J     SI2 4.340 4.350 2.750 63.300 58.000

## #04. 결측치 점검

### 1. 결측치 확인

In [7]:
my_qtcheck.check_missing_values(df2)

         Missing Count  Missing Ratio (%)
price                0              0.000
carat                0              0.000
cut                  0              0.000
color                0              0.000
clarity              0              0.000
x                    0              0.000
y                    0              0.000
z                    0              0.000
depth                0              0.000
table                0              0.000

## #05. 품질 검사 저장

### 1. 품질 검사 데이터셋 저장

In [8]:
df2.to_excel("Diamond_qtcheck.xlsx", index=False)

## #06. 기술 통계량 확인

### 1. 명목형 변수의 기술 통계량 확인

In [9]:
category_desc = my_qtcheck.categorical_summary(df2, save_path="diamonds_category_summary.xlsx")
category_desc

컬럼 'cut'의 value_counts():

           count
cut
Fair        1598
Good        4891
Ideal      21488
Premium    13748
Very Good  12069

컬럼 'color'의 value_counts():

       count
color
D       6755
E       9776
F       9520
G      11262
H       8272
I       5407
J       2802

컬럼 'clarity'의 value_counts():

         count
clarity
I1         740
IF        1784
SI1      13032
SI2       9150
VS1       8156
VS2      12229
VVS1      3647
VVS2      5056

          cut  color clarity
count   53794  53794   53794
unique      5      7       8
top     Ideal      G     SI1
freq    21488  11262   13032

### 2. 연속형 변수의 기술 통계량 확인

In [10]:
desc_df = my_qtcheck.numerical_summary(df2, 
                                       save_path="diamonds_numericla_summary.xlsx")

desc_df

,count,mean,std,min,25%,50%,75%,max,rel_diff,rdiff_flag,iqr,upper_bound,lower_bound,upper_outliers,upper_outliers_ratio,lower_outliers,lower_outliers_ratio,outliers,outliers_ratio,skew,skew_interpret,kurt,kurt_interpret,log_need
price,53794.000,3933.065,3988.114,326.000,951.000,2401.000,5326.750,18823.000,0.638,large_diff,4375.750,11890.375,-5612.625,3523,0.065,0,0.000,3523,0.065,1.618,right tail,2.178,leptokurtic,log1p
carat,53794.000,0.798,0.473,0.200,0.400,0.700,1.040,5.010,0.140,diff,0.640,2.000,-0.560,1873,0.035,0,0.000,1873,0.035,1.114,right tail,1.247,leptokurtic,log1p
x,53794.000,5.731,1.121,0.000,4.710,5.700,6.540,10.740,0.005,similar,1.830,9.285,1.965,24,0.000,7,0.000,31,0.001,0.380,symmetric,-0.629,platykurtic,none
y,53794.000,5.735,1.141,0.000,4.720,5.710,6.540,58.900,0.004,similar,1.820,9.270,1.990,22,0.000,6,0.000,28,0.001,2.446,right tail,91.752,leptokurtic,log1p
z,53794.000,3.539,0.705,0.000,2.910,3.530,4.030,31.800,0.002,similar,1.120,5.710,1.230,28,0.001,20,0.000,48,0.001,1.529,right tail,47.384,leptokurtic,log1p
depth,53794.000,61.748,1.430,43.000,61.000,61.800,62.500,79.000,0.001,similar,1.500,64.750,58.750,1027,0.019,1498,0.028,2525,0.047,-0.114,symmetric,5.413,leptokurtic,none
table,53794.000,57.458,2.234,43.000,56.000,57.000,59.000,95.000,0.008,similar,3.000,63.500,51.500,588,0.011,16,0.000,604,0.011,0.792,right tail,2.775,leptokurtic,log1p

In [11]:
desc_df.T

,price,carat,x,y,z,depth,table
count,53794.000,53794.000,53794.000,53794.000,53794.000,53794.000,53794.000
mean,3933.065,0.798,5.731,5.735,3.539,61.748,57.458
std,3988.114,0.473,1.121,1.141,0.705,1.430,2.234
min,326.000,0.200,0.000,0.000,0.000,43.000,43.000
25%,951.000,0.400,4.710,4.720,2.910,61.000,56.000
50%,2401.000,0.700,5.700,5.710,3.530,61.800,57.000
75%,5326.750,1.040,6.540,6.540,4.030,62.500,59.000
max,18823.000,5.010,10.740,58.900,31.800,79.000,95.000
rel_diff,0.638,0.140,0.005,0.004,0.002,0.001,0.008
rdiff_flag,large_diff,diff,similar,similar,similar,similar,similar
iqr,4375.750,0.640,1.830,1.820,1.120,1.500,3.000
upper_bound,11890.375,2.000,9.285,9.270,5.710,64.750,63.500
lower_bound,-5612.625,-0.560,1.965,1.990,1.230,58.750,51.500
upper_outliers,3523,1873,24,22,28,1027,588
upper_outliers_ratio,0.065,0.035,0.000,0.000,0.001,0.019,0.011
lower_outliers,0,0,7,6,20,1498,16
lower_outliers_ratio,0.000,0.000,0.000,0.000,0.000,0.028,0.000
outliers,3523,1873,31,28,48,2525,604
outliers_ratio,0.065,0.035,0.001,0.001,0.001,0.047,0.011
skew,1.618,1.114,0.380,2.446,1.529,-0.114,0.792
skew_interpret,right tail,right tail,symmetric,right tail,right tail,symmetric,right tail
kurt,2.178,1.247,-0.629,91.752,47.384,5.413,2.775
kurt_interpret,leptokurtic,leptokurtic,platykurtic,leptokurtic,leptokurtic,leptokurtic,leptokurtic
log_need,log1p,log1p,none,log1p,log1p,none,log1p