# [LAB-09] 선형회귀ㅣ05-[PBT] 분석용 데이터 전처리(실습코드).ipynb

## 분석용 데이터 전처리

## #01. 준비작업

### 1. 이전 작업 내역 불러오기

In [1]:
import os
os.chdir(r"c:\py_temp\15_LAB\[LAB-08] EDA")
print(os.listdir())

['(수정본) 0721', '(수정본) 0721.zip', 'boston_checkpoint_0.xlsx', 'boston_checkpoint_1.xlsx', 'boston_checkpoint_2.xlsx', 'boston_checkpoint_3.xlsx', 'boston_chekpoint_4.xlsx', '[LAB-08] PBT - EDAㅣ1-EDA 시작하기(실습코드) yeonju (1).ipynb', '[LAB-08] PBT - EDAㅣ1-EDA 시작하기(실습코드) yeonju.ipynb', '[LAB-08] PBT - EDAㅣ1-EDA 시작하기(실습코드).ipynb', '[LAB-08] PBT - EDAㅣ1-EDA 시작하기(연습문제) yeonju.ipynb', '[LAB-08] PBT - EDAㅣ1-EDA 시작하기(연습문제).ipynb', '[LAB-08] PBT - EDAㅣ1-EDA 시작하기.pdf', '[LAB-08] PBT - EDAㅣ2-단변량 분석(실습코드) yeonju.ipynb', '[LAB-08] PBT - EDAㅣ2-단변량 분석(실습코드).ipynb', '[LAB-08] PBT - EDAㅣ2-단변량 분석(연습문제) yeonju.ipynb', '[LAB-08] PBT - EDAㅣ2-단변량 분석(연습문제).ipynb', '[LAB-08] PBT - EDAㅣ2-단변량 분석.pdf', '[LAB-08] PBT - EDAㅣ3-이변량 분석(실습코드) yeonju.ipynb', '[LAB-08] PBT - EDAㅣ3-이변량 분석(실습코드).ipynb', '[LAB-08] PBT - EDAㅣ3-이변량 분석(연습문제) yeonju.ipynb', '[LAB-08] PBT - EDAㅣ3-이변량 분석(연습문제).ipynb', '[LAB-08] PBT - EDAㅣ3-이변량 분석.pdf', '[LAB-08] PBT - EDAㅣ4-다변량 분석(실습코드) yeonju.ipynb', '[LAB-08] PBT - EDAㅣ4-다변량 분석(실습코드).ipynb', '[LAB-08] PBT - EDAㅣ4-다변량 분석(연습문제) yeonju.ipynb', '[LAB-08] PBT - EDAㅣ4-다변량 분석(연습문제).ipynb', '[LAB-08] PBT - EDAㅣ4-다변량 분석.pdf', '[LAB-08] PBT - EDAㅣ5-EDA 파이프라인(실습코드) yeonju.ipynb', '[LAB-08] PBT - EDAㅣ5-EDA 파이프라인(실습코드).ipynb', '[LAB-08] PBT - EDAㅣ5-EDA 파이프라인(연습문제) yeonju.ipynb', '[LAB-08] PBT - EDAㅣ5-EDA 파이프라인(연습문제).ipynb', '[LAB-08] PBT - EDAㅣ5-EDA 파이프라인.pdf', '노션에서 Assignment 사용방법', '노션에서 Assignment 사용방법.zip', '데이터분석_프로젝트_Assignment_01', '데이터분석_프로젝트_Assignment_01.7z', '데이터분석_프로젝트_Assignment_02', '데이터분석_프로젝트_Assignment_02.7z', '데이터분석_프로젝트_Assignment_03', '데이터분석_프로젝트_Assignment_03.7z']

In [2]:
%%capture cap

# 자신의 실습 환경에 맞게 파일 경로 수정 
%run "./[LAB-08] PBT - EDAㅣ1-EDA 시작하기(실습코드) yeonju.ipynb"

### 2. 불러온 내용 확인

In [3]:
print("목표변수: ", target)
print("연속형(종속변수 포함) : ", continuous_cols)
print("독립변수(명목형): ", nominal_cols)
print("독립변수(연속형) : ", continuous_cols)

display(df.head()) # 품질점검 완료 후 타입변환 데이터 프레임
display(desc)      # 기술통계량 데이터 프레임 
display(cat_desc)  # 범주형 데이터 기술통계량 데이터 프레임

목표변수:  MEDV
연속형(종속변수 포함) :  ['CRIM', 'ZN', 'INDUS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']
독립변수(명목형):  ['CHAS']
독립변수(연속형) :  ['CRIM', 'ZN', 'INDUS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.006,18.000,2.310,0,0.538,6.575,65.200,4.090,1,296,15.300,396.900,4.980,24.000
1,0.027,0.000,7.070,0,0.469,6.421,78.900,4.967,2,242,17.800,396.900,9.140,21.600
2,0.027,0.000,7.070,0,0.469,7.185,61.100,4.967,2,242,17.800,392.830,4.030,34.700
3,0.032,0.000,2.180,0,0.458,6.998,45.800,6.062,3,222,18.700,394.630,2.940,33.400
4,0.069,0.000,2.180,0,0.458,7.147,54.200,6.062,3,222,18.700,396.900,5.330,36.200

,count,mean,std,min,25%,50%,75%,max,rel_diff,rdiff_flag,iqr,upper_bound,lower_bound,upper_outliers,upper_outliers_ratio,lower_outliers,lower_outliers_ratio,outliers,outliers_ratio,skew,skew_interpret,kurt,kurt_interpret,log_need
CRIM,506.000,3.614,8.602,0.006,0.082,0.257,3.677,88.976,13.087,large_diff,3.595,9.070,-5.311,66,0.130,0,0.000,66,0.130,5.223,right tail,37.131,leptokurtic,log
ZN,506.000,11.364,23.322,0.000,0.000,0.000,12.500,100.000,inf,large_diff,12.500,31.250,-18.750,68,0.134,0,0.000,68,0.134,2.226,right tail,4.032,leptokurtic,log1p
INDUS,506.000,11.137,6.860,0.460,5.190,9.690,18.100,27.740,0.149,diff,12.910,37.465,-14.175,0,0.000,0,0.000,0,0.000,0.295,symmetric,-1.234,platykurtic,none
NOX,506.000,0.555,0.116,0.385,0.449,0.538,0.624,0.871,0.031,similar,0.175,0.886,0.187,0,0.000,0,0.000,0,0.000,0.729,right tail,-0.065,platykurtic,none
RM,506.000,6.285,0.703,3.561,5.885,6.208,6.623,8.780,0.012,similar,0.738,7.731,4.778,22,0.043,8,0.016,30,0.059,0.404,symmetric,1.892,leptokurtic,none
AGE,506.000,68.575,28.149,2.900,45.025,77.500,94.075,100.000,0.115,diff,49.050,167.650,-28.550,0,0.000,0,0.000,0,0.000,-0.599,left tail,-0.968,platykurtic,none
DIS,506.000,3.795,2.106,1.130,2.100,3.207,5.188,12.127,0.183,diff,3.088,9.821,-2.532,5,0.010,0,0.000,5,0.010,1.012,right tail,0.488,leptokurtic,log
RAD,506.000,9.549,8.707,1.000,4.000,5.000,24.000,24.000,0.910,large_diff,20.000,54.000,-26.000,0,0.000,0,0.000,0,0.000,1.005,right tail,-0.867,platykurtic,log
TAX,506.000,408.237,168.537,187.000,279.000,330.000,666.000,711.000,0.237,diff,387.000,1246.500,-301.500,0,0.000,0,0.000,0,0.000,0.670,right tail,-1.142,platykurtic,none
PTRATIO,506.000,18.456,2.165,12.600,17.400,19.050,20.200,22.000,0.031,similar,2.800,24.400,13.200,0,0.000,15,0.030,15,0.030,-0.802,left tail,-0.285,platykurtic,none
B,506.000,356.674,91.295,0.320,375.377,391.440,396.225,396.900,0.089,similar,20.848,427.496,344.106,0,0.000,77,0.152,77,0.152,-2.890,left tail,7.227,leptokurtic,reverse_log1p
LSTAT,506.000,12.653,7.141,1.730,6.950,11.360,16.955,37.970,0.114,diff,10.005,31.963,-8.058,7,0.014,0,0.000,7,0.014,0.906,right tail,0.493,leptokurtic,log
MEDV,506.000,22.533,9.197,5.000,17.025,21.200,25.000,50.000,0.063,similar,7.975,36.963,5.062,38,0.075,2,0.004,40,0.079,1.108,right tail,1.495,leptokurtic,log

       CHAS
count   506
unique    2
top       0
freq    471

## #02. 데이터 전처리

### 1. 명목형 라벨링

In [4]:
df1 = my_prep.labeling(df, columns=nominal_cols)
df1.head()

CHAS (1종) : 0=0
CHAS (2종) : 0=0, 1=1

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.006,18.000,2.310,0,0.538,6.575,65.200,4.090,1,296,15.300,396.900,4.980,24.000
1,0.027,0.000,7.070,0,0.469,6.421,78.900,4.967,2,242,17.800,396.900,9.140,21.600
2,0.027,0.000,7.070,0,0.469,7.185,61.100,4.967,2,242,17.800,392.830,4.030,34.700
3,0.032,0.000,2.180,0,0.458,6.998,45.800,6.062,3,222,18.700,394.630,2.940,33.400
4,0.069,0.000,2.180,0,0.458,7.147,54.200,6.062,3,222,18.700,396.900,5.330,36.200

### 2. 더미변수 인코딩

In [5]:
df2 = my_prep.dummies(df1, columns=nominal_cols, drop_first=True)
df2.to_excel("boston_checkpoint_0.xlsx", index=False)
df2.head()

CHAS (2종) -> 생략: 이진 변수이므로 원래 컬럼을 유지

컬럼 수 : 14개 ->14개

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.006,18.000,2.310,0,0.538,6.575,65.200,4.090,1,296,15.300,396.900,4.980,24.000
1,0.027,0.000,7.070,0,0.469,6.421,78.900,4.967,2,242,17.800,396.900,9.140,21.600
2,0.027,0.000,7.070,0,0.469,7.185,61.100,4.967,2,242,17.800,392.830,4.030,34.700
3,0.032,0.000,2.180,0,0.458,6.998,45.800,6.062,3,222,18.700,394.630,2.940,33.400
4,0.069,0.000,2.180,0,0.458,7.147,54.200,6.062,3,222,18.700,396.900,5.330,36.200

### 3. 로그변환 대상 컬럼 선정

In [6]:
# 우측 꼬리 로그 변환 대상 컬럼 
log_cols = desc.loc[desc['log_need'] == 'log'].index.tolist()
log_cols

['CRIM', 'DIS', 'RAD', 'LSTAT', 'MEDV']

In [7]:
# 우측꼬리 로그1p 변환 대상 컬럼 
log1p_cols = desc.loc[desc['log_need'] == 'log1p'].index.tolist()
log1p_cols

['ZN']

In [8]:
# 좌측꼬리 로그 변환 대상 컬럼 
reflect_cols = desc.loc[desc['log_need'] == 'reverse_log1p'].index.tolist()
reflect_cols

['B']

### 4. 로그 변환

In [9]:
df3 = my_prep.log_transform(df2, log_columns=log_cols, 
                            log1p_columns=log1p_cols, 
                            reflect_columns=reflect_cols)
df3.to_excel("boston_checkpoint_1.xlsx", index=False)
df3.head()

컬럼        꼬리방향      변환식                   역변환식                                  왜도
----------------------------------------------------------------------------------------
CRIM      우측 꼬리     log(x)                exp(y)                    5.21 -> 0.40
DIS       우측 꼬리     log(x)                exp(y)                    1.01 -> 0.15
RAD       우측 꼬리     log(x)                exp(y)                    1.00 -> 0.29
LSTAT     우측 꼬리     log(x)                exp(y)                   0.90 -> -0.32
MEDV      우측 꼬리     log(x)                exp(y)                   1.10 -> -0.33
ZN        우측 꼬리     log(1+x)              exp(y)-1                  2.22 -> 1.19
B         좌측 꼬리     log(1+396.9-x)        396.9-(exp(y)-1)         -2.88 -> 0.60

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,-5.064,2.944,2.310,0,0.538,6.575,65.200,1.409,0.000,296,15.300,0.000,1.605,3.178
1,-3.601,0.000,7.070,0,0.469,6.421,78.900,1.603,0.693,242,17.800,0.000,2.213,3.073
2,-3.601,0.000,7.070,0,0.469,7.185,61.100,1.603,0.693,242,17.800,1.623,1.394,3.547
3,-3.431,0.000,2.180,0,0.458,6.998,45.800,1.802,1.099,222,18.700,1.185,1.078,3.509
4,-2.673,0.000,2.180,0,0.458,7.147,54.200,1.802,1.099,222,18.700,0.000,1.673,3.589

### 5. 이상치 대체

In [10]:
df4 = my_prep.replace_outlier(df3, columns=continuous_cols)
df4.to_excel("boston_checkpoint_2.xlsx", index=False)
df4.head()

이상치 대체 방식: 'bound' (기준: IQR x 1.5)
컬럼                                정상범위       이상치                   대체값
--------------------------------------------------------------------
CRIM                     -8.20 ~ 7.01 0개 (0.0%)           -8.20 또는 7.01
ZN                       -3.90 ~ 6.51 0개 (0.0%)           -3.90 또는 6.51
INDUS                  -14.18 ~ 37.47 0개 (0.0%)         -14.18 또는 37.47
NOX                       0.19 ~ 0.89 0개 (0.0%)            0.19 또는 0.89
RM                        4.78 ~ 7.73 30개 (5.9%)           4.78 또는 7.73
AGE                   -28.55 ~ 167.65 0개 (0.0%)        -28.55 또는 167.65
DIS                      -0.61 ~ 3.00 0개 (0.0%)           -0.61 또는 3.00
RAD                      -1.30 ~ 5.87 0개 (0.0%)           -1.30 또는 5.87
TAX                 -301.50 ~ 1246.50 0개 (0.0%)      -301.50 또는 1246.50
PTRATIO                 13.20 ~ 24.40 15개 (3.0%)         13.20 또는 24.40
B                        -3.38 ~ 7.01 0개 (0.0%)           -3.38 또는 7.01
LSTAT                     0.60 ~ 4.17 1개 (0.2%)            0.60 또는 4.17

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,-5.064,2.944,2.310,0,0.538,6.575,65.200,1.409,0.000,296,15.300,0.000,1.605,3.178
1,-3.601,0.000,7.070,0,0.469,6.421,78.900,1.603,0.693,242,17.800,0.000,2.213,3.073
2,-3.601,0.000,7.070,0,0.469,7.185,61.100,1.603,0.693,242,17.800,1.623,1.394,3.547
3,-3.431,0.000,2.180,0,0.458,6.998,45.800,1.802,1.099,222,18.700,1.185,1.078,3.509
4,-2.673,0.000,2.180,0,0.458,7.147,54.200,1.802,1.099,222,18.700,0.000,1.673,3.589

### 6. 다중 공선성 제거

In [11]:
df5 = my_prep.reduce_vif(df4, columns=continuous_cols, threshold=10.0)
df5.to_excel("boston_checkpoint_3.xlsx", index=False)
df5.head()

완료! 남은변수 : ['AGE', 'B', 'CRIM', 'DIS', 'INDUS', 'LSTAT', 'NOX', 'PTRATIO', 'RAD', 'RM', 'TAX', 'ZN']
최대 VIF = 7.57

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,-5.064,2.944,2.310,0,0.538,6.575,65.200,1.409,0.000,296,15.300,0.000,1.605,3.178
1,-3.601,0.000,7.070,0,0.469,6.421,78.900,1.603,0.693,242,17.800,0.000,2.213,3.073
2,-3.601,0.000,7.070,0,0.469,7.185,61.100,1.603,0.693,242,17.800,1.623,1.394,3.547
3,-3.431,0.000,2.180,0,0.458,6.998,45.800,1.802,1.099,222,18.700,1.185,1.078,3.509
4,-2.673,0.000,2.180,0,0.458,7.147,54.200,1.802,1.099,222,18.700,0.000,1.673,3.589

### 7. 정규화

In [12]:
df6 = my_prep.scaling(df5, columns=continuous_cols, method='standard')
df6.to_excel("boston_chekpoint_4.xlsx", index=False)
df6.head()

StandardScaler 적용 (12개 컬럼)
컬럼                            변환 전                  변환 후
--------------------------------------------------------
CRIM                -5.06 ~ 4.49            -1.98~2.44
ZN                   0.00 ~ 4.62            -0.59~2.26
INDUS               0.46 ~ 27.74            -1.56~2.42
NOX                  0.39 ~ 0.87            -1.47~2.73
RM                   4.78 ~ 7.73            -2.38~2.31
AGE                2.90 ~ 100.00            -2.34~1.12
DIS                  0.12 ~ 2.50            -1.98~2.43
RAD                  0.00 ~ 3.18            -2.14~1.50
TAX              187.00 ~ 711.00            -1.31~1.80
PTRATIO            13.20 ~ 22.00            -2.46~1.65
B                    0.00 ~ 5.99            -1.18~2.23
LSTAT                0.60 ~ 3.64            -2.95~2.11

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,-1.983,1.229,-1.288,0,-0.144,0.476,-0.120,0.409,-2.137,-0.667,-1.477,-1.184,-1.276,3.178
1,-1.306,-0.589,-0.593,0,-0.740,0.231,0.367,0.770,-1.344,-0.987,-0.310,-1.184,-0.264,3.073
2,-1.306,-0.589,-0.593,0,-0.740,1.445,-0.266,0.770,-1.344,-0.987,-0.310,-0.257,-1.629,3.547
3,-1.227,-0.589,-1.307,0,-0.835,1.148,-0.810,1.139,-0.880,-1.106,0.110,-0.507,-2.154,3.509
4,-0.876,-0.589,-1.307,0,-0.835,1.384,-0.511,1.139,-0.880,-1.106,0.110,-1.184,-1.163,3.589

## #01. 연습문제

In [13]:
origin = load_data('insurance_qtcheck')
origin.head()

📚 보험 비용 데이터셋의 품질 검사 완료 버전 (출처: 자체 정제)

   age     sex    bmi  children smoker     region   charges
0   19  female 27.900         0    yes  southwest 16884.924
1   18    male 33.770         1     no  southeast  1725.552
2   28    male 33.000         3     no  southeast  4449.462
3   33    male 22.705         0     no  northwest 21984.471
4   32    male 28.880         0     no  northwest  3866.855

In [14]:
desc = load_data('insurance_qtcheck_desc')
desc.head()

📚 보험 비용 데이터셋의 연속형 변수에 대한 기술 통계량 (출처: 자체 작업)

,count,mean,std,min,25%,50%,75%,max,rel_diff,rdiff_flag,iqr,upper_bound,lower_bound,upper_outliers,upper_outliers_ratio,lower_outliers,lower_outliers_ratio,outliers,outliers_ratio,skew,skew_interpret,kurt,kurt_interpret,log_need
age,1337.000,39.222,14.044,18.000,27.000,39.000,51.000,64.000,0.006,similar,24.000,87.000,-9.000,0,0.000,0,0.000,0,0.000,0.055,symmetric,-1.244,platykurtic,none
bmi,1337.000,30.663,6.100,15.960,26.290,30.400,34.700,53.130,0.009,similar,8.410,47.315,13.675,9,0.007,0,0.000,9,0.007,0.284,symmetric,-0.053,platykurtic,none
children,1337.000,1.096,1.206,0.000,0.000,1.000,2.000,5.000,0.096,similar,2.000,5.000,-3.000,0,0.000,0,0.000,0,0.000,0.937,right tail,0.201,leptokurtic,log1p
charges,1337.000,13279.121,12110.360,1121.874,4746.344,9386.161,16657.717,63770.428,0.415,diff,11911.373,34524.778,-13120.716,139,0.104,0,0.000,139,0.104,1.515,right tail,1.604,leptokurtic,log

In [15]:
cat_desc = load_data('insurance_qtcheck_category_desc')
cat_desc

📚 보험 비용 데이터셋의 범주형 변수에 대한 기술 통계량 (출처: 자체 작업)

         sex smoker     region
count   1337   1337       1337
unique     2      2          4
top     male     no  southeast
freq     675   1063        364

In [16]:
# 명목형 기술통계량 표의 컬럼명이 곧 명목형 변수 목록이다
df = my_qtcheck.set_type(origin, as_category=cat_desc.columns)

<class 'pandas.DataFrame'>
RangeIndex: 1337 entries, 0 to 1336
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   sex       1337 non-null   category
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   category
 5   region    1337 non-null   category
 6   charges   1337 non-null   float64
dtypes: category(3), float64(2), int64(2)
memory usage: 45.9 KB

In [17]:
target = "charges"

nominal_cols = my_qtcheck.get_categorical_column_names(df)
continuous_cols = my_qtcheck.get_number_column_names(df)
continuous_cols.remove(target) # target 은 리스트에서 제외시키기 

print("[EDA 반영 전] 명목형: ", nominal_cols)

[EDA 반영 전] 명목형:  ['sex', 'smoker', 'region']

In [18]:
# EDA 에서 채택되지 않은 변수를 걷어낸다 
# sex, region은 청구비용과 관련이 없어 제외하기로 함. 
df = df.drop(columns=['sex', 'region'])
cat_desc = cat_desc.drop(columns=['sex', 'region'])
nominal_cols = cat_desc.columns.to_list()

print("[EDA 반영 후] 명목형 : ", nominal_cols)
print("              연속형 :", continuous_cols)
print("                 크기 : ", df.shape)

[EDA 반영 후] 명목형 :  ['smoker']
              연속형 : ['age', 'bmi', 'children']
                 크기 :  (1337, 5)

In [19]:
# 문제1 : 명목형 변수인 smoker

### 명목형 라벨링

In [20]:
df1 = my_prep.labeling(df, columns=nominal_cols)
df1.head()

smoker (1종) : no=0
smoker (2종) : no=0, yes=1

   age    bmi  children  smoker   charges
0   19 27.900         0       1 16884.924
1   18 33.770         1       0  1725.552
2   28 33.000         3       0  4449.462
3   33 22.705         0       0 21984.471
4   32 28.880         0       0  3866.855

In [21]:
# 문제2 : 흡연자 yes에게 부여된 정수 1

### 더미변수 인코딩

In [22]:
df2 = my_prep.dummies(df1, columns=nominal_cols, drop_first=True)
df2.head()

smoker (2종) -> 생략: 이진 변수이므로 원래 컬럼을 유지

컬럼 수 : 5개 ->5개

   age    bmi  children  smoker   charges
0   19 27.900         0       1 16884.924
1   18 33.770         1       0  1725.552
2   28 33.000         3       0  4449.462
3   33 22.705         0       0 21984.471
4   32 28.880         0       0  3866.855

In [23]:
# 문제3 : 인코딩을 마친 컬럼의 수 5

### 로그변환 대상 선정

In [24]:
# 우측 꼬리 로그 변환 대상 컬럼 
log_cols = desc.loc[desc['log_need'] == 'log'].index.tolist()
log_cols

['charges']

In [25]:
# 우측꼬리 로그1p 변환 대상 컬럼 
log1p_cols = desc.loc[desc['log_need'] == 'log1p'].index.tolist()
log1p_cols

['children']

In [26]:
# 좌측꼬리 로그 변환 대상 컬럼 
reflect_cols = desc.loc[desc['log_need'] == 'reverse_log1p'].index.tolist()
reflect_cols

[]

In [27]:
print("순수 log : ", log_cols)
print("log(1+x) : ", log1p_cols)
print("반사 후 log : ", reflect_cols)

desc[['skew', 'kurt', 'min', 'log_need']]

순수 log :  ['charges']
log(1+x) :  ['children']
반사 후 log :  []

          skew   kurt      min log_need
age      0.055 -1.244   18.000     none
bmi      0.284 -0.053   15.960     none
children 0.937  0.201    0.000    log1p
charges  1.515  1.604 1121.874      log

In [28]:
df3 = my_prep.log_transform(df2, log_columns=log_cols, 
                            log1p_columns=log1p_cols, 
                            reflect_columns=reflect_cols)
df3.head()

컬럼        꼬리방향      변환식                   역변환식                                  왜도
----------------------------------------------------------------------------------------
charges   우측 꼬리     log(x)                exp(y)                   1.51 -> -0.09
children  우측 꼬리     log(1+x)              exp(y)-1                  0.94 -> 0.26

   age    bmi  children  smoker  charges
0   19 27.900     0.000       1    9.734
1   18 33.770     0.693       0    7.453
2   28 33.000     1.386       0    8.401
3   33 22.705     0.000       0    9.998
4   32 28.880     0.000       0    8.260

In [29]:
# 로그변환을 마친 뒤 이 변수의 왜도 
# charges 1.51 -> -0.09 
# children 0.94 -> 0.26

In [30]:
# 1을 더한 뒤 로그를 취해야 하는 변수 children

In [31]:
# 왜도가 큰 변수는 charges(1.515), children(0.937) 
# charges는 최솟값이 1,121.874로 0보다 크니 순수 log,
# children은 자녀가 없는 가입자가 573명이라 최솟값이 0이므로 log(1+x)로 갈린다.

### 이상치 대체

In [32]:
df4 = my_prep.replace_outlier(df3, columns=continuous_cols)
df4.head()

이상치 대체 방식: 'bound' (기준: IQR x 1.5)
컬럼                                정상범위       이상치                   대체값
--------------------------------------------------------------------
age                     -9.00 ~ 87.00 0개 (0.0%)          -9.00 또는 87.00
bmi                     13.67 ~ 47.32 9개 (0.7%)          13.67 또는 47.32
children                 -1.65 ~ 2.75 0개 (0.0%)           -1.65 또는 2.75

   age    bmi  children  smoker  charges
0   19 27.900     0.000       1    9.734
1   18 33.770     0.693       0    7.453
2   28 33.000     1.386       0    8.401
3   33 22.705     0.000       0    9.998
4   32 28.880     0.000       0    8.260

In [ ]:
# 문제 6 
# 연속형 변수들의 이상치를 경계값으로 대체함 
# 대체된 값은 총 9개

###  다중 공선성 제거

In [33]:
df5 = my_prep.reduce_vif(df4, columns=continuous_cols)
df5.head()

완료! 남은변수 : ['age', 'bmi', 'children']
최대 VIF = 1.01

   age    bmi  children  smoker  charges
0   19 27.900     0.000       1    9.734
1   18 33.770     0.693       0    7.453
2   28 33.000     1.386       0    8.401
3   33 22.705     0.000       0    9.998
4   32 28.880     0.000       0    8.260

In [ ]:
# 최대 VIF가 1.01로 임계값 10에 한참 못미쳐 제거된 변수가 없음

###  정규화

In [34]:
df6 = my_prep.scaling(df5, columns=continuous_cols, method='standard')
df6.head()

StandardScaler 적용 (3개 컬럼)
컬럼                            변환 전                  변환 후
--------------------------------------------------------
age                18.00 ~ 64.00            -1.51~1.76
bmi                15.96 ~ 47.32            -2.43~2.75
children             0.00 ~ 1.79            -1.04~2.17

     age    bmi  children  smoker  charges
0 -1.440 -0.454    -1.043       1    9.734
1 -1.512  0.515     0.199       0    7.453
2 -0.799  0.388     1.441       0    8.401
3 -0.443 -1.312    -1.043       0    9.998
4 -0.514 -0.292    -1.043       0    8.260

In [35]:
df6.describe().T[['mean', 'std', 'min', 'max']]

           mean   std    min    max
age      -0.000 1.000 -1.512  1.765
bmi      -0.000 1.000 -2.425  2.751
children -0.000 1.000 -1.043  2.167
smoker    0.205 0.404  0.000  1.000
charges   9.100 0.919  7.023 11.063

In [ ]:
# 문제 7 
# 데이터에 평균이 0으로 맞춰지지 않고 남은 변수 
# charges

In [ ]:
# age, bmi, children 세 개만 평균 0, 표준편차 1로 맞춰졌고, 
# charges는 평균 9.100, 표준편차 0.9191 로 로그 스케일 그대로 남아있음
# smoker도 0/1 이진값이라 대상이 아님.

In [ ]:
# age, bmi, children 은 표준화 되어있어 계수를 '1살 늘때'가 아니라
# '1 표준편차 만큼 늘때' 라고 읽어야 함