# [LAB 04] 데이터 다루기 - 3. 문자열, 시계열 데이터 처리

## #01. 준비작업

### 1. 라이브러리 불러오기

In [39]:
from jussam import load_data

from pandas import to_datetime          # 날짜 타입 형변환 기능
from pandas import DateOffset           # pandas의 날짜 연산 단위 
from datetime import datetime as dt     # 파이썬의 내장 객체 
from datetime import timedelta as td    # 파이썬의 내장 날짜 연산 단위

### 2. 데이터 불러오기

In [40]:
origin = load_data('group_list')
origin

📚 어느 게임 동아리의 회원 목록을 조사한 가상의 데이터

,아이디,이메일,주소,전화번호,메모,등급,상태,등록일시
이름,,,,,,,,
김철수,kimcs,kimcs@naver.com,서울시 강남구,010-1234-5678,파이썬 좋아함,골드,활성,2024-01-15 09:30:00
이영희,leeyh,leeyh@daum.net,부산시 해운대구,010-2345-6789,메모 없음,실버,비활성,2024-02-20 14:15:30
박민수,parkms,parkms@gmail.com,대구시 중구,010-3456-7890,판다스 사용중,브론즈,활성,2024-03-10 16:45:00
최수지,choisj,choisj@hanmail.net,인천시 연수구,010-4567-8901,앞쪽공백,플래티넘,활성,2024-04-05 11:20:15
정하나,junghana,junghana@nate.com,광주시 서구,010-5678-9012,뒤쪽공백,골드,비활성,2024-05-12 08:55:45
강민호,kangmh,kangmh@yahoo.co.kr,대전시 유성구,010-6789-0123,대소문자 혼합,실버,활성,2024-06-18 13:30:20
송지은,songje,songje@outlook.com,울산시 남구,010-7890-1234,"쉼표,포함",브론즈,활성,2024-07-22 17:10:30
윤태우,yoontw,yoontw@kakao.com,세종시,010-8901-2345,숫자123포함,플래티넘,비활성,2024-08-30 10:05:00

## #02. 문자열 데이터 처리

### 1. 대소문자 변경

In [41]:
# 원본 데이터 프레임 복사 
df = origin.copy()

# 예: 이메일 컬럼의 대소문자 조작 
df['이메일_소문자'] = df['이메일'].str.lower()      # 소문자 변경 
df['이메일_대문자'] = df['이메일'].str.upper()      # 대문자 변경 
df['단어_첫글자'] = df['아이디'].str.title()        # 단어 첫 글자 대문자 
df['첫글자'] = df['아이디'].str.capitalize()        # 문장 첫 글자 대문자 
df[['이메일','이메일_소문자', '이메일_대문자', '단어_첫글자', '첫글자']].head()

,이메일,이메일_소문자,이메일_대문자,단어_첫글자,첫글자
이름,,,,,
김철수,kimcs@naver.com,kimcs@naver.com,KIMCS@NAVER.COM,Kimcs,Kimcs
이영희,leeyh@daum.net,leeyh@daum.net,LEEYH@DAUM.NET,Leeyh,Leeyh
박민수,parkms@gmail.com,parkms@gmail.com,PARKMS@GMAIL.COM,Parkms,Parkms
최수지,choisj@hanmail.net,choisj@hanmail.net,CHOISJ@HANMAIL.NET,Choisj,Choisj
정하나,junghana@nate.com,junghana@nate.com,JUNGHANA@NATE.COM,Junghana,Junghana

### 2. 공백 제거와 패딩

In [42]:
df['strip'] = df['메모'].str.strip()        # 앞뒤 공백 제거
df['lstrip'] = df['메모'].str.lstrip()      # 왼쪽 공백 제거 
df['rstrip'] = df['메모'].str.rstrip()      # 오른쪽 공백 제거 

# 왼쪽 0으로 채워 지정길이로 만듦 
df['zfill'] = df['아이디'].str.zfill(12)

# 지정된 길이로 만들기 위해 side에 지정한 위치(left, right, both)에 fillchar를 채움
df['pad'] = df['아이디'].str.pad(12, side='both', fillchar='*')

df[['strip', 'lstrip', 'rstrip', 'zfill','pad']].head()

       strip     lstrip     rstrip         zfill           pad
이름
김철수  파이썬 좋아함  파이썬 좋아함      파이썬 좋아함  0000000kimcs  ***kimcs****
이영희    메모 없음      메모 없음      메모 없음  0000000leeyh  ***leeyh****
박민수  판다스 사용중    판다스 사용중    판다스 사용중  000000parkms  ***parkms***
최수지     앞쪽공백       앞쪽공백       앞쪽공백  000000choisj  ***choisj***
정하나     뒤쪽공백     뒤쪽공백         뒤쪽공백  0000junghana  **junghana**

### 3. 특정 패턴 포함/ 시작/ 끝 검사

In [43]:
# 이메일이 'naver.com'을 포함하는지 확인 
df['네이버이메일'] = df['이메일'].str.contains('naver.com')

# 전화번호가 '010-'으로 시작하는지 
df['휴대폰번호'] = df['전화번호'].str.startswith('010-')    

# 주소가 '구'로 끝나는지 
df['구단위주소'] = df['주소'].str.endswith('구')

# 결과확인 
df[['이메일', '네이버이메일', '전화번호', '휴대폰번호', '주소', '구단위주소']].head()

                    이메일  네이버이메일           전화번호  휴대폰번호        주소  구단위주소
이름
김철수     kimcs@naver.com    True  010-1234-5678   True   서울시 강남구   True
이영희      leeyh@daum.net   False  010-2345-6789   True  부산시 해운대구   True
박민수    parkms@gmail.com   False  010-3456-7890   True    대구시 중구   True
최수지  choisj@hanmail.net   False  010-4567-8901   True   인천시 연수구   True
정하나   junghana@nate.com   False  010-5678-9012   True    광주시 서구   True

### 4. 찾기/ 개수/ 치환

In [44]:
# 메모에서 '중' 문자가 처음 나오는 위치 (0부터 시작, 못찾으면 -1)
df['메모_중_위치'] = df['메모'].str.find('중')

# 메모에서 '중'이라는 글자의 개수 
df['메모_중_개수'] = df['메모'].str.count('중')

# '메모없음'이라는 문자열을 'empty'로 치환 
df['메모없음'] = df['메모'].str.replace('메모없음', 'empty')

df[['메모', '메모_중_위치', '메모_중_개수', '메모없음']].head()

              메모  메모_중_위치  메모_중_개수         메모없음
이름
김철수    파이썬 좋아함         -1        0    파이썬 좋아함
이영희        메모 없음       -1        0        메모 없음
박민수      판다스 사용중        6        1      판다스 사용중
최수지         앞쪽공백       -1        0         앞쪽공백
정하나       뒤쪽공백         -1        0       뒤쪽공백

### 5. 분할/ 추출/ 결합

In [45]:
# '@' 기준으로 분할한 후 0번째 요소 반환 
df['사용자명'] = df['이메일'].str.split('@').str.get(0)

# '@'기준으로 분할한 후 1번째 요소 반환 
df['도메인'] = df['이메일'].str.split('@').str.get(1)

# 이름과 이메일 뒷부분 결합 
df['이름_이메일'] = df.index.str.cat(df['도메인'], sep='@')

# 결과확인 
df[['사용자명', '도메인', '이름_이메일']].head()

         사용자명          도메인           이름_이메일
이름
김철수     kimcs    naver.com    김철수@naver.com
이영희     leeyh     daum.net     이영희@daum.net
박민수    parkms    gmail.com    박민수@gmail.com
최수지    choisj  hanmail.net  최수지@hanmail.net
정하나  junghana     nate.com     정하나@nate.com

In [46]:
### 6. 타입 검사(숫자/문자 여부)

df['아이디_숫자여부(1)'] = df['아이디'].str.isdigit()
df['아이디_숫자여부(2)'] = df['아이디'].str.isnumeric()
df['등급_문자여부'] = df['등급'].str.isalpha()
df['등급_문자+숫자여부'] = df['등급'].str.isalnum()

df[['아이디', '아이디_숫자여부(1)', '아이디_숫자여부(2)', '등급', '등급_문자여부', '등급_문자+숫자여부']].head()

          아이디  아이디_숫자여부(1)  아이디_숫자여부(2)    등급  등급_문자여부  등급_문자+숫자여부
이름
김철수     kimcs        False        False    골드     True        True
이영희     leeyh        False        False    실버     True        True
박민수    parkms        False        False   브론즈     True        True
최수지    choisj        False        False  플래티넘     True        True
정하나  junghana        False        False    골드     True        True

### 7. 길이/ 슬라이스

In [47]:
df['이름_길이'] = df.index.str.len() # 문자열 길이 
df['이름_성'] = df.index.str.slice(0,1) # 0번째 부터 1번째 전까지 자름 
df['전화번호_뒷4자리'] = df['전화번호'].str.slice(-4)   # 마지막 4자리 
df[['이름_길이', '이름_성', '전화번호', '전화번호_뒷4자리']].head()

     이름_길이 이름_성           전화번호 전화번호_뒷4자리
이름
김철수      3    김  010-1234-5678      5678
이영희      3    이  010-2345-6789      6789
박민수      3    박  010-3456-7890      7890
최수지      3    최  010-4567-8901      8901
정하나      3    정  010-5678-9012      9012

## #03. 시계열 데이터 처리 준비 작업

### 1. 데이터 불러오기

In [48]:
origin = load_data('shopping_orders')
origin.head()

📚 어느 쇼핑몰의 고객별 주문 내역 데이터

      고객명           주문일              배송완료일시       상품명  상품분류    주문금액  결제방법 배송지역
고객ID
C001  김민수  2024년 1월 15일 2024-01-17 14:30:00    무선 이어폰  전자기기   89000  카드결제   서울
C002  이영희   2024년 2월 3일 2024-02-05 16:20:00     겨울 코트    의류  156000  계좌이체   부산
C003  박철수  2024년 2월 14일 2024-02-16 11:45:00  발렌타인 초콜릿    식품   25000  카드결제   대구
C004  최지영   2024년 3월 8일 2024-03-10 13:15:00     여성 향수   화장품   78000  카드결제   인천
C005  정한솔  2024년 3월 22일 2024-03-24 09:30:00   게이밍 마우스  전자기기   65000  카드결제   서울

### 2. 데이터 타입 확인 
- 주문일 -> 문자열 타입
- 배송완료 일시 -> 날짜, 시간 타입

In [49]:
origin.info()

<class 'pandas.DataFrame'>
Index: 30 entries, C001 to C018
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   고객명     30 non-null     str
 1   주문일     30 non-null     str
 2   배송완료일시  30 non-null     datetime64[us]
 3   상품명     30 non-null     str
 4   상품분류    30 non-null     str
 5   주문금액    30 non-null     int64
 6   결제방법    30 non-null     str
 7   배송지역    30 non-null     str
dtypes: datetime64[us](1), int64(1), str(6)
memory usage: 4.2 KB

## #04. 시계열 데이터 처리

### 1. 문자열을 날짜 타입으로 변환

In [50]:
df = origin.copy()      # 원본 데이터 보호를 위해 복사본 생성 

# 문자열에 대한 날짜 타입 변환 
# --> 년, 월, 일에 대한 format 지정 필요 
df['주문일_타입변환'] = to_datetime(df['주문일'], format= '%Y년 %m월 %d일')

# 변환 전, 후의 데이터 타입 확인 
print(df[['주문일', '주문일_타입변환']].info())

# 변환 전, 후의 데이터 확인 
df[['주문일', '주문일_타입변환']].head()

<class 'pandas.DataFrame'>
Index: 30 entries, C001 to C018
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   주문일       30 non-null     str
 1   주문일_타입변환  30 non-null     datetime64[us]
dtypes: datetime64[us](1), str(1)
memory usage: 1.3 KB
None

               주문일   주문일_타입변환
고객ID
C001  2024년 1월 15일 2024-01-15
C002   2024년 2월 3일 2024-02-03
C003  2024년 2월 14일 2024-02-14
C004   2024년 3월 8일 2024-03-08
C005  2024년 3월 22일 2024-03-22

### 2. 년/ 월/ 일 정보 추출 
- 날짜 타입의 컬럼은 .df 속성을 사용하여 다양한 정보를 추출할 수 있다. 
    - .dt.year : 년도 / .df.month : 월 / .dt.day : 일

In [51]:
# 주문일에서 년/ 월/ 일 정보 추출
df['주문년도'] = df['주문일_타입변환'].dt.year
df['주문월'] = df['주문일_타입변환'].dt.month
df['주문일자'] = df['주문일_타입변환'].dt.day

# 결과 확인 
df[['고객명', '주문일', '주문년도', '주문월', '주문일자']].head()

      고객명           주문일  주문년도  주문월  주문일자
고객ID
C001  김민수  2024년 1월 15일  2024    1    15
C002  이영희   2024년 2월 3일  2024    2     3
C003  박철수  2024년 2월 14일  2024    2    14
C004  최지영   2024년 3월 8일  2024    3     8
C005  정한솔  2024년 3월 22일  2024    3    22

### 3. 요일 정보 추출

In [52]:
# 주문일 기준 요일 정보 추출 
df['주문요일영문'] = df['주문일_타입변환'].dt.day_name()    # 영문 요일명 
df['주문요일번호'] = df['주문일_타입변환'].dt.dayofweek   # 0=월요일, 6=일요일 

# 한글 요일명 매핑 
요일매핑 = {0:'월요일', 1:'화요일', 2:'수요일', 3:'목요일', 4:'금요일', 5:'토요일', 6:'일요일'}
df['주문요일'] = df['주문요일번호'].map(요일매핑)

# 결과확인 
df[['고객명', '주문일', '주문요일영문', '주문요일번호', '주문요일']].head()

      고객명           주문일     주문요일영문  주문요일번호 주문요일
고객ID
C001  김민수  2024년 1월 15일     Monday       0  월요일
C002  이영희   2024년 2월 3일   Saturday       5  토요일
C003  박철수  2024년 2월 14일  Wednesday       2  수요일
C004  최지영   2024년 3월 8일     Friday       4  금요일
C005  정한솔  2024년 3월 22일     Friday       4  금요일

In [53]:
# dt.dayofweek는 속성(attribute) 이라 () 붙이면 안 됨.
# dt.day_name()은 메서드라 () 필요하고, dt.dayofweek는 프로퍼티라 () 없이 써야 해.
# pythondf['주문요일번호'] = df['주문일_타입변환'].dt.dayofweek  # 괄호 제거
# 헷갈리면 이렇게 기억해:

# dt.day_name() → 함수처럼 동작, () 있음
# dt.dayofweek → 변수처럼 접근, () 없음

### 4. 분기와 몇 번째 날짜인지 추출

In [55]:
df['주문분기'] = df['주문일_타입변환'].dt.quarter       # 분기 (1~4)
df['연중몇일째'] = df['주문일_타입변환'].dt.dayofyear   # 1년 중 몇 번째 날 

# 결과 확인 
df[['고객명', '주문일', '주문분기', '연중몇일째']].head()

      고객명           주문일  주문분기  연중몇일째
고객ID
C001  김민수  2024년 1월 15일     1     15
C002  이영희   2024년 2월 3일     1     34
C003  박철수  2024년 2월 14일     1     45
C004  최지영   2024년 3월 8일     1     68
C005  정한솔  2024년 3월 22일     1     82

### 5. 시/ 분/ 초 추출

In [56]:
df['배송완료-시간'] = df['배송완료일시'].dt.hour 
df['배송완료-분'] = df['배송완료일시'].dt.minute
df['배송완료-초'] = df['배송완료일시'].dt.second

# 결과확인 
df[['고객명', '배송완료-시간', '배송완료-분', '배송완료-초']].head()

      고객명  배송완료-시간  배송완료-분  배송완료-초
고객ID
C001  김민수       14      30       0
C002  이영희       16      20       0
C003  박철수       11      45       0
C004  최지영       13      15       0
C005  정한솔        9      30       0

### 6. 날짜 간 차이 계산

(날짜2 - 날짜1).dt.days

- 두 날짜 타입간의 연산은 timedelta 객체를 생성한다.
- 이 객체에 대한 dt 속성을 통해 두 날짜간의 차이를 구할 수 있다.

In [60]:
df['배송소요일'] = (df['배송완료일시']- df['주문일_타입변환']).dt.days 
df[['주문일', '배송완료일시', '배송소요일']].head()

               주문일              배송완료일시  배송소요일
고객ID
C001  2024년 1월 15일 2024-01-17 14:30:00      2
C002   2024년 2월 3일 2024-02-05 16:20:00      2
C003  2024년 2월 14일 2024-02-16 11:45:00      2
C004   2024년 3월 8일 2024-03-10 13:15:00      2
C005  2024년 3월 22일 2024-03-24 09:30:00      2

### 7. 경과일 구하기

파이썬의 기본 내장 모듈인 datetime 객체를 사용하여 오늘 날짜를 생성하고, \
오늘 날짜에서 DataFrame의 날짜 타입 컬럼을 빼면, \
오늘 날짜와 해당 컬럼 간의 차이를 구할 수 있다.

In [61]:
오늘 = dt.now()

df['배송완료후_경과일'] = (오늘 - df['배송완료일시']).dt.days 

df[['주문일', '배송완료일시', '배송완료후_경과일']].head()

               주문일              배송완료일시  배송완료후_경과일
고객ID
C001  2024년 1월 15일 2024-01-17 14:30:00        888
C002   2024년 2월 3일 2024-02-05 16:20:00        869
C003  2024년 2월 14일 2024-02-16 11:45:00        858
C004   2024년 3월 8일 2024-03-10 13:15:00        835
C005  2024년 3월 22일 2024-03-24 09:30:00        821

### 8. 기준일로부터 년/ 월/ 일 더하기, 빼기( 파이썬 내장 API 사용)
- n일 더하거나 빼기 
    - Timedelta 객체는 n일에 대한 단위만 생성 가능하다. (년/월 등 다른 단위는 생성불가)
    - datetime.Timedelta(days = n)

In [62]:
# 재주문 예상일 ( 배송완료 후 30일 )
df['재주문예상일'] = df['배송완료일시'] + td(days = 30)

# 결과확인 
df[['고객명', '배송완료일시', '재주문예상일']].head()

      고객명              배송완료일시              재주문예상일
고객ID
C001  김민수 2024-01-17 14:30:00 2024-02-16 14:30:00
C002  이영희 2024-02-05 16:20:00 2024-03-06 16:20:00
C003  박철수 2024-02-16 11:45:00 2024-03-17 11:45:00
C004  최지영 2024-03-10 13:15:00 2024-04-09 13:15:00
C005  정한솔 2024-03-24 09:30:00 2024-04-23 09:30:00

### 9. 기준일로부터 년/ 월 / 일 더하기, 빼기 ( Pandas API 사용)
- Pandas의 DateOffset 객체는 연산을 위한 년/월/일/시/분/초 모든 단위에 대한 객체 생성 가능

In [ ]:
# 1년 A/S 보장 종료일 (주문일 기준) 
df['AS보장만료일'] = df['주문일_타입변환'] + DateOffset(years햣
                                             =1)

# 예상 매출 집계일 (주문일에서 3개월 후) 
df['매출집계예정일'] = df['주문일_타입변환'] + DateOffset(months=3)


# 리뷰 요청 예정 일시 (배송완료시점에서 7일 12시간 경과 후, 혼합사용 가능) 
df['리뷰요청예정'] = df['배송완료일시'] + DateOffset(days=3, hours=12)

# 결과확인 
df[['고객명', '주문일', 'AS보장만료일', '매출집계예정일', '리뷰요청예정']].head()

      고객명           주문일    AS보장만료일    매출집계예정일              리뷰요청예정
고객ID
C001  김민수  2024년 1월 15일 2025-01-15 2024-04-15 2024-01-21 02:30:00
C002  이영희   2024년 2월 3일 2025-02-03 2024-05-03 2024-02-09 04:20:00
C003  박철수  2024년 2월 14일 2025-02-14 2024-05-14 2024-02-19 23:45:00
C004  최지영   2024년 3월 8일 2025-03-08 2024-06-08 2024-03-14 01:15:00
C005  정한솔  2024년 3월 22일 2025-03-22 2024-06-22 2024-03-27 21:30:00