# [LAB-05] 4. 결측치 처리 - 연습문제 풀이

## 상점 판매 데이터 정제 챌린지 🛒

### 라이브러리 참조

In [ ]:
import numpy as np
from jussam import load_data
from sklearn.impute import SimpleImputer

### 데이터 불러오기

In [7]:
df = load_data("month_sales")
df

📚 데이터 정제(결측치 처리) 연습문제용 데이터

    field     description
--  --------  ----------------
 0  OrderID   주문번호(인덱스)
 1  Product   상품명
 2  Category  상품 카테고리
 3  Price     단가
 4  Quantity  주문 수량

          Product     Category    Price  Quantity
OrderID
1001       Laptop  Electronics 1200.000    10.000
1002        Mouse  Electronics   25.000       NaN
1003     Keyboard  Electronics      NaN     5.000
1004      Monitor  Electronics  300.000     8.000
1005       Webcam  Electronics   80.000       NaN
1006         Desk    Furniture  150.000     3.000
1007        Chair    Furniture      NaN     2.000
1008         Lamp    Furniture   40.000    15.000
1009     Notebook   Stationery    5.000   100.000
1010          Pen   Stationery    1.000       NaN

### 미션1: 각 열의 결측치 개수 확인

In [8]:
df.isnull().sum()

Product     0
Category    0
Price       2
Quantity    3
dtype: int64

### 미션2: 신뢰할 수 없는 데이터 제거

In [9]:
df2 = df.dropna(subset=['Quantity'])
df2

          Product     Category    Price  Quantity
OrderID
1001       Laptop  Electronics 1200.000    10.000
1003     Keyboard  Electronics      NaN     5.000
1004      Monitor  Electronics  300.000     8.000
1006         Desk    Furniture  150.000     3.000
1007        Chair    Furniture      NaN     2.000
1008         Lamp    Furniture   40.000    15.000
1009     Notebook   Stationery    5.000   100.000

### 미션 3: 가격 정보 복원

In [10]:
df2_reshape = df2['Price'].values.reshape(-1, 1)

imr = SimpleImputer(missing_values=np.nan, strategy='mean')
df_imr = imr.fit_transform(df2_reshape)

df3 = df2.copy()
df3['Price'] = df_imr
df3

          Product     Category    Price  Quantity
OrderID
1001       Laptop  Electronics 1200.000    10.000
1003     Keyboard  Electronics  339.000     5.000
1004      Monitor  Electronics  300.000     8.000
1006         Desk    Furniture  150.000     3.000
1007        Chair    Furniture  339.000     2.000
1008         Lamp    Furniture   40.000    15.000
1009     Notebook   Stationery    5.000   100.000