# [LAB 04] 6. 데이터 정렬, 필터링

## #01. 준비작업

### 1. 라이브러리 참조

In [1]:
from jussam import load_data

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

### 2. 데이터 불러오기

In [2]:
origin = load_data('grade')
origin

📚 어느 학급의 과목별 점수를 조사한 가상의 데이터

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

## #02. 데이터 정렬

### 1. 변수에 의한 정렬

- 원본에 즉시 반영해야 할 경우 `inplace=True` 파라미터를 적용
- `ascending=False` 파라미터는 내림차순 정렬을 설정함 (기본값=True, 오름차순)

In [3]:
단일정렬df = origin.sort_values('학년', ascending=False)
단일정렬df

    학년  성별  국어   영어  수학  과학
이름
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
수현   3  여자  63   60  31  71
영희   2  여자  88  120  62  72
용식   2  남자  82   88  79  90
철수   1  남자  98   77  88  64
민철   1  남자  92   70  83  79
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### 2. 여러 변수 정렬

- 정렬 기준이 되는 컬럼 이름을 리스트로 설정하면 첫 번째 컬럼의 값이 동일한 경우 두 번째 컬럼을 기준으로 정렬한다.
- 각 변수에 대한 정렬 옵션 역시 리스트로 설정한다.

In [4]:
복수정렬df = origin.sort_values(['학년', '국어'],
                            ascending=[False, False])
복수정렬df

    학년  성별  국어   영어  수학  과학
이름
영호   4  남자  80   88  91  72
호영   4  남자  75   50  90  88
수현   3  여자  63   60  31  71
영희   2  여자  88  120  62  72
용식   2  남자  82   88  79  90
철수   1  남자  98   77  88  64
민철   1  남자  92   70  83  79
석영   1  남자  91   90  89  80
나영   1  여자  90   92  81  95

### 3. 인덱스를 기준으로 하는 정렬

- 인덱스는 하나만 존재하므로 열 이름을 지정할 필요가 없다.
- 정렬 방향을 위한 `ascending` 파라미터를 `False`로 설정하면 내림차순으로 정렬된다.
- `inplace=True`를 적용할 경우 원본에 즉시 반영된다.

In [5]:
인덱스정렬df = origin.sort_index(ascending=False)
인덱스정렬df

    학년  성별  국어   영어  수학  과학
이름
호영   4  남자  75   50  90  88
철수   1  남자  98   77  88  64
용식   2  남자  82   88  79  90
영희   2  여자  88  120  62  72
영호   4  남자  80   88  91  72
수현   3  여자  63   60  31  71
석영   1  남자  91   90  89  80
민철   1  남자  92   70  83  79
나영   1  여자  90   92  81  95

## #03. 데이터 필터링

### 1. 숫자형 변수의 조건 검색

In [6]:
# r1 = origin[origin['국어'] > 80]
r1 = origin.query('국어 > 80')
r1

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### 2. 문자열 변수의 조건 검색

In [7]:
#r2 = origin[origin["성별"] == '남자']
r2 = origin.query("성별 == '남자'")
r2

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
민철   1  남자  92  70  83  79
호영   4  남자  75  50  90  88
영호   4  남자  80  88  91  72
용식   2  남자  82  88  79  90
석영   1  남자  91  90  89  80

### 3. AND 연산을 사용하는 조건 검색

In [8]:
#r3 = origin[(origin['국어'] > 80) & (origin['수학'] > 80)]
r3 = origin.query('국어 > 80 and 수학 > 80')
r3

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
민철   1  남자  92  70  83  79
나영   1  여자  90  92  81  95
석영   1  남자  91  90  89  80

### 4. OR 연산을 사용하는 조건 검색

In [9]:
#r4 = origin[(origin['국어'] <= 80) | (origin['수학'] <= 80)]
r4 = origin.query('국어 <= 80 or 수학 <= 80')
r4

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90

### 5. 비교식에 변수를 사용하는 조건 검색

- `@변수이름` 형태로 조건식에 포함한다.

In [10]:
point = int(input('점수를 입력하세요: '))
print("국어 점수가 %d점 보다 높은 학생" % point)

r5 = origin.query('국어 > @point')
r5

국어 점수가 82점 보다 높은 학생

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### 6. 열 단위 필터링

In [11]:
fl = origin.filter(['국어', '영어'])
fl

    국어   영어
이름
철수  98   77
영희  88  120
민철  92   70
수현  63   60
호영  75   50
영호  80   88
용식  82   88
나영  90   92
석영  91   90