# [LAB 04] 2. 데이터 구조 점검 (2)

## #01. 준비작업

### 1. 라이브러리 참조

In [1]:
from jussam import load_data
from pandas import Series

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

### 2. 데이터 가져오기

In [2]:
origin = load_data("grade")
origin

📚 어느 학급의 과목별 점수를 조사한 가상의 데이터

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

## #02. 행,열 재배치

### 1. 열 순서 변경

- 지정된 순서대로 열이 재정렬 된 결과가 반환된다.(`inplace` 파라미터 지원 안함)
- 원본은 변화 없음. 결과가 적용된 복사본이 생성된다.
- 재배치 되지 못한 열은 제외된다.

In [3]:
열순서_변경df = origin.reindex(columns=['국어','수학','과학','영어'])
열순서_변경df

    국어  수학  과학   영어
이름
철수  98  88  64   77
영희  88  62  72  120
민철  92  83  79   70
수현  63  31  71   60
호영  75  90  88   50
영호  80  91  72   88
용식  82  79  90   88
나영  90  81  95   92
석영  91  89  80   90

### 2. 행 순서 변경

- 지정된 순서대로 행이 재정렬 된 결과가 반환된다.
- 원본은 변화 없음. 결과가 적용된 복사본이 생성된다.
- 재배치 되지 못한 행은 제외된다.

In [4]:
행_순서변경df = origin.reindex(index=['석영','호영','민철','수현'])
행_순서변경df

    학년  성별  국어  영어  수학  과학
이름
석영   1  남자  91  90  89  80
호영   4  남자  75  50  90  88
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  71

## #03. 행 추가하기

### 1. 리스트로 행 추가하기

- 추가될 행의 인덱스 이름을 지정해야 한다.
- 리스트로 추가할 경우 DataFrame의 컬럼 순서에 맞게 지정해야 한다.
- 누락되는 값이 있거나 값의 수가 초과할 경우 에러

In [5]:
리스트_행추가df = origin.copy()
리스트_행추가df.loc['정호'] = [2, '남자', 90, 80, 70, 60]
리스트_행추가df

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80
정호   2  남자  90   80  70  60

### 2. 딕셔너리로 추가하기

-   컬럼 순서는 상관 없다.
-   누락되는 값이 있거나 값의 수가 초과할 경우 에러

In [6]:
딕셔너리_행추가df = origin.copy()
딕셔너리_행추가df.loc['민정'] = {'성별': '여자', '학년': 4, '국어': 81,
                              '영어': 72, '수학': 84, '과학': 90}
딕셔너리_행추가df

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80
민정   4  여자  81   72  84  90

### 3. Series 객체로 행 추가하기

- 순서는 상관 없다.
- Series 객체의 index가 DataFrame의 변수명과 동일해야 한다.

In [7]:
시리즈_행추가df = origin.copy()
s = Series([2, '남자', 90, 80, 70, 60],
           index=['학년', '성별', '국어', '영어', '수학', '과학'])
시리즈_행추가df.loc['형석'] = s
시리즈_행추가df

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80
형석   2  남자  90   80  70  60

### 4. 빈 값을 포함하는 행 추가하기

- 데이터를 추가할 때 값이 없는 필드는 생략할 수 있다.
- Series 형태의 객체로 추가할 때만 가능함

In [8]:
빈값_행추가df = origin.copy()
s = Series([2, '남자', 93, 71],
           index=['학년', '성별', '국어', '수학'])
빈값_행추가df.loc['석호'] = s
빈값_행추가df

    학년  성별  국어      영어  수학     과학
이름
철수   1  남자  98  77.000  88 64.000
영희   2  여자  88 120.000  62 72.000
민철   1  남자  92  70.000  83 79.000
수현   3  여자  63  60.000  31 71.000
호영   4  남자  75  50.000  90 88.000
영호   4  남자  80  88.000  91 72.000
용식   2  남자  82  88.000  79 90.000
나영   1  여자  90  92.000  81 95.000
석영   1  남자  91  90.000  89 80.000
석호   2  남자  93     NaN  71    NaN

### 5. 기존의 행을 복사해서 행 추가 하기

In [9]:
행_복사df = origin.copy()
행_복사df.loc['철민'] = 행_복사df.loc['철수']
행_복사df

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80
철민   1  남자  98   77  88  64

### 6. 단일 값으로 행 추가하기

- 모든 변수에 같은 값이 저장된다.

In [10]:
단일값_행추가df = origin.copy()
단일값_행추가df.loc['희영'] = 100
단일값_행추가df

     학년   성별   국어   영어   수학   과학
이름
철수    1   남자   98   77   88   64
영희    2   여자   88  120   62   72
민철    1   남자   92   70   83   79
수현    3   여자   63   60   31   71
호영    4   남자   75   50   90   88
영호    4   남자   80   88   91   72
용식    2   남자   82   88   79   90
나영    1   여자   90   92   81   95
석영    1   남자   91   90   89   80
희영  100  100  100  100  100  100

## #04. 열 추가하기

### 1. 리스트로 열 추가하기

- 모든 행에 대한 값을 순서대로 나열한다.
- 기존의 행과 비교하여 추가되는 값이 부족하거나 초과하면 에러 발생
- 빈값을 추가하고자 하는 경우 해당 위치에 `None`이라고 명시

In [11]:
리스트_열추가df = origin.copy()
리스트_열추가df['한국사'] = [72, 56, 90, None, 92, 90, 75, 80, 60]
리스트_열추가df

    학년  성별  국어   영어  수학  과학    한국사
이름
철수   1  남자  98   77  88  64 72.000
영희   2  여자  88  120  62  72 56.000
민철   1  남자  92   70  83  79 90.000
수현   3  여자  63   60  31  71    NaN
호영   4  남자  75   50  90  88 92.000
영호   4  남자  80   88  91  72 90.000
용식   2  남자  82   88  79  90 75.000
나영   1  여자  90   92  81  95 80.000
석영   1  남자  91   90  89  80 60.000

### 2. 딕셔너리로 열 추가하기

- 추가되지 않을 행은 명시하지 않는다.
- 데이터프레임에 존재하지 않는 인덱스가 포함될 경우 해당 값을 버린다.
- 명시되지 않은 행은 빈값(`NaN`)으로 설정된다.

In [12]:
딕셔너리_열추가df = origin.copy()
딕셔너리_열추가df['세계사'] = {"철수": 90, "영희": 88, "민철": 72, "수현": 56,
                            "호민": 65, "용식": 77, "나영": 95, "석영": 54}
딕셔너리_열추가df

    학년  성별  국어   영어  수학  과학    세계사
이름
철수   1  남자  98   77  88  64 90.000
영희   2  여자  88  120  62  72 88.000
민철   1  남자  92   70  83  79 72.000
수현   3  여자  63   60  31  71 56.000
호영   4  남자  75   50  90  88    NaN
영호   4  남자  80   88  91  72    NaN
용식   2  남자  82   88  79  90 77.000
나영   1  여자  90   92  81  95 95.000
석영   1  남자  91   90  89  80 54.000

### 3. Series 객체로 추가하기

- 각 값이 연결될 행의 이름(index)를 지정해야 한다.
- 부분적으로 값을 비워 둘 수 있다.

In [13]:
시리즈_열추가df = origin.copy()
s = Series([72, 56, 90, 88], index=['철수', '민철', '호영', '용식'])
시리즈_열추가df['윤리'] = s
시리즈_열추가df

    학년  성별  국어   영어  수학  과학     윤리
이름
철수   1  남자  98   77  88  64 72.000
영희   2  여자  88  120  62  72    NaN
민철   1  남자  92   70  83  79 56.000
수현   3  여자  63   60  31  71    NaN
호영   4  남자  75   50  90  88 90.000
영호   4  남자  80   88  91  72    NaN
용식   2  남자  82   88  79  90 88.000
나영   1  여자  90   92  81  95    NaN
석영   1  남자  91   90  89  80    NaN

### 4. 기존의 열을 복사해서 열 추가하기

In [14]:
열_복사df = origin.copy()
열_복사df['체육'] = 열_복사df['과학']
열_복사df

    학년  성별  국어   영어  수학  과학  체육
이름
철수   1  남자  98   77  88  64  64
영희   2  여자  88  120  62  72  72
민철   1  남자  92   70  83  79  79
수현   3  여자  63   60  31  71  71
호영   4  남자  75   50  90  88  88
영호   4  남자  80   88  91  72  72
용식   2  남자  82   88  79  90  90
나영   1  여자  90   92  81  95  95
석영   1  남자  91   90  89  80  80

### 5. 단일 값으로 열 추가하기

In [15]:
단일_값추가df = origin.copy()
단일_값추가df['체육'] = 100
단일_값추가df

    학년  성별  국어   영어  수학  과학   체육
이름
철수   1  남자  98   77  88  64  100
영희   2  여자  88  120  62  72  100
민철   1  남자  92   70  83  79  100
수현   3  여자  63   60  31  71  100
호영   4  남자  75   50  90  88  100
영호   4  남자  80   88  91  72  100
용식   2  남자  82   88  79  90  100
나영   1  여자  90   92  81  95  100
석영   1  남자  91   90  89  80  100

## #05. 행 삭제하기

### 1. 단일 행 삭제

- 추가는 원본 자체가 변하지만 삭제는 결과가 반영된 새로운 복사본이 생성된다.
- `drop()` 메서드도 `inplace=True` 파라미터 적용 가능

In [16]:
행_삭제df = origin.copy()
행_삭제df = 행_삭제df.drop(index='철수')
행_삭제df

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### 2. 다중 행 삭제

- 삭제할 행의 인덱스를 리스트로 지정한다.

In [17]:
다중삭제df = origin.copy()
다중삭제결과df = 다중삭제df.drop(index=['철수','민철','수현'])
다중삭제결과df

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### 3. index에 대한 인덱싱으로 행 삭제

In [18]:
인덱싱_행_삭제df = origin.copy()
인덱싱_행_삭제df.index

Index(['철수', '영희', '민철', '수현', '호영', '영호', '용식', '나영', '석영'], dtype='str', name='이름')

In [19]:
인덱싱_행_삭제결과df = 인덱싱_행_삭제df.drop(index=인덱싱_행_삭제df.index[0])
인덱싱_행_삭제결과df

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### 4. index에 대한 슬라이싱으로 행 삭제

In [20]:
다중_행_삭제df = origin.copy()
print(다중_행_삭제df.index)

다중_행_삭제결과df = 다중_행_삭제df.drop(index=다중_행_삭제df.index[0:7])
다중_행_삭제결과df

Index(['철수', '영희', '민철', '수현', '호영', '영호', '용식', '나영', '석영'], dtype='str', name='이름')

    학년  성별  국어  영어  수학  과학
이름
나영   1  여자  90  92  81  95
석영   1  남자  91  90  89  80

## #06 열 삭제

### 1. 단일 열 삭제

- 행 삭제는 `drop()` 메서드에 `index` 파라미터를 설정하고,     
  열 삭제는 `columns` 파라미터를 설정한다.

In [21]:
단일_열_삭제df = origin.copy()
단일_열_삭제결과df = 단일_열_삭제df.drop(columns='학년')
단일_열_삭제결과df

    성별  국어   영어  수학  과학
이름
철수  남자  98   77  88  64
영희  여자  88  120  62  72
민철  남자  92   70  83  79
수현  여자  63   60  31  71
호영  남자  75   50  90  88
영호  남자  80   88  91  72
용식  남자  82   88  79  90
나영  여자  90   92  81  95
석영  남자  91   90  89  80

### 2. 다중 열 삭제

- `columns` 파라미터에 삭제 대상 변수 이름을 리스트 타입으로 설정한다.

In [22]:
다중_열_삭제df = origin.copy()
다중_열_삭제결과df = 다중_열_삭제df.drop(columns=['학년','성별','과학'])
다중_열_삭제결과df

    국어   영어  수학
이름
철수  98   77  88
영희  88  120  62
민철  92   70  83
수현  63   60  31
호영  75   50  90
영호  80   88  91
용식  82   88  79
나영  90   92  81
석영  91   90  89

### 3. 컬럼명에 대한 인덱싱으로 열 삭제

In [23]:
인덱싱_열_삭제df = origin.copy()
print(인덱싱_열_삭제df.columns) # 컬럼 이름에 대한 연속성 객체

인덱싱_열_삭제결과df = 인덱싱_열_삭제df.drop(columns=인덱싱_열_삭제df.columns[0])
인덱싱_열_삭제결과df

Index(['학년', '성별', '국어', '영어', '수학', '과학'], dtype='str')

    성별  국어   영어  수학  과학
이름
철수  남자  98   77  88  64
영희  여자  88  120  62  72
민철  남자  92   70  83  79
수현  여자  63   60  31  71
호영  남자  75   50  90  88
영호  남자  80   88  91  72
용식  남자  82   88  79  90
나영  여자  90   92  81  95
석영  남자  91   90  89  80

### 4. 컬럼명에 대한 슬라이싱으로 열 삭제

In [24]:
다중_열_삭제df = origin.copy()
print(다중_열_삭제df.columns)

다중_열_삭제결과df = 다중_열_삭제df.drop(columns=다중_열_삭제df.columns[1:-2])
다중_열_삭제결과df

Index(['학년', '성별', '국어', '영어', '수학', '과학'], dtype='str')

    학년  수학  과학
이름
철수   1  88  64
영희   2  62  72
민철   1  83  79
수현   3  31  71
호영   4  90  88
영호   4  91  72
용식   2  79  90
나영   1  81  95
석영   1  89  80

## #07. 축을 지정하여 행˙열 삭제

### 1. 축(`axis`)를 설정한 단일 행 삭제 방법

- 파라미터 이름을 지정하지 않을 경우 `index`이름으로 처리됨

In [25]:
df1 = origin.drop('철수')
df1

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### 2. 축(axis)를 설정한 다중 행 삭제 방법

   여러 행을 삭제할 경우 인덱스 이름을 리스트로 전달

In [26]:
df2 = origin.drop(['철수', '영희', '민철', '수현'])
df2

    학년  성별  국어  영어  수학  과학
이름
호영   4  남자  75  50  90  88
영호   4  남자  80  88  91  72
용식   2  남자  82  88  79  90
나영   1  여자  90  92  81  95
석영   1  남자  91  90  89  80

### 3. 축(aixs)를 설정한 열 삭제 방법

   열을 삭제할 경우 축을 설정 (기본값=`0`, 행)

In [27]:
df3 = origin.drop(['학년', '성별'], axis=1)
df3

    국어   영어  수학  과학
이름
철수  98   77  88  64
영희  88  120  62  72
민철  92   70  83  79
수현  63   60  31  71
호영  75   50  90  88
영호  80   88  91  72
용식  82   88  79  90
나영  90   92  81  95
석영  91   90  89  80