# [LAB-04] 9. 파생변수

## #01. 준비작업

### 1. 라이브러리 참조

In [1]:
from jussam import load_data
from pandas import cut
import numpy as np

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

### 2. 데이터 가져오기

In [2]:
origin = load_data("grade")
origin

📚 어느 학급의 과목별 점수를 조사한 가상의 데이터

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

## #02. 파생변수 추가하기

### 1. 컬럼 연산을 통한 새로운 컬럼 추가

In [3]:
df1 = origin.copy()
df1["직접합계"] = df1["국어"] + df1["영어"] + df1["수학"] + df1["과학"]
df1

    학년  성별  국어   영어  수학  과학  직접합계
이름
철수   1  남자  98   77  88  64   327
영희   2  여자  88  120  62  72   342
민철   1  남자  92   70  83  79   324
수현   3  여자  63   60  31  71   225
호영   4  남자  75   50  90  88   303
영호   4  남자  80   88  91  72   331
용식   2  남자  82   88  79  90   339
나영   1  여자  90   92  81  95   358
석영   1  남자  91   90  89  80   350

### 2. 기술통계값 관련 함수를 사용한 파생변수

#### 1) 컬럼 이름에 대한 슬라이싱 접근

- `axis=1`: x축
- `axis=0`: y축

In [4]:
df2 = origin.copy()
df2["합계"] = df2[df2.columns[2:6]].sum(axis=1)
df2

    학년  성별  국어   영어  수학  과학   합계
이름
철수   1  남자  98   77  88  64  327
영희   2  여자  88  120  62  72  342
민철   1  남자  92   70  83  79  324
수현   3  여자  63   60  31  71  225
호영   4  남자  75   50  90  88  303
영호   4  남자  80   88  91  72  331
용식   2  남자  82   88  79  90  339
나영   1  여자  90   92  81  95  358
석영   1  남자  91   90  89  80  350

#### 2) 인덱스 기반 위치로 슬라이싱하여 합계변수 추가

In [5]:
df3 = origin.copy()
df3["합계"] = df3.iloc[:, 2:].sum(axis=1)
df3

    학년  성별  국어   영어  수학  과학   합계
이름
철수   1  남자  98   77  88  64  327
영희   2  여자  88  120  62  72  342
민철   1  남자  92   70  83  79  324
수현   3  여자  63   60  31  71  225
호영   4  남자  75   50  90  88  303
영호   4  남자  80   88  91  72  331
용식   2  남자  82   88  79  90  339
나영   1  여자  90   92  81  95  358
석영   1  남자  91   90  89  80  350

#### 3) 나머지 기술통계 값 추가

In [6]:
df3["평균"] = df3.iloc[:, 2:6].mean(axis=1)
df3["최대값"] = df3.iloc[:, 2:6].max(axis=1)
df3["최소값"] = df3.iloc[:, 2:6].min(axis=1)
df3["표준편차"] = df3.iloc[:, 2:6].std(axis=1)
df3["분산"] = df3.iloc[:, 2:6].var(axis=1)
df3

    학년  성별  국어   영어  수학  과학   합계     평균  최대값  최소값   표준편차      분산
이름
철수   1  남자  98   77  88  64  327 81.750   98   64 14.614 213.583
영희   2  여자  88  120  62  72  342 85.500  120   62 25.371 643.667
민철   1  남자  92   70  83  79  324 81.000   92   70  9.129  83.333
수현   3  여자  63   60  31  71  225 56.250   71   31 17.462 304.917
호영   4  남자  75   50  90  88  303 75.750   90   50 18.410 338.917
영호   4  남자  80   88  91  72  331 82.750   91   72  8.539  72.917
용식   2  남자  82   88  79  90  339 84.750   90   79  5.123  26.250
나영   1  여자  90   92  81  95  358 89.500   95   81  6.028  36.333
석영   1  남자  91   90  89  80  350 87.500   91   80  5.066  25.667

## #03. 조건별 파생변수

### 1. `if~else`

#### 1) 실습을 위해 합계와 평균에 대한 파생변수 추가

In [7]:
df4 = origin.copy()
df4["합계"] = df4.iloc[:, 2:6].sum(axis=1)
df4["평균"] = df4.iloc[:, 2:6].mean(axis=1)
df4

    학년  성별  국어   영어  수학  과학   합계     평균
이름
철수   1  남자  98   77  88  64  327 81.750
영희   2  여자  88  120  62  72  342 85.500
민철   1  남자  92   70  83  79  324 81.000
수현   3  여자  63   60  31  71  225 56.250
호영   4  남자  75   50  90  88  303 75.750
영호   4  남자  80   88  91  72  331 82.750
용식   2  남자  82   88  79  90  339 84.750
나영   1  여자  90   92  81  95  358 89.500
석영   1  남자  91   90  89  80  350 87.500

#### 2) NumPy의 where 함수를 사용한 조건부 파생 변수

In [8]:
df4["결과1"] = np.where(df4["평균"] >= 80, "합격", "불합격")
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1
이름
철수   1  남자  98   77  88  64  327 81.750   합격
영희   2  여자  88  120  62  72  342 85.500   합격
민철   1  남자  92   70  83  79  324 81.000   합격
수현   3  여자  63   60  31  71  225 56.250  불합격
호영   4  남자  75   50  90  88  303 75.750  불합격
영호   4  남자  80   88  91  72  331 82.750   합격
용식   2  남자  82   88  79  90  339 84.750   합격
나영   1  여자  90   92  81  95  358 89.500   합격
석영   1  남자  91   90  89  80  350 87.500   합격

#### 3) 표현식을 사용한 평균값에 따른 조건부 파생변수

In [9]:
df4["결과2"] = "불합격"
df4.loc[df4["평균"] >= 80, "결과2"] = "합격"
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격
영희   2  여자  88  120  62  72  342 85.500   합격   합격
민철   1  남자  92   70  83  79  324 81.000   합격   합격
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격
영호   4  남자  80   88  91  72  331 82.750   합격   합격
용식   2  남자  82   88  79  90  339 84.750   합격   합격
나영   1  여자  90   92  81  95  358 89.500   합격   합격
석영   1  남자  91   90  89  80  350 87.500   합격   합격

### 2. 경우의 수에 따른 조건값 (`elif`)- numpy의 `select` 함수 사용

In [10]:
# 학점을 부여하기 위한 점수의 구간을 설정하는 조건들을 리스트로 설정
conditions = [
    (df4["평균"] >= 90),  # if
    (df4["평균"] >= 80),  # elif
    (df4["평균"] >= 70),  # elif
]
# 조건에 따라 부여될 학점
value = ["A", "B", "C"]
#                        조건        값        else
df4["학점1"] = np.select(conditions, value, default="F")
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2 학점1
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격   B
영희   2  여자  88  120  62  72  342 85.500   합격   합격   B
민철   1  남자  92   70  83  79  324 81.000   합격   합격   B
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격   F
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격   C
영호   4  남자  80   88  91  72  331 82.750   합격   합격   B
용식   2  남자  82   88  79  90  339 84.750   합격   합격   B
나영   1  여자  90   92  81  95  358 89.500   합격   합격   B
석영   1  남자  91   90  89  80  350 87.500   합격   합격   B

### 3. 사용자 정의 함수 사용

#### 1) 함수 정의하기

In [11]:
def getScore(x):
    if x >= 90:
        score = "A"
    elif x >= 80:
        score = "B"
    elif x >= 70:
        score = "C"
    else:
        score = "F"

    return score

#### 2) 함수의 리턴값으로 파생변수 추가하기

In [12]:
df4["학점2"] = df4["평균"].apply(getScore)
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2 학점1 학점2
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격   B   B
영희   2  여자  88  120  62  72  342 85.500   합격   합격   B   B
민철   1  남자  92   70  83  79  324 81.000   합격   합격   B   B
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격   F   F
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격   C   C
영호   4  남자  80   88  91  72  331 82.750   합격   합격   B   B
용식   2  남자  82   88  79  90  339 84.750   합격   합격   B   B
나영   1  여자  90   92  81  95  358 89.500   합격   합격   B   B
석영   1  남자  91   90  89  80  350 87.500   합격   합격   B   B

#### 3) 함수 정의 없이 람다식으로 익명함수 적용하기

In [13]:
df4["학점3"] = df4["평균"].apply(
    lambda x: {10: "A", 9: "A", 8: "B", 7: "C"}.get(x // 10, "F")
)
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2 학점1 학점2 학점3
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격   B   B   B
영희   2  여자  88  120  62  72  342 85.500   합격   합격   B   B   B
민철   1  남자  92   70  83  79  324 81.000   합격   합격   B   B   B
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격   F   F   F
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격   C   C   C
영호   4  남자  80   88  91  72  331 82.750   합격   합격   B   B   B
용식   2  남자  82   88  79  90  339 84.750   합격   합격   B   B   B
나영   1  여자  90   92  81  95  358 89.500   합격   합격   B   B   B
석영   1  남자  91   90  89  80  350 87.500   합격   합격   B   B   B

### 4. `map()` 메서드 활용

- 앞의 방법처럼 연산을 사용할 수는 없고 값이 완전히 일치하는 경우에만 사용할 수 있음.

In [14]:
df4["성별코드"] = df4["성별"].map({"남자": "M", "여자": "F"})
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2 학점1 학점2 학점3 성별코드
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격   B   B   B    M
영희   2  여자  88  120  62  72  342 85.500   합격   합격   B   B   B    F
민철   1  남자  92   70  83  79  324 81.000   합격   합격   B   B   B    M
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격   F   F   F    F
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격   C   C   C    M
영호   4  남자  80   88  91  72  331 82.750   합격   합격   B   B   B    M
용식   2  남자  82   88  79  90  339 84.750   합격   합격   B   B   B    M
나영   1  여자  90   92  81  95  358 89.500   합격   합격   B   B   B    F
석영   1  남자  91   90  89  80  350 87.500   합격   합격   B   B   B    M

### 5. Pandas의 cut 함수 사용

구간에 따른 파생변수 생성

- `0`이상 `70`미만 : **F**
- `70`이상 `80`미만 : **C**
- `80`이상 `90`미만 : **B**
- `90`이상 `100`이하 : **F** (마지막 구간은 **이하**)

In [15]:
df4["학점4"] = cut(
    df4["평균"],  # 대상 컬럼
    bins=[0, 70, 80, 90, 100],  # 구간 설정
    labels=["F", "C", "B", "A"],  # 구간별 값 설정
)
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2 학점1 학점2 학점3 성별코드 학점4
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격   B   B   B    M   B
영희   2  여자  88  120  62  72  342 85.500   합격   합격   B   B   B    F   B
민철   1  남자  92   70  83  79  324 81.000   합격   합격   B   B   B    M   B
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격   F   F   F    F   F
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격   C   C   C    M   C
영호   4  남자  80   88  91  72  331 82.750   합격   합격   B   B   B    M   B
용식   2  남자  82   88  79  90  339 84.750   합격   합격   B   B   B    M   B
나영   1  여자  90   92  81  95  358 89.500   합격   합격   B   B   B    F   B
석영   1  남자  91   90  89  80  350 87.500   합격   합격   B   B   B    M   B