# [LAB 04] 2. 데이터 구조 점검 (2)

## 연습문제

### 라이브러리 참조

In [1]:
from jussam import load_data
from pandas import Series

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

###  데이터 가져오기

In [2]:
monsters = load_data('monsters')
monsters

📚 신비한 생물 연구소의 몬스터 데이터

    field          description
--  -------------  ----------------------
 0  monster_id     몬스터 고유 ID(인덱스)
 1  last_seen      마지막으로 관찰된 날짜
 2  species        생물 종
 3  habitat        서식지
 4  height         키 (m)
 5  weight         몸무게 (kg)
 6  caution_level  위험 등급

            last_seen   species   habitat  height    weight caution_level
monster_id
M001       2024-01-15   Griffin  Mountain   2.500   150.500          High
M002       2024-02-20   Unicorn    Forest   2.100   120.000           Low
M003       2024-03-10    Dragon   Volcano  15.200  5500.000     Very High
M004       2024-03-12    Dragon   Volcano  14.800  5300.000     Very High
M005       2024-04-05    Kraken     Ocean  30.500 15000.000          High
M006       2024-05-21   Phoenix    Desert   1.800    25.500        Medium
M007       2024-06-30   Mermaid     Ocean   1.900    65.500           Low
M008       2024-07-14    Goblin      Cave   1.100    40.200        Medium
M009       2024-08-01     Fairy    Forest   0.300     0.500           Low
M010       2024-09-10     Hydra     Swamp   5.500   800.000          High
M011       2024-10-02   Cyclops    Island   8.200  2500.000          High
M012       2024-11-18     Gnome    Garden   0.400     5.100           Low
M013       2024-12-25      Yeti  Mountain   3.500   300.000        Medium
M014       2025-01-20    Sphinx    Desert   2.800   180.000        Medium
M015       2025-02-15   Banshee     Ruins   1.700    45.000          High
M016       2025-03-22  Werewolf    Forest   2.300   110.000          High
M017       2025-04-18   Vampire    Castle   1.800    75.000          High
M018       2025-05-30   Chimera  Mountain   3.100   450.000     Very High
M019       2025-06-11  Basilisk     Sewer   4.000   200.000     Very High
M020       2025-07-07  Gargoyle   Rooftop   2.000   500.000        Medium

### 1. 데이터의 첫인상

In [3]:
monsters.info()

<class 'pandas.DataFrame'>
Index: 20 entries, M001 to M020
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   last_seen      20 non-null     datetime64[us]
 1   species        20 non-null     str
 2   habitat        20 non-null     str
 3   height         20 non-null     float64
 4   weight         20 non-null     float64
 5   caution_level  20 non-null     str
dtypes: datetime64[us](1), float64(2), str(3)
memory usage: 1.5 KB

### 2. 쓸모 없는 정보 삭제

In [4]:
df1 = monsters.drop(columns='last_seen')
df1.head()

            species   habitat  height    weight caution_level
monster_id
M001        Griffin  Mountain   2.500   150.500          High
M002        Unicorn    Forest   2.100   120.000           Low
M003         Dragon   Volcano  15.200  5500.000     Very High
M004         Dragon   Volcano  14.800  5300.000     Very High
M005         Kraken     Ocean  30.500 15000.000          High

### 3. 신규 개체 추가

In [5]:
new_monster = Series({'height': 2.2, 'species': 'Kelpie', 'caution_level': 'Medium'})

df2 = df1.copy()
df2.loc['M021'] = new_monster
df2

             species   habitat  height    weight caution_level
monster_id
M001         Griffin  Mountain   2.500   150.500          High
M002         Unicorn    Forest   2.100   120.000           Low
M003          Dragon   Volcano  15.200  5500.000     Very High
M004          Dragon   Volcano  14.800  5300.000     Very High
M005          Kraken     Ocean  30.500 15000.000          High
M006         Phoenix    Desert   1.800    25.500        Medium
M007         Mermaid     Ocean   1.900    65.500           Low
M008          Goblin      Cave   1.100    40.200        Medium
M009           Fairy    Forest   0.300     0.500           Low
M010           Hydra     Swamp   5.500   800.000          High
M011         Cyclops    Island   8.200  2500.000          High
M012           Gnome    Garden   0.400     5.100           Low
M013            Yeti  Mountain   3.500   300.000        Medium
M014          Sphinx    Desert   2.800   180.000        Medium
M015         Banshee     Ruins   1.700    45.000          High
M016        Werewolf    Forest   2.300   110.000          High
M017         Vampire    Castle   1.800    75.000          High
M018         Chimera  Mountain   3.100   450.000     Very High
M019        Basilisk     Sewer   4.000   200.000     Very High
M020        Gargoyle   Rooftop   2.000   500.000        Medium
M021          Kelpie       NaN   2.200       NaN        Medium

### 3. 데이터 오류 수정

In [6]:
# 인덱스도 M003_copy로 변경해야 하므로 인덱스 해제
df3 = df2.reset_index()

df3.loc[3] = df3.loc[2].copy()
df3.loc[3, 'monster_id'] = 'M003_copy'
df3

   monster_id   species   habitat  height    weight caution_level
0        M001   Griffin  Mountain   2.500   150.500          High
1        M002   Unicorn    Forest   2.100   120.000           Low
2        M003    Dragon   Volcano  15.200  5500.000     Very High
3   M003_copy    Dragon   Volcano  15.200  5500.000     Very High
4        M005    Kraken     Ocean  30.500 15000.000          High
5        M006   Phoenix    Desert   1.800    25.500        Medium
6        M007   Mermaid     Ocean   1.900    65.500           Low
7        M008    Goblin      Cave   1.100    40.200        Medium
8        M009     Fairy    Forest   0.300     0.500           Low
9        M010     Hydra     Swamp   5.500   800.000          High
10       M011   Cyclops    Island   8.200  2500.000          High
11       M012     Gnome    Garden   0.400     5.100           Low
12       M013      Yeti  Mountain   3.500   300.000        Medium
13       M014    Sphinx    Desert   2.800   180.000        Medium
14       M015   Banshee     Ruins   1.700    45.000          High
15       M016  Werewolf    Forest   2.300   110.000          High
16       M017   Vampire    Castle   1.800    75.000          High
17       M018   Chimera  Mountain   3.100   450.000     Very High
18       M019  Basilisk     Sewer   4.000   200.000     Very High
19       M020  Gargoyle   Rooftop   2.000   500.000        Medium
20       M021    Kelpie       NaN   2.200       NaN        Medium

### 5. 최종 보고서용 정렬

In [7]:
df4 = df3.reindex(columns=['monster_id', 'caution_level', 'species', 'habitat', 'height', 'weight'])
df4

   monster_id caution_level   species   habitat  height    weight
0        M001          High   Griffin  Mountain   2.500   150.500
1        M002           Low   Unicorn    Forest   2.100   120.000
2        M003     Very High    Dragon   Volcano  15.200  5500.000
3   M003_copy     Very High    Dragon   Volcano  15.200  5500.000
4        M005          High    Kraken     Ocean  30.500 15000.000
5        M006        Medium   Phoenix    Desert   1.800    25.500
6        M007           Low   Mermaid     Ocean   1.900    65.500
7        M008        Medium    Goblin      Cave   1.100    40.200
8        M009           Low     Fairy    Forest   0.300     0.500
9        M010          High     Hydra     Swamp   5.500   800.000
10       M011          High   Cyclops    Island   8.200  2500.000
11       M012           Low     Gnome    Garden   0.400     5.100
12       M013        Medium      Yeti  Mountain   3.500   300.000
13       M014        Medium    Sphinx    Desert   2.800   180.000
14       M015          High   Banshee     Ruins   1.700    45.000
15       M016          High  Werewolf    Forest   2.300   110.000
16       M017          High   Vampire    Castle   1.800    75.000
17       M018     Very High   Chimera  Mountain   3.100   450.000
18       M019     Very High  Basilisk     Sewer   4.000   200.000
19       M020        Medium  Gargoyle   Rooftop   2.000   500.000
20       M021        Medium    Kelpie       NaN   2.200       NaN