# [LAB 04] 6. 데이터 정렬, 필터링 - 연습문제 풀이

## 준비작업

### 라이브러리 참조

In [1]:
from jussam import load_data

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

### 데이터 가져오기

In [2]:
df = load_data('vip_customer')
df

📚 VIP 고객 목록 데이터

    field             description
--  ----------------  ----------------
 0  CustomerID        고객번호
 1  Name              고객명
 2  Age               나이
 3  City              거주지역
 4  JoinDate          가입일
 5  TotalSpending     총 지출액
 6  LastPurchaseDate  마지막 구매 날짜

           Name  Age City   JoinDate  TotalSpending LastPurchaseDate
CustomerID
1001        김철수   35   서울 2022-01-15         150000       2023-11-01
1002        이영희   28   부산 2021-03-22          80000       2023-10-15
1003        박민준   42   서울 2022-07-10         250000       2023-11-10
1004        최지우   25   인천 2023-02-20          50000       2023-09-25
1005        정다솜   31   서울 2021-11-05         320000       2023-11-12
1006        윤현우   38   부산 2022-05-30         120000       2023-11-05
1007        강예진   29   서울 2023-01-15          85000       2023-10-22
1008        오승민   45   광주 2021-08-12         180000       2023-11-08
1009        한지민   27   서울 2022-10-01         450000       2023-11-15
1010        송서연   33   대전 2023-04-01          65000       2023-09-30
1011        임도윤   39   서울 2021-06-18         210000       2023-11-02
1012        장유나   26   부산 2023-03-10          40000       2023-08-15
1013        황재민   41   서울 2022-09-05         190000       2023-11-07
1014        신은경   30   대구 2021-12-20          95000       2023-10-18
1015        고은별   36   서울 2023-05-25         130000       2023-11-11

## 요구사항 처리

### 조건에 따른 필터링

In [3]:
# 조건 1: 총 구매액 100,000원 이상
# 조건 2: 서울 거주 고객
df2 = df.query("TotalSpending >= 100000 and City == '서울'")
df2

           Name  Age City   JoinDate  TotalSpending LastPurchaseDate
CustomerID
1001        김철수   35   서울 2022-01-15         150000       2023-11-01
1003        박민준   42   서울 2022-07-10         250000       2023-11-10
1005        정다솜   31   서울 2021-11-05         320000       2023-11-12
1009        한지민   27   서울 2022-10-01         450000       2023-11-15
1011        임도윤   39   서울 2021-06-18         210000       2023-11-02
1013        황재민   41   서울 2022-09-05         190000       2023-11-07
1015        고은별   36   서울 2023-05-25         130000       2023-11-11

### 보고할 내용 생성

In [4]:
# 총 지출액 기준 내림차순 정렬
sorted_vips = df2.sort_values(by='TotalSpending', ascending=False)

# 상위 5명 고객 추출
top5_vips = sorted_vips.head(5)

# 최종 보고에 필요한 'Name', 'City', 'TotalSpending' 열 선택
final_report = top5_vips.filter(['Name', 'City', 'TotalSpending'])

# 결과 출력
final_report

           Name City  TotalSpending
CustomerID
1009        한지민   서울         450000
1005        정다솜   서울         320000
1003        박민준   서울         250000
1011        임도윤   서울         210000
1013        황재민   서울         190000