# [LAB 04] 데이터 다루기 - 13. 데이터 표준화

## #01. 준비작업

### 1. 라이브러리 참조

In [1]:
from jussam import load_data 

# 스케일링을 위해 사용 
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, StandardScaler, RobustScaler

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

### 2. 샘플 데이터 가져오기

In [2]:
origin = load_data('nursing_grades')
origin

📚 어느 간호학과 대학원에 지원한 학생들에 대한 합격/불합격 여부를 조사한 가상의 데이터(메타데이터 없음)

        접수코드   이름 성별  필기점수  학부성적  병원경력 합격여부
0    NRS0001  장은우  남   380 3.610     3  불합격
1    NRS0002  최지호  남   660 3.670     3   합격
2    NRS0003  김하준  남   800 4.000     1   합격
3    NRS0004  임아윤  여   640 3.190     4   합격
4    NRS0005  강하준  남   520 2.930     4  불합격
..       ...  ... ..   ...   ...   ...  ...
395  NRS0396  박지유  여   620 4.000     2  불합격
396  NRS0397  조하은  여   560 3.040     3  불합격
397  NRS0398  박하윤  여   460 2.630     2  불합격
398  NRS0399  이지우  여   700 3.650     2  불합격
399  NRS0400  강하은  여   600 3.890     3  불합격

[400 rows x 7 columns]

## #02. Min-Max Scaler (정규화)

In [3]:
minmax_df = origin.copy()

x = minmax_df['필기점수']
xmin = x.min()
xmax = x.max()

minmax_df['필기점수_MinMax(1)'] = (x-xmin)/(xmax -xmin)
minmax_df.head()

      접수코드   이름 성별  필기점수  학부성적  병원경력 합격여부  필기점수_MinMax(1)
0  NRS0001  장은우  남   380 3.610     3  불합격           0.276
1  NRS0002  최지호  남   660 3.670     3   합격           0.759
2  NRS0003  김하준  남   800 4.000     1   합격           1.000
3  NRS0004  임아윤  여   640 3.190     4   합격           0.724
4  NRS0005  강하준  남   520 2.930     4  불합격           0.517

### 2. Sklearn 활용 
- 특정 필드만 추출

In [4]:
x = minmax_df[['필기점수']]
x.head()

   필기점수
0   380
1   660
2   800
3   640
4   520

### 2. Sklearn 활용
- 2) 스케일링 적용

In [5]:
scaler = MinMaxScaler()
minmax_df['필기점수_MinMax(2)'] = scaler.fit_transform(x) 
minmax_df.head()

      접수코드   이름 성별  필기점수  학부성적  병원경력 합격여부  필기점수_MinMax(1)  필기점수_MinMax(2)
0  NRS0001  장은우  남   380 3.610     3  불합격           0.276           0.276
1  NRS0002  최지호  남   660 3.670     3   합격           0.759           0.759
2  NRS0003  김하준  남   800 4.000     1   합격           1.000           1.000
3  NRS0004  임아윤  여   640 3.190     4   합격           0.724           0.724
4  NRS0005  강하준  남   520 2.930     4  불합격           0.517           0.517

## #03. Max - Abs Scaler

In [6]:
abs_df = origin.copy()
x = abs_df['필기점수']
abs_df['필기점수_MaxAbs(1)'] = x / x.abs().max()
abs_df.head()

      접수코드   이름 성별  필기점수  학부성적  병원경력 합격여부  필기점수_MaxAbs(1)
0  NRS0001  장은우  남   380 3.610     3  불합격           0.475
1  NRS0002  최지호  남   660 3.670     3   합격           0.825
2  NRS0003  김하준  남   800 4.000     1   합격           1.000
3  NRS0004  임아윤  여   640 3.190     4   합격           0.800
4  NRS0005  강하준  남   520 2.930     4  불합격           0.650

### 2. Sklearn 활용

In [7]:
scaler = MaxAbsScaler() 
x = abs_df[['필기점수']]
abs_df['필기점수_MaxAbs(2)'] = scaler.fit_transform(x)
abs_df.head()

      접수코드   이름 성별  필기점수  학부성적  병원경력 합격여부  필기점수_MaxAbs(1)  필기점수_MaxAbs(2)
0  NRS0001  장은우  남   380 3.610     3  불합격           0.475           0.475
1  NRS0002  최지호  남   660 3.670     3   합격           0.825           0.825
2  NRS0003  김하준  남   800 4.000     1   합격           1.000           1.000
3  NRS0004  임아윤  여   640 3.190     4   합격           0.800           0.800
4  NRS0005  강하준  남   520 2.930     4  불합격           0.650           0.650

## #04. Standard Scaler (z-score, 표준화)

In [8]:
std_df = origin.copy()
x = origin['학부성적']
std_df['학부성적_Standard(1)'] = (x - x.mean()) / x.std()
std_df.head()

      접수코드   이름 성별  필기점수  학부성적  병원경력 합격여부  학부성적_Standard(1)
0  NRS0001  장은우  남   380 3.610     3  불합격             0.578
1  NRS0002  최지호  남   660 3.670     3   합격             0.736
2  NRS0003  김하준  남   800 4.000     1   합격             1.603
3  NRS0004  임아윤  여   640 3.190     4   합격            -0.525
4  NRS0005  강하준  남   520 2.930     4  불합격            -1.208

### 2. Sklearn 활용

In [9]:
scaler = StandardScaler()
x = std_df[['학부성적']]
std_df['학부성적_Standard(2)'] = scaler.fit_transform(x)
std_df.head()

      접수코드   이름 성별  필기점수  학부성적  병원경력 합격여부  학부성적_Standard(1)  학부성적_Standard(2)
0  NRS0001  장은우  남   380 3.610     3  불합격             0.578             0.579
1  NRS0002  최지호  남   660 3.670     3   합격             0.736             0.737
2  NRS0003  김하준  남   800 4.000     1   합격             1.603             1.605
3  NRS0004  임아윤  여   640 3.190     4   합격            -0.525            -0.526
4  NRS0005  강하준  남   520 2.930     4  불합격            -1.208            -1.210

## #05. Robust Scaler

In [10]:
rb_df = origin.copy()

x = rb_df['병원경력']
m = x.median()
iqr = x.quantile(0.75) - x.quantile(0.25)

rb_df['병원경력_Robust(1)'] = (x-m) / iqr 
rb_df.head()

      접수코드   이름 성별  필기점수  학부성적  병원경력 합격여부  병원경력_Robust(1)
0  NRS0001  장은우  남   380 3.610     3  불합격           1.000
1  NRS0002  최지호  남   660 3.670     3   합격           1.000
2  NRS0003  김하준  남   800 4.000     1   합격          -1.000
3  NRS0004  임아윤  여   640 3.190     4   합격           2.000
4  NRS0005  강하준  남   520 2.930     4  불합격           2.000

### 2. Sklearn 활용

In [11]:
scaler = RobustScaler()
x = rb_df[['병원경력']]
rb_df['병원경력_Robust(2)'] = scaler.fit_transform(x)
rb_df.head()

      접수코드   이름 성별  필기점수  학부성적  병원경력 합격여부  병원경력_Robust(1)  병원경력_Robust(2)
0  NRS0001  장은우  남   380 3.610     3  불합격           1.000           1.000
1  NRS0002  최지호  남   660 3.670     3   합격           1.000           1.000
2  NRS0003  김하준  남   800 4.000     1   합격          -1.000          -1.000
3  NRS0004  임아윤  여   640 3.190     4   합격           2.000           2.000
4  NRS0005  강하준  남   520 2.930     4  불합격           2.000           2.000

## #01. 연습문제 - 직원 성과 분석을 위한 데이터 스케일링 

문제에 관한 텍스트만 뽑아줘오전 1:25Claude 응답: 한 회사의 인사팀에서는 직원들의 성과를 공정하게 평가하고 비교하기 위한 시스템을 구축하고 있습니다.한 회사의 인사팀에서는 직원들의 성과를 공정하게 평가하고 비교하기 위한 시스템을 구축하고 있습니다.

각 직원의 성과 지표(예: 월별 매출, 고객 만족도, 프로젝트 투입 시간 등)는 측정 단위와 범위가 서로 달라 직접 비교하기 어렵습니다.
따라서 이러한 지표들을 통일된 기준으로 변환하여, 모든 직원의 성과를 하나의 척도 위에서 분석할 수 있도록 데이터 전처리 작업이 필요합니다.
여러분은 데이터 분석가로서 인사팀을 도와 다양한 성과 지표들을 적절한 스케일링 기법을 사용하여 표준화하는 작업을 수행해야 합니다.

performance 데이터에 대해 다음을 각 컬럼에 적용하세요.

MonthlySales 컬럼에는 Min-Max 스케일링을 적용하여 0과 1 사이의 값으로 변환하세요.
CustomerSatisfaction 컬럼에는 MaxAbs 스케일링을 적용하여 -1과 1 사이의 값으로 변환하세요.
ProjectHours와 InnovationScore 컬럼에는 Standard 스케일링(표준화)을 적용하여 평균이 0, 표준편차가 1인 값으로 변환하세요.
모든 스케일링 과정이 끝난 후, MonthlySales (Min-Max 스케일링), CustomerSatisfaction (MaxAbs 스케일링), ProjectHours (Standard 스케일링), InnovationScore (Standard 스케일링) 컬럼의 값을 모두 더했을 때, 합산 값이 가장 높은 직원의 EmployeeID를 찾아주세요.

# [LAB 04] 13. 데이터 표준화 - 연습문제

## #01. 준비작업

### 1. 라이브러리 참조

In [ ]:
from jussam import load_data

# 스케일링을 위해 사용
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, StandardScaler, RobustScaler

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

### 2. 데이터 가져오기

In [ ]:
performance_df = load_data("performance");
performance_df

📚 직원 성과 지표 데이터

            MonthlySales  CustomerSatisfaction  ProjectHours  InnovationScore
EmployeeID
E001                 120                    75           160                8
E002                 250                    90           180                9
E003                  80                    60           150                6
E004                 180                    82           170                8
E005                 300                    95           190               10
E006                  90                    65           155                7
E007                 200                    88           175                9
E008                 110                    70           165                7
E009                 220                    85           185                9
E010                  70                    55           145                6
E011                 130                    78           162                8
E012                 280                    92           188               10
E013                  60                    50           140                5
E014                 190                    80           172                8
E015                 260                    91           183                9
E016                 100                    68           158                7
E017                 170                    83           168                8
E018                 320                    98           195               10
E019                  50                    45           135                5
E020                 240                    89           178                9

## 요구사항 해결

### 요구사항에 따른 스케일링 수행

In [ ]:
df = performance_df.copy()

# MinMaxScaler
df['MonthlySales_scaled'] = MinMaxScaler().fit_transform(df[['MonthlySales']])

# MaxAbsScaler
df['CustomerSatisfaction_scaled'] = MaxAbsScaler().fit_transform(df[['CustomerSatisfaction']])

# StandardScaler
scaled_standard_features = StandardScaler().fit_transform(df[['ProjectHours', 'InnovationScore']])
df['ProjectHours_scaled'] = scaled_standard_features[:, 0]
df['InnovationScore_scaled'] = scaled_standard_features[:, 1]

df.head()

,MonthlySales,CustomerSatisfaction,ProjectHours,InnovationScore,MonthlySales_scaled,CustomerSatisfaction_scaled,ProjectHours_scaled,InnovationScore_scaled
EmployeeID,,,,,,,,
E001,120,75,160,8,0.259,0.765,-0.463,0.066
E002,250,90,180,9,0.741,0.918,0.739,0.727
E003,80,60,150,6,0.111,0.612,-1.063,-1.256
E004,180,82,170,8,0.481,0.837,0.138,0.066
E005,300,95,190,10,0.926,0.969,1.340,1.388

### 스케일링 값의 합계 구하기

In [ ]:
df['TotalScaledScore'] = df['MonthlySales_scaled'] + df['CustomerSatisfaction_scaled'] + df['ProjectHours_scaled'] + df['InnovationScore_scaled']
df.head()

,MonthlySales,CustomerSatisfaction,ProjectHours,InnovationScore,MonthlySales_scaled,CustomerSatisfaction_scaled,ProjectHours_scaled,InnovationScore_scaled,TotalScaledScore
EmployeeID,,,,,,,,,
E001,120,75,160,8,0.259,0.765,-0.463,0.066,0.628
E002,250,90,180,9,0.741,0.918,0.739,0.727,3.125
E003,80,60,150,6,0.111,0.612,-1.063,-1.256,-1.595
E004,180,82,170,8,0.481,0.837,0.138,0.066,1.522
E005,300,95,190,10,0.926,0.969,1.340,1.388,4.623

### 합계 결과가 가장 큰 직원 찾기

In [ ]:
max_data = df.sort_values('TotalScaledScore', ascending=False).head(1)
max_data

,MonthlySales,CustomerSatisfaction,ProjectHours,InnovationScore,MonthlySales_scaled,CustomerSatisfaction_scaled,ProjectHours_scaled,InnovationScore_scaled,TotalScaledScore
EmployeeID,,,,,,,,,
E018,320,98,195,10,1.000,1.000,1.640,1.388,5.028

### 결과

In [ ]:
print(f"스케일링된 값의 합계가 가장 높은 직원의 EmployeeID는 {max_data.index[0]}입니다.")

스케일링된 값의 합계가 가장 높은 직원의 EmployeeID는 E018입니다.