# [LAB 04] 1. 데이터 구조 점검 (1)

## #01. 준비작업

### 1. 라이브러리 참조

In [1]:
from jussam import load_data        # 데이터 로딩 함수
from pandas import CategoricalDtype # 명목형 타입 클래스

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

### 2. 데이터 가져오기

In [2]:
origin = load_data("grade")
origin

📚 어느 학급의 과목별 점수를 조사한 가상의 데이터

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

## #02. 데이터 확인하기

### 1. 데이터의 크기

In [3]:
rows, cols = origin.shape
print("%d행,%d열의 %d차원 데이터" % (rows, cols, origin.ndim))

9행,6열의 2차원 데이터

### 2. 각 변수의 데이터 타입 확인

In [4]:
origin.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: int64(5), str(1)
memory usage: 612.0 bytes

## #03. 데이터 타입 변경

### 1. 작업을 위한 복사본 생성

In [5]:
컬럼타입변경df = origin.copy()
컬럼타입변경df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: int64(5), str(1)
memory usage: 612.0 bytes

### 2. 컬럼 단위 변경

- **컬럼 단위의 데이터 타입 변경**
  - 하나의 컬럼은 시리즈 개체이므로 `astype()` 함수로 타입 변경 가능.
  - 변경된 결과는 다시 원래의 컬럼에 저장해야 DataFrame에 반영된다.

In [6]:
컬럼타입변경df['국어'] = 컬럼타입변경df['국어'].astype('float')
컬럼타입변경df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      float64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: float64(1), int64(4), str(1)
memory usage: 612.0 bytes

### 3. 타입 일괄 변경 후 새로운 DataFrame 리턴 받기

- **타입 변환 적용**
  - 타입 변환을 수행할 변수만 `이름:타입` 형식의 딕셔너리로 구성한다.
  - 결과가 적용된 복사본이 리턴된다.

In [7]:
타입변환df = origin.astype({'국어': 'float', '영어': 'float',
                           '수학': 'str', '과학': 'bool'})
타입변환df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      float64
 3   영어      9 non-null      float64
 4   수학      9 non-null      str
 5   과학      9 non-null      bool
dtypes: bool(1), float64(2), int64(1), str(2)
memory usage: 567.0 bytes

### 4. 타입 변환 전 원본 확인

- DataFrame 객체에 대한 `astype()`함수는 결과가 적용된 복사본을 리턴한다.     
  (원본은 변하지 않음)

In [8]:
origin.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: int64(5), str(1)
memory usage: 612.0 bytes

### 5. 범주형 데이터를 명목척도로 변환 (1)

- 컬럼 단위 변환

In [9]:
컬럼단위_명목df = origin.copy()
컬럼단위_명목df['학년'] = 컬럼단위_명목df['학년'].astype('category')
컬럼단위_명목df['성별'] = 컬럼단위_명목df['성별'].astype('category')
컬럼단위_명목df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      category
 1   성별      9 non-null      category
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: category(2), int64(4)
memory usage: 493.0 bytes

### 6. 범주형 데이터를 명목척도로 변환 (2)

- DataFrame 전체에 적용 후 복사본 리턴 받기

In [10]:
범주형df = origin.astype({'학년': 'category', '성별': 'category'})
범주형df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      category
 1   성별      9 non-null      category
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: category(2), int64(4)
memory usage: 493.0 bytes

### 7. 범주형 데이터를 서열척도로 변환 (1)

- **컬럼 단위로 적용하여 원본에 직접 적용하기**
  - `CategoricalDtype` 클래스의 객체를 생성하여 범주의 특성을 설정한다.

In [11]:
컬럼단위_서열척도df = origin.copy()
컬럼단위_서열척도df['학년'] = 컬럼단위_서열척도df['학년'].astype(
        CategoricalDtype(categories=[1, 2, 3, 4], ordered=True))
컬럼단위_서열척도df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      category
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: category(1), int64(4), str(1)
memory usage: 753.0 bytes

### 8. 범주형 데이터를 서열척도로 변환 (2)

- DataFrame 전체에 적용 후 복사본 반환 받기

In [12]:
서열척도df = origin.astype({
    "학년": CategoricalDtype(categories=[1,2,3,4], ordered=True)})
서열척도df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      category
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: category(1), int64(4), str(1)
memory usage: 753.0 bytes

## #04. 행, 열의 이름 변경

### 1. `rename()` 메서드의 사용

-  `기존이름: 새이름` 형식의 딕셔너리로 지정
-  `columns`와 `index`중 변경을 원하는 파라미터 하나만 설정 가능.
-  원본은 변화 없음. 결과가 적용된 복사본이 생성된다.
-  이름이 변경되지 않은 항목이 결과에서 제외되지는 않는다.
-  원본에 즉시 반영해야 할 경우 `inplace=True` 파라미터를 적용

In [13]:
이름변경df = origin.rename(
    columns={'국어': 'kor', '영어': 'eng', '수학': 'math', '과학': 'sci'},
    index={'석영': 'suk', '호영': 'ho', '민철': 'min', '수현': 'su'}
)
이름변경df

     학년  성별  kor  eng  math  sci
이름
철수    1  남자   98   77    88   64
영희    2  여자   88  120    62   72
min   1  남자   92   70    83   79
su    3  여자   63   60    31   71
ho    4  남자   75   50    90   88
영호    4  남자   80   88    91   72
용식    2  남자   82   88    79   90
나영    1  여자   90   92    81   95
suk   1  남자   91   90    89   80