# [LAB 04] 데이터 다루기 - 6. 데이터 정렬 필터링

## #01. 준비작업

### 1. 라이브러리 참조

In [23]:
from jussam import load_data

### 2. 데이터 불러오기

In [24]:
origin = load_data('grade')
origin

📚 어느 학급의 과목별 점수를 조사한 가상의 데이터

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

## #02. 데이터 정렬

### 1. 변수에 의한 정렬

In [25]:
# 단일정렬df = origin.sort_values('학년', ascending=False)
# 단일정렬df

### 2. 여러 변수 정렬

In [26]:
복수정렬df = origin.sort_values(['학년', '국어'], ascending = [False, False])
복수정렬df

    학년  성별  국어   영어  수학  과학
이름
영호   4  남자  80   88  91  72
호영   4  남자  75   50  90  88
수현   3  여자  63   60  31  71
영희   2  여자  88  120  62  72
용식   2  남자  82   88  79  90
철수   1  남자  98   77  88  64
민철   1  남자  92   70  83  79
석영   1  남자  91   90  89  80
나영   1  여자  90   92  81  95

### 3. 인덱스 기준으로 하는 정렬

In [27]:
인덱스정렬df = origin.sort_index(ascending=False)
인덱스정렬df

    학년  성별  국어   영어  수학  과학
이름
호영   4  남자  75   50  90  88
철수   1  남자  98   77  88  64
용식   2  남자  82   88  79  90
영희   2  여자  88  120  62  72
영호   4  남자  80   88  91  72
수현   3  여자  63   60  31  71
석영   1  남자  91   90  89  80
민철   1  남자  92   70  83  79
나영   1  여자  90   92  81  95

## #03. 데이터 필터링 

### 1. 숫자형 변수의 조건 검색

In [28]:
# r1 = origin[origin['국어'] > 80]
r1 = origin.query('국어 > 80' )
r1

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### 2. 문자열 변수의 조건 검색

In [29]:
# r2 = origin[origin["성별"] == '남자']
r2 = origin.query("성별 == '남자'")
r2

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
민철   1  남자  92  70  83  79
호영   4  남자  75  50  90  88
영호   4  남자  80  88  91  72
용식   2  남자  82  88  79  90
석영   1  남자  91  90  89  80

### 3. AND 연산을 사용하는 조건 검색

In [30]:
# r3 = origin[(origin['국어'] > 80 ) & (origin['수학'] > 80) ]
r3 = origin.query('국어 > 80 and 수학 > 80')
r3

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
민철   1  남자  92  70  83  79
나영   1  여자  90  92  81  95
석영   1  남자  91  90  89  80

### 4. OR 연산을 사용하는 조건 검색

In [31]:
# r4 = origin[(origin['국어'] <= 80) | (origin['수학'] <= 80)]  
r4 = origin.query('국어 <= 80 or 수학 <= 80')
r4

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90

### 5. 비교식에 변수를 사용하는 조건검색 
- @변수이름 형태로 조건식에 포함한다.

In [32]:
point = int(input('점수를 입력하세요: '))
print("국어 점수가 %d점 보다 높은 학생 " % point)

r5 = origin.query('국어 > @point')
r5

국어 점수가 82점 보다 높은 학생

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### 6. 열 단위 필터링

In [33]:
fl = origin.filter(['국어', '영어'])
fl

    국어   영어
이름
철수  98   77
영희  88  120
민철  92   70
수현  63   60
호영  75   50
영호  80   88
용식  82   88
나영  90   92
석영  91   90

## #1. 연습문제 - 마케팅팀 신입사원의 첫번째 미션

In [34]:
vip = load_data('vip_customer')
vip

📚 VIP 고객 목록 데이터

    field             description
--  ----------------  ----------------
 0  CustomerID        고객번호
 1  Name              고객명
 2  Age               나이
 3  City              거주지역
 4  JoinDate          가입일
 5  TotalSpending     총 지출액
 6  LastPurchaseDate  마지막 구매 날짜

           Name  Age City   JoinDate  TotalSpending LastPurchaseDate
CustomerID
1001        김철수   35   서울 2022-01-15         150000       2023-11-01
1002        이영희   28   부산 2021-03-22          80000       2023-10-15
1003        박민준   42   서울 2022-07-10         250000       2023-11-10
1004        최지우   25   인천 2023-02-20          50000       2023-09-25
1005        정다솜   31   서울 2021-11-05         320000       2023-11-12
1006        윤현우   38   부산 2022-05-30         120000       2023-11-05
1007        강예진   29   서울 2023-01-15          85000       2023-10-22
1008        오승민   45   광주 2021-08-12         180000       2023-11-08
1009        한지민   27   서울 2022-10-01         450000       2023-11-15
1010        송서연   33   대전 2023-04-01          65000       2023-09-30
1011        임도윤   39   서울 2021-06-18         210000       2023-11-02
1012        장유나   26   부산 2023-03-10          40000       2023-08-15
1013        황재민   41   서울 2022-09-05         190000       2023-11-07
1014        신은경   30   대구 2021-12-20          95000       2023-10-18
1015        고은별   36   서울 2023-05-25         130000       2023-11-11

In [35]:
df1 = vip.copy()
df1

           Name  Age City   JoinDate  TotalSpending LastPurchaseDate
CustomerID
1001        김철수   35   서울 2022-01-15         150000       2023-11-01
1002        이영희   28   부산 2021-03-22          80000       2023-10-15
1003        박민준   42   서울 2022-07-10         250000       2023-11-10
1004        최지우   25   인천 2023-02-20          50000       2023-09-25
1005        정다솜   31   서울 2021-11-05         320000       2023-11-12
1006        윤현우   38   부산 2022-05-30         120000       2023-11-05
1007        강예진   29   서울 2023-01-15          85000       2023-10-22
1008        오승민   45   광주 2021-08-12         180000       2023-11-08
1009        한지민   27   서울 2022-10-01         450000       2023-11-15
1010        송서연   33   대전 2023-04-01          65000       2023-09-30
1011        임도윤   39   서울 2021-06-18         210000       2023-11-02
1012        장유나   26   부산 2023-03-10          40000       2023-08-15
1013        황재민   41   서울 2022-09-05         190000       2023-11-07
1014        신은경   30   대구 2021-12-20          95000       2023-10-18
1015        고은별   36   서울 2023-05-25         130000       2023-11-11

In [36]:
df2 = df1[(df1['TotalSpending']> 100000)]
df2

           Name  Age City   JoinDate  TotalSpending LastPurchaseDate
CustomerID
1001        김철수   35   서울 2022-01-15         150000       2023-11-01
1003        박민준   42   서울 2022-07-10         250000       2023-11-10
1005        정다솜   31   서울 2021-11-05         320000       2023-11-12
1006        윤현우   38   부산 2022-05-30         120000       2023-11-05
1008        오승민   45   광주 2021-08-12         180000       2023-11-08
1009        한지민   27   서울 2022-10-01         450000       2023-11-15
1011        임도윤   39   서울 2021-06-18         210000       2023-11-02
1013        황재민   41   서울 2022-09-05         190000       2023-11-07
1015        고은별   36   서울 2023-05-25         130000       2023-11-11

In [37]:
df3 = df2.copy()
df3

           Name  Age City   JoinDate  TotalSpending LastPurchaseDate
CustomerID
1001        김철수   35   서울 2022-01-15         150000       2023-11-01
1003        박민준   42   서울 2022-07-10         250000       2023-11-10
1005        정다솜   31   서울 2021-11-05         320000       2023-11-12
1006        윤현우   38   부산 2022-05-30         120000       2023-11-05
1008        오승민   45   광주 2021-08-12         180000       2023-11-08
1009        한지민   27   서울 2022-10-01         450000       2023-11-15
1011        임도윤   39   서울 2021-06-18         210000       2023-11-02
1013        황재민   41   서울 2022-09-05         190000       2023-11-07
1015        고은별   36   서울 2023-05-25         130000       2023-11-11

In [38]:
df3 = vip[vip['City'] =='서울']
df3

           Name  Age City   JoinDate  TotalSpending LastPurchaseDate
CustomerID
1001        김철수   35   서울 2022-01-15         150000       2023-11-01
1003        박민준   42   서울 2022-07-10         250000       2023-11-10
1005        정다솜   31   서울 2021-11-05         320000       2023-11-12
1007        강예진   29   서울 2023-01-15          85000       2023-10-22
1009        한지민   27   서울 2022-10-01         450000       2023-11-15
1011        임도윤   39   서울 2021-06-18         210000       2023-11-02
1013        황재민   41   서울 2022-09-05         190000       2023-11-07
1015        고은별   36   서울 2023-05-25         130000       2023-11-11

In [39]:
vip정렬 = vip.sort_values('TotalSpending', ascending=False)
vip정렬

           Name  Age City   JoinDate  TotalSpending LastPurchaseDate
CustomerID
1009        한지민   27   서울 2022-10-01         450000       2023-11-15
1005        정다솜   31   서울 2021-11-05         320000       2023-11-12
1003        박민준   42   서울 2022-07-10         250000       2023-11-10
1011        임도윤   39   서울 2021-06-18         210000       2023-11-02
1013        황재민   41   서울 2022-09-05         190000       2023-11-07
1008        오승민   45   광주 2021-08-12         180000       2023-11-08
1001        김철수   35   서울 2022-01-15         150000       2023-11-01
1015        고은별   36   서울 2023-05-25         130000       2023-11-11
1006        윤현우   38   부산 2022-05-30         120000       2023-11-05
1014        신은경   30   대구 2021-12-20          95000       2023-10-18
1007        강예진   29   서울 2023-01-15          85000       2023-10-22
1002        이영희   28   부산 2021-03-22          80000       2023-10-15
1010        송서연   33   대전 2023-04-01          65000       2023-09-30
1004        최지우   25   인천 2023-02-20          50000       2023-09-25
1012        장유나   26   부산 2023-03-10          40000       2023-08-15

In [40]:
vip정렬최종 = vip정렬.head(5)

final_report = vip정렬최종.filter(['Name', 'City', 'TotalSpending'])

final_report

           Name City  TotalSpending
CustomerID
1009        한지민   서울         450000
1005        정다솜   서울         320000
1003        박민준   서울         250000
1011        임도윤   서울         210000
1013        황재민   서울         190000

In [ ]:
# 두 조건을 동시에 적용하는 법.
# python# ❌ 연주 방식 (조건이 합쳐지지 않음)
# df2 = df1[df1['TotalSpending'] > 100000]
# df3 = vip[vip['City'] == '서울']

# # ✅ 방법 1: & 연산자
# df2 = df[(df['TotalSpending'] >= 100000) & (df['City'] == '서울s')]

# # ✅ 방법 2: query() (강사 방식)
# df2 = df.query("TotalSpending >= 100000 and City == '서울'")
# 두 조건을 & 또는 query()로 동시에 걸어야 교집합이 나와.