# [LAB 04] 데이터 다루기 - 7. 그룹집계

## #01. 준비작업

### 1. 라이브러리 참조

In [42]:
from jussam import load_data

### 2. 데이터 불러오기

In [43]:
origin = load_data("traffic_acc")
origin

📚 2005년 1월 부터 2018년 12월 까지 월별 교통사고의 발생건수,부상자수,사망자수 데이터(인덱스/메타데이터 없음, 출처: 공공데이터포털)

       년도   월   발생건수  사망자수   부상자수
0    2005   1  15494   504  25413
1    2005   2  13244   431  21635
2    2005   3  16580   477  25550
3    2005   4  17817   507  28131
4    2005   5  19085   571  29808
..    ...  ..    ...   ...    ...
163  2018   8  18335   357  27749
164  2018   9  18371   348  27751
165  2018  10  19738   373  28836
166  2018  11  19029   298  28000
167  2018  12  18010   323  26463

[168 rows x 5 columns]

## #02. 지정된 컬럼을 기준으로 그룹화

### 1. 전체 컬럼에 대한 집계

In [44]:
origin.groupby('년도').sum()

       월    발생건수  사망자수    부상자수
년도
2005  78  214171  6376  342233
2006  78  213745  6327  340229
2007  78  211662  6166  335906
2008  78  215822  5870  338962
2009  78  231990  5838  361875
2010  78  226878  5505  352458
2011  78  221711  5229  341391
2012  78  223656  5392  344565
2013  78  215354  5092  328711
2014  78  223552  4762  337497
2015  78  232035  4621  350400
2016  78  220917  4292  331720
2017  78  216335  4185  322829
2018  78  217148  3781  323037

### 2. 불필요한 컬럼을 제외하는 경우(1)

In [45]:
df = origin.drop(columns = '월')
df

       년도   발생건수  사망자수   부상자수
0    2005  15494   504  25413
1    2005  13244   431  21635
2    2005  16580   477  25550
3    2005  17817   507  28131
4    2005  19085   571  29808
..    ...    ...   ...    ...
163  2018  18335   357  27749
164  2018  18371   348  27751
165  2018  19738   373  28836
166  2018  19029   298  28000
167  2018  18010   323  26463

[168 rows x 4 columns]

### 2. 불필요한 컬럼을 제외하는 경우 (2)

In [46]:
df.groupby('년도').sum()

        발생건수  사망자수    부상자수
년도
2005  214171  6376  342233
2006  213745  6327  340229
2007  211662  6166  335906
2008  215822  5870  338962
2009  231990  5838  361875
2010  226878  5505  352458
2011  221711  5229  341391
2012  223656  5392  344565
2013  215354  5092  328711
2014  223552  4762  337497
2015  232035  4621  350400
2016  220917  4292  331720
2017  216335  4185  322829
2018  217148  3781  323037

## #03. 필요한 컬럼만 추출하여 집계하는 경우

### 1. 년도와 교통사고 사망자수만 추출

In [47]:
df = df.filter(['년도', '사망자수'])
df

       년도  사망자수
0    2005   504
1    2005   431
2    2005   477
3    2005   507
4    2005   571
..    ...   ...
163  2018   357
164  2018   348
165  2018   373
166  2018   298
167  2018   323

[168 rows x 2 columns]

### 2. 추출된 새로운 데이터 프레임을 활용한 집계

In [48]:
df.groupby('년도').sum()

      사망자수
년도
2005  6376
2006  6327
2007  6166
2008  5870
2009  5838
2010  5505
2011  5229
2012  5392
2013  5092
2014  4762
2015  4621
2016  4292
2017  4185
2018  3781

## #04. 두 개 이상의 변수에 대한 그룹화

### 1. 그룹화 할 기준이 두 개 이상인 경우

In [49]:
origin.groupby(['년도', '월']).mean()

             발생건수    사망자수      부상자수
년도   월
2005 1  15494.000 504.000 25413.000
     2  13244.000 431.000 21635.000
     3  16580.000 477.000 25550.000
     4  17817.000 507.000 28131.000
     5  19085.000 571.000 29808.000
...           ...     ...       ...
2018 8  18335.000 357.000 27749.000
     9  18371.000 348.000 27751.000
     10 19738.000 373.000 28836.000
     11 19029.000 298.000 28000.000
     12 18010.000 323.000 26463.000

[168 rows x 3 columns]

### 2. 두 개 이상의 집계함수를 사용할 경우

In [50]:
origin.filter(['년도', '발생건수']).groupby('년도').agg(
    ['sum', 'max', 'min', 'mean']
)

        발생건수
         sum    max    min      mean
년도
2005  214171  19757  13244 17847.583
2006  213745  19877  14270 17812.083
2007  211662  19264  14696 17638.500
2008  215822  19926  14176 17985.167
2009  231990  21440  15502 19332.500
2010  226878  21575  15803 18906.500
2011  221711  20952  14208 18475.917
2012  223656  19750  16656 18638.000
2013  215354  19797  14187 17946.167
2014  223552  20760  14061 18629.333
2015  232035  21587  14939 19336.250
2016  220917  19918  15664 18409.750
2017  216335  19891  14832 18027.917
2018  217148  19738  16208 18095.667

### 3. 컬럼별로 집계함수를 다르게 지정하는 경우

In [51]:
origin.drop("월", axis=1).groupby('년도').agg(
    {"발생건수":['mean', 'sum'], '사망자수':'max', '부상자수':'min'}
)

          발생건수         사망자수   부상자수
          mean     sum  max    min
년도
2005 17847.583  214171  639  21635
2006 17812.083  213745  701  22903
2007 17638.500  211662  582  23717
2008 17985.167  215822  574  23282
2009 19332.500  231990  592  24429
2010 18906.500  226878  619  24968
2011 18475.917  221711  520  22493
2012 18638.000  223656  533  25998
2013 17946.167  215354  499  22255
2014 18629.333  223552  476  21501
2015 19336.250  232035  470  22999
2016 18409.750  220917  440  24021
2017 18027.917  216335  420  22323
2018 18095.667  217148  373  24630

## #05. 사용자 정의 함수를 사용한 집계

In [52]:
def myFunction(x):
    # x는 Series객체 - 컬럼 하나가 통째로 전달됨 
    return x.max() - x.min()

In [53]:
# 사용자 정의 함수 이름은 문자열이 아님 
origin.drop('월', axis=1).groupby('년도').agg(['max', 'min', myFunction])

       발생건수                   사망자수                   부상자수
        max    min myFunction  max  min myFunction    max    min myFunction
년도
2005  19757  13244       6513  639  431        208  31603  21635       9968
2006  19877  14270       5607  701  373        328  31270  22903       8367
2007  19264  14696       4568  582  446        136  30532  23717       6815
2008  19926  14176       5750  574  423        151  30935  23282       7653
2009  21440  15502       5938  592  405        187  33255  24429       8826
2010  21575  15803       5772  619  395        224  33282  24968       8314
2011  20952  14208       6744  520  338        182  32133  22493       9640
2012  19750  16656       3094  533  393        140  30163  25998       4165
2013  19797  14187       5610  499  335        164  29676  22255       7421
2014  20760  14061       6699  476  325        151  31199  21501       9698
2015  21587  14939       6648  470  296        174  32436  22999       9437
2016  19918  15664       4254  440  292        148  29635  24021       5614
2017  19891  14832       5059  420  280        140  29371  22323       7048
2018  19738  16208       3530  373  266        107  28836  24630       4206

### 2. 람다식 적용

In [54]:
origin.drop('월', axis=1).groupby('년도').agg(
    ['max', 'min', lambda x : x.max() - x.min()])

       발생건수                   사망자수                   부상자수
        max    min <lambda_0>  max  min <lambda_0>    max    min <lambda_0>
년도
2005  19757  13244       6513  639  431        208  31603  21635       9968
2006  19877  14270       5607  701  373        328  31270  22903       8367
2007  19264  14696       4568  582  446        136  30532  23717       6815
2008  19926  14176       5750  574  423        151  30935  23282       7653
2009  21440  15502       5938  592  405        187  33255  24429       8826
2010  21575  15803       5772  619  395        224  33282  24968       8314
2011  20952  14208       6744  520  338        182  32133  22493       9640
2012  19750  16656       3094  533  393        140  30163  25998       4165
2013  19797  14187       5610  499  335        164  29676  22255       7421
2014  20760  14061       6699  476  325        151  31199  21501       9698
2015  21587  14939       6648  470  296        174  32436  22999       9437
2016  19918  15664       4254  440  292        148  29635  24021       5614
2017  19891  14832       5059  420  280        140  29371  22323       7048
2018  19738  16208       3530  373  266        107  28836  24630       4206

## #06. 인덱스 지정 해제

### 1. groupby() 메서드에서 사용한 필드는 기본적으로 결과집합의 인덱스로 지정됨

In [55]:
origin.drop('월', axis=1).groupby('년도', as_index=False).sum()

      년도    발생건수  사망자수    부상자수
0   2005  214171  6376  342233
1   2006  213745  6327  340229
2   2007  211662  6166  335906
3   2008  215822  5870  338962
4   2009  231990  5838  361875
5   2010  226878  5505  352458
6   2011  221711  5229  341391
7   2012  223656  5392  344565
8   2013  215354  5092  328711
9   2014  223552  4762  337497
10  2015  232035  4621  350400
11  2016  220917  4292  331720
12  2017  216335  4185  322829
13  2018  217148  3781  323037

## #1. 연습문제 - 온라인 쇼핑몰의 다음 분기 프로모션 전략 수립

### 1. 결측치 확인 / price 컬럼에 결측치는 전체 상품의 평균 price로 대체

In [56]:
df = load_data('shop_order_list')
df

📚 온라인 쇼핑몰의 최근 고객 주문 데이터

    field      description
--  ---------  ----------------
 0  OrderID    주문번호(인덱스)
 1  UserID     고객번호
 2  Product    상품명
 3  Price      단가
 4  Category   카테고리
 5  Region     지역
 6  OrderDate  주문일

    OrderID   UserID   Product    Price     Category   Region  OrderDate
0      1001  user001    Laptop 1200.000  Electronics    Seoul 2023-01-15
1      1002  user002     Mouse   25.000  Electronics    Busan 2023-01-16
2      1003  user003  Keyboard   70.000  Electronics    Seoul 2023-01-17
3      1004  user001      Book   15.000        Books  Incheon 2023-01-18
4      1005  user004   T-shirt   30.000      Apparel  Gwangju 2023-01-19
5      1006  user002      Book   20.000        Books    Seoul 2023-01-20
6      1007  user005     Jeans   80.000      Apparel    Busan 2023-02-21
7      1008  user001   Monitor  300.000  Electronics    Seoul 2023-02-22
8      1009  user006      Book   18.000        Books    Daegu 2023-02-23
9      1010  user007    Jacket  150.000      Apparel    Seoul 2023-02-24
10     1011  user003    Webcam      NaN  Electronics  Incheon 2023-03-25
11     1012  user008    Coffee    5.000         Food    Busan 2023-03-26
12     1013  user009     Snack    3.000         Food  Gwangju 2023-03-27
13     1014  user002    Laptop 1300.000  Electronics    Seoul 2023-03-28
14     1015  user010     Shoes  120.000      Apparel    Daegu 2023-03-29
15     1016  user005      Book   22.000        Books    Seoul 2023-04-10
16     1017  user001      Desk  250.000    Furniture    Busan 2023-04-11
17     1018  user004     Chair      NaN    Furniture    Seoul 2023-04-12
18     1019  user007      Book   12.000        Books  Incheon 2023-04-13
19     1020  user003       Hat   40.000      Apparel    Seoul 2023-04-14

In [57]:
df.isnull().sum()

OrderID      0
UserID       0
Product      0
Price        2
Category     0
Region       0
OrderDate    0
dtype: int64

In [58]:
df2 = df.copy()
price_mean = df2['Price'].mean()
df2['Price'] = df2['Price'].fillna(price_mean)
print(df2.isnull().sum())

OrderID      0
UserID       0
Product      0
Price        0
Category     0
Region       0
OrderDate    0
dtype: int64

In [59]:
top_categories = df2['Category'].value_counts().head(3)
print("가장 많은 주문이 발생한 카테고리 TOP 3: ")
top_categories

가장 많은 주문이 발생한 카테고리 TOP 3:

Category
Electronics    6
Books          5
Apparel        5
Name: count, dtype: int64

In [64]:
region_avg_price = df2.filter(['Region', 'Price']).groupby('Region').mean().sort_values('Price', ascending=False)
region_avg_price

          Price
Region
Seoul   367.259
Busan    90.000
Incheon  76.778
Daegu    69.000
Gwangju  16.500