# [LAB 04] 데이터 다루기 - 9. 파생변수

## #01. 준비 작업

### 1. 라이브러리 참조

In [3]:
from jussam import load_data
from pandas import cut 
import numpy as np

### 2. 데이터 가져오기

In [4]:
origin = load_data("grade")
origin

📚 어느 학급의 과목별 점수를 조사한 가상의 데이터

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

## #02. 파생변수 추가하기

### 1. 컬럼 연산을 통한 새로운 컬럼 추가

In [5]:
df1 = origin.copy()
df1['직접합계'] = df1['국어'] + df1['영어'] + df1['수학'] + df1['과학']
df1

    학년  성별  국어   영어  수학  과학  직접합계
이름
철수   1  남자  98   77  88  64   327
영희   2  여자  88  120  62  72   342
민철   1  남자  92   70  83  79   324
수현   3  여자  63   60  31  71   225
호영   4  남자  75   50  90  88   303
영호   4  남자  80   88  91  72   331
용식   2  남자  82   88  79  90   339
나영   1  여자  90   92  81  95   358
석영   1  남자  91   90  89  80   350

### 2. 기술통계 관련 함수를 사용한 파생변수 
- 1) 컬럼이름에 대한 슬라이싱 접근

In [6]:
df2 = origin.copy()
df2['합계'] = df2[df2.columns[2:6]].sum(axis=1)
df2

    학년  성별  국어   영어  수학  과학   합계
이름
철수   1  남자  98   77  88  64  327
영희   2  여자  88  120  62  72  342
민철   1  남자  92   70  83  79  324
수현   3  여자  63   60  31  71  225
호영   4  남자  75   50  90  88  303
영호   4  남자  80   88  91  72  331
용식   2  남자  82   88  79  90  339
나영   1  여자  90   92  81  95  358
석영   1  남자  91   90  89  80  350

### 2. 기술통계 관련 함수를 사용한 파생변수 
- 2) 인덱스 기반 위치로 슬라이싱하여 합계 변수 추가

In [7]:
df3 = origin.copy()
df3['합계'] = df3.iloc[:, 2:].sum(axis =1)
df3

    학년  성별  국어   영어  수학  과학   합계
이름
철수   1  남자  98   77  88  64  327
영희   2  여자  88  120  62  72  342
민철   1  남자  92   70  83  79  324
수현   3  여자  63   60  31  71  225
호영   4  남자  75   50  90  88  303
영호   4  남자  80   88  91  72  331
용식   2  남자  82   88  79  90  339
나영   1  여자  90   92  81  95  358
석영   1  남자  91   90  89  80  350

### 2. 기술통계 관련 함수를 사용한 파생변수 
- 2) 나머지 기술통계값 추가

In [8]:
df3['평균'] = df3.iloc[:, 2:6].mean(axis =1)
df3['최대값'] = df3.iloc[:, 2:6].max(axis =1)
df3['최소값'] = df3.iloc[:, 2:6].min(axis =1)
df3['표준편차'] = df3.iloc[:, 2:6].std(axis =1)
df3['분산'] = df3.iloc[:, 2:6].var(axis =1)
df3

    학년  성별  국어   영어  수학  과학   합계     평균  최대값  최소값   표준편차      분산
이름
철수   1  남자  98   77  88  64  327 81.750   98   64 14.614 213.583
영희   2  여자  88  120  62  72  342 85.500  120   62 25.371 643.667
민철   1  남자  92   70  83  79  324 81.000   92   70  9.129  83.333
수현   3  여자  63   60  31  71  225 56.250   71   31 17.462 304.917
호영   4  남자  75   50  90  88  303 75.750   90   50 18.410 338.917
영호   4  남자  80   88  91  72  331 82.750   91   72  8.539  72.917
용식   2  남자  82   88  79  90  339 84.750   90   79  5.123  26.250
나영   1  여자  90   92  81  95  358 89.500   95   81  6.028  36.333
석영   1  남자  91   90  89  80  350 87.500   91   80  5.066  25.667

## #03. 조건별 파생 변수

### 1. if ~ else 
- 1) 실습을 위해 합계와 평균에 대한 파생 변수 추가

In [9]:
df4 = origin.copy()
df4['합계'] = df4.iloc[:, 2:6].sum(axis =1)
df4['평균'] = df4.iloc[:, 2:6].mean(axis =1)
df4

    학년  성별  국어   영어  수학  과학   합계     평균
이름
철수   1  남자  98   77  88  64  327 81.750
영희   2  여자  88  120  62  72  342 85.500
민철   1  남자  92   70  83  79  324 81.000
수현   3  여자  63   60  31  71  225 56.250
호영   4  남자  75   50  90  88  303 75.750
영호   4  남자  80   88  91  72  331 82.750
용식   2  남자  82   88  79  90  339 84.750
나영   1  여자  90   92  81  95  358 89.500
석영   1  남자  91   90  89  80  350 87.500

### 1. if ~ else 
- 2) Numpy의 where 함수를 사용한 조건부 파생 변수

In [10]:
df4['결과1'] = np.where(df4['평균'] >= 80, '합격', '불합격')
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1
이름
철수   1  남자  98   77  88  64  327 81.750   합격
영희   2  여자  88  120  62  72  342 85.500   합격
민철   1  남자  92   70  83  79  324 81.000   합격
수현   3  여자  63   60  31  71  225 56.250  불합격
호영   4  남자  75   50  90  88  303 75.750  불합격
영호   4  남자  80   88  91  72  331 82.750   합격
용식   2  남자  82   88  79  90  339 84.750   합격
나영   1  여자  90   92  81  95  358 89.500   합격
석영   1  남자  91   90  89  80  350 87.500   합격

### 1. if ~ else 
- 3) 표현식을 사용한 평균값에 따른 조건부 파생변수

In [11]:
df4['결과2'] = "불합격" 
df4.loc[df4['평균'] >= 80 , "결과2"] = '합격'
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격
영희   2  여자  88  120  62  72  342 85.500   합격   합격
민철   1  남자  92   70  83  79  324 81.000   합격   합격
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격
영호   4  남자  80   88  91  72  331 82.750   합격   합격
용식   2  남자  82   88  79  90  339 84.750   합격   합격
나영   1  여자  90   92  81  95  358 89.500   합격   합격
석영   1  남자  91   90  89  80  350 87.500   합격   합격

### 2. 경우의 수에 따른 조건값 (elif) - Numpy의 select함수 사용

In [12]:
# 학점을 부여하기 위한 점수의 구간을 설정하는 조건들을 리스트로 설정 
conditions = [(df4['평균'] >= 90), 
              (df4['평균'] >= 80), 
              (df4['평균'] >= 70)]

# 조건에 따라 부여될 학점 
value = ['A', 'B', 'C'] 

#                           조건       값     else
df4['학점1'] = np.select(conditions, value, default='F') 
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2 학점1
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격   B
영희   2  여자  88  120  62  72  342 85.500   합격   합격   B
민철   1  남자  92   70  83  79  324 81.000   합격   합격   B
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격   F
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격   C
영호   4  남자  80   88  91  72  331 82.750   합격   합격   B
용식   2  남자  82   88  79  90  339 84.750   합격   합격   B
나영   1  여자  90   92  81  95  358 89.500   합격   합격   B
석영   1  남자  91   90  89  80  350 87.500   합격   합격   B

### 3. 사용자 정의 함수 사용 
- 1) 함수 정의하기

In [13]:
def getScore(x) : 
    if x >= 90 :
        score = 'A'
    elif x >= 80:
        score = 'B'
    elif x >= 70:
        score = 'C'
    else: 
        score = 'F'
    
    return score

### 3. 사용자 정의 함수 사용 
- 2) 함수 리턴 값으로 파생변수 추가하기

In [14]:
df4['학점2'] = df4['평균'].apply(getScore)
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2 학점1 학점2
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격   B   B
영희   2  여자  88  120  62  72  342 85.500   합격   합격   B   B
민철   1  남자  92   70  83  79  324 81.000   합격   합격   B   B
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격   F   F
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격   C   C
영호   4  남자  80   88  91  72  331 82.750   합격   합격   B   B
용식   2  남자  82   88  79  90  339 84.750   합격   합격   B   B
나영   1  여자  90   92  81  95  358 89.500   합격   합격   B   B
석영   1  남자  91   90  89  80  350 87.500   합격   합격   B   B

### 람다식의 이해

### 3. 사용자 정의 함수 사용 
- 3) 함수 정의 없이 람다식으로 익명함수 적용하기

In [15]:
df4['학점3'] = df4['평균'].apply(
    lambda x : {10:"A", 9:"B", 8:"B", 7:"C"}.get( x // 10,"F"))
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2 학점1 학점2 학점3
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격   B   B   B
영희   2  여자  88  120  62  72  342 85.500   합격   합격   B   B   B
민철   1  남자  92   70  83  79  324 81.000   합격   합격   B   B   B
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격   F   F   F
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격   C   C   C
영호   4  남자  80   88  91  72  331 82.750   합격   합격   B   B   B
용식   2  남자  82   88  79  90  339 84.750   합격   합격   B   B   B
나영   1  여자  90   92  81  95  358 89.500   합격   합격   B   B   B
석영   1  남자  91   90  89  80  350 87.500   합격   합격   B   B   B

### 4. map() 메서드 사용 
- 앞의 방법처럼 연산을 사용할 수는 없고, 값이 완전히 일치하는 경우에만 사용할 수 있음.

In [16]:
df4['성별코드'] = df4['성별'].map({"남자":"M", "여자":"F"})
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2 학점1 학점2 학점3 성별코드
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격   B   B   B    M
영희   2  여자  88  120  62  72  342 85.500   합격   합격   B   B   B    F
민철   1  남자  92   70  83  79  324 81.000   합격   합격   B   B   B    M
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격   F   F   F    F
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격   C   C   C    M
영호   4  남자  80   88  91  72  331 82.750   합격   합격   B   B   B    M
용식   2  남자  82   88  79  90  339 84.750   합격   합격   B   B   B    M
나영   1  여자  90   92  81  95  358 89.500   합격   합격   B   B   B    F
석영   1  남자  91   90  89  80  350 87.500   합격   합격   B   B   B    M

### 5. Pandas의 cut 함수 사용

In [17]:
df4["학점"] = cut(
    df4["평균"] , 
    bins = [0, 70, 80, 90, 100] , 
    labels = ["F", "C", "B", "A"]
)
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2 학점1 학점2 학점3 성별코드 학점
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격   B   B   B    M  B
영희   2  여자  88  120  62  72  342 85.500   합격   합격   B   B   B    F  B
민철   1  남자  92   70  83  79  324 81.000   합격   합격   B   B   B    M  B
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격   F   F   F    F  F
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격   C   C   C    M  C
영호   4  남자  80   88  91  72  331 82.750   합격   합격   B   B   B    M  B
용식   2  남자  82   88  79  90  339 84.750   합격   합격   B   B   B    M  B
나영   1  여자  90   92  81  95  358 89.500   합격   합격   B   B   B    F  B
석영   1  남자  91   90  89  80  350 87.500   합격   합격   B   B   B    M  B

## #01. 연습문제 - 우수 고객 찾기

In [ ]:
# 이 문제의 사고 순서
# 총 구매금액이 필요하다
#   → Total = Price × Quantity  (파생변수 먼저)
#   → UserID별로 Total 합산  (groupby + sum)
#   → 내림차순 정렬 후 상위 2명  (sort_values + head)

In [ ]:
# 네가 헷갈리는 진짜 원인
# "지금 df에 내가 필요한 컬럼이 있나?" 를 안 확인하고 코드부터 쓰는 것.
# groupby('UserID').sum() 쓰기 전에 df에 Total이 없으면 sum할 게 없잖아.
# 습관으로 만들어야 할 체크포인트:


# 지금 df 상태가 뭐야? (df.columns 머릿속으로 체크)
# 내가 원하는 결과에 필요한 컬럼이 있어? → 없으면 먼저 만들어
# 그 다음에 groupby / sort / filter


# 코드 문법 문제가 아니라 "지금 df에 뭐가 있는지 추적하는 습관" 이 없는 거야. 셀 실행할 때마다 df.head() 한 번씩 찍어보는 것만 해도 많이 잡혀.

In [18]:
from jussam import load_data

In [19]:
df = load_data('online_shop_sales') 
df

📚 우수 고객을 찾아라! - 영업 데이터 분석 챌린지

    field      description
--  ---------  ----------------
 0  OrderID    주문번호(인덱스)
 1  UserID     고객아이디
 2  Product    상품
 3  Price      가격
 4  Quantity   주문수량
 5  OrderDate  주문일

    UserID          Product  Price  Quantity  OrderDate
0     1001           Laptop   1200         1 2024-10-01
1     1002            Mouse     25         2 2024-10-01
2     1001         Keyboard     75         1 2024-10-02
3     1003          Monitor    300         1 2024-10-03
4     1002           Webcam     50         1 2024-10-04
5     1003       HDMI Cable     15         3 2024-10-05
6     1001          USB Hub     30         2 2024-10-06
7     1004           Laptop   1300         1 2024-10-07
8     1002            Mouse     25         1 2024-10-08
9     1003          Monitor    300         2 2024-10-09
10    1001     External SSD    150         1 2024-10-10
11    1004  Docking Station    250         1 2024-10-11
12    1002         Keyboard     80         1 2024-10-12
13    1003           Webcam     55         1 2024-10-13
14    1001            Mouse     28         1 2024-10-14

In [20]:
df1 = df.copy()
df1

    UserID          Product  Price  Quantity  OrderDate
0     1001           Laptop   1200         1 2024-10-01
1     1002            Mouse     25         2 2024-10-01
2     1001         Keyboard     75         1 2024-10-02
3     1003          Monitor    300         1 2024-10-03
4     1002           Webcam     50         1 2024-10-04
5     1003       HDMI Cable     15         3 2024-10-05
6     1001          USB Hub     30         2 2024-10-06
7     1004           Laptop   1300         1 2024-10-07
8     1002            Mouse     25         1 2024-10-08
9     1003          Monitor    300         2 2024-10-09
10    1001     External SSD    150         1 2024-10-10
11    1004  Docking Station    250         1 2024-10-11
12    1002         Keyboard     80         1 2024-10-12
13    1003           Webcam     55         1 2024-10-13
14    1001            Mouse     28         1 2024-10-14

In [21]:
# 총 구매금액 = 개별주문의 Price 와 Quantity 를 곱한 값들의 총합

In [22]:
df1['Total'] = df1['Price'] * df1['Quantity']
df1['Total']

0     1200
1       50
2       75
3      300
4       50
5       45
6       60
7     1300
8       25
9      600
10     150
11     250
12      80
13      55
14      28
Name: Total, dtype: int64

In [35]:
df2 = df1.filter(['UserID', 'Total'])
df2

    UserID  Total
0     1001   1200
1     1002     50
2     1001     75
3     1003    300
4     1002     50
5     1003     45
6     1001     60
7     1004   1300
8     1002     25
9     1003    600
10    1001    150
11    1004    250
12    1002     80
13    1003     55
14    1001     28

In [36]:
df2.groupby('UserID')
df2

    UserID  Total
0     1001   1200
1     1002     50
2     1001     75
3     1003    300
4     1002     50
5     1003     45
6     1001     60
7     1004   1300
8     1002     25
9     1003    600
10    1001    150
11    1004    250
12    1002     80
13    1003     55
14    1001     28

In [42]:
df3 = df2.groupby('UserID').sum()

df3

        Total
UserID
1001     1513
1002      205
1003     1000
1004     1550

In [31]:
df1 = df.set_index('UserID')
df1

                Product  Price  Quantity  OrderDate
UserID
1001             Laptop   1200         1 2024-10-01
1002              Mouse     25         2 2024-10-01
1001           Keyboard     75         1 2024-10-02
1003            Monitor    300         1 2024-10-03
1002             Webcam     50         1 2024-10-04
1003         HDMI Cable     15         3 2024-10-05
1001            USB Hub     30         2 2024-10-06
1004             Laptop   1300         1 2024-10-07
1002              Mouse     25         1 2024-10-08
1003            Monitor    300         2 2024-10-09
1001       External SSD    150         1 2024-10-10
1004    Docking Station    250         1 2024-10-11
1002           Keyboard     80         1 2024-10-12
1003             Webcam     55         1 2024-10-13
1001              Mouse     28         1 2024-10-14

In [33]:
df1 = df.copy()
df1["Total"] = df1["Price"] * df1["Quantity"]
df1

    UserID          Product  Price  Quantity  OrderDate  Total
0     1001           Laptop   1200         1 2024-10-01   1200
1     1002            Mouse     25         2 2024-10-01     50
2     1001         Keyboard     75         1 2024-10-02     75
3     1003          Monitor    300         1 2024-10-03    300
4     1002           Webcam     50         1 2024-10-04     50
5     1003       HDMI Cable     15         3 2024-10-05     45
6     1001          USB Hub     30         2 2024-10-06     60
7     1004           Laptop   1300         1 2024-10-07   1300
8     1002            Mouse     25         1 2024-10-08     25
9     1003          Monitor    300         2 2024-10-09    600
10    1001     External SSD    150         1 2024-10-10    150
11    1004  Docking Station    250         1 2024-10-11    250
12    1002         Keyboard     80         1 2024-10-12     80
13    1003           Webcam     55         1 2024-10-13     55
14    1001            Mouse     28         1 2024-10-14     28

In [34]:
df2 = df1.filter(["UserID", "Total"]).groupby("UserID").sum()
df2

        Total
UserID
1001     1513
1002      205
1003     1000
1004     1550

In [28]:
df2.sort_values("Total", ascending=False).head(2)

        Total
UserID
1004     1550
1001     1513

In [26]:
pivot_table(df, index= 'UserID', columns ='Total', values=)

SyntaxError: invalid syntax (2931148948.py, line 1)

In [ ]:
# 오름차순을 하고, .head(2)

columns = ['UserID', '총 구매 금액']

# 총 구매 금액을 기준으로 내림차순으로 정렬