# [LAB 04] 데이터 다루기 1. 데이터 구조 점검 (1)

## #01. 준비작업

### 1. 라이브러리 참조

In [160]:
from jussam import load_data            # 데이터 로딩 함수
from pandas import CategoricalDtype     # 명목형 타입 클래스

### 2. 데이터 불러오기

In [161]:
origin = load_data("grade")
origin

📚 어느 학급의 과목별 점수를 조사한 가상의 데이터

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

## #02. 데이터 확인하기 

### 1. 데이터의 크기

In [162]:
rows, cols = origin.shape
print("%d행, %d열의 %d 차원 데이터" % (rows, cols, origin.ndim))

9행, 6열의 2 차원 데이터

In [163]:
### 2. 각 변수의 데이터 타입 확인 
origin.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: int64(5), str(1)
memory usage: 612.0 bytes

## #03. 데이터 타입 변경

### 1. 작업을 위한 복사본 생성

In [164]:
컬럼타입변경df = origin.copy()
컬럼타입변경df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: int64(5), str(1)
memory usage: 612.0 bytes

### 2. 컬럼 단위 변경

In [165]:
컬럼타입변경df['국어'] = 컬럼타입변경df['국어'].astype('float')
컬럼타입변경df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      float64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: float64(1), int64(4), str(1)
memory usage: 612.0 bytes

### 3. 타입 일괄 변경 후 새로운 DataFrame 리턴 받기

In [166]:
타입변환df = origin.astype({'국어':'float', '영어':'float', '수학':'str', '과학':'bool'})

타입변환df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      float64
 3   영어      9 non-null      float64
 4   수학      9 non-null      str
 5   과학      9 non-null      bool
dtypes: bool(1), float64(2), int64(1), str(2)
memory usage: 567.0 bytes

### 4. 타입 변경 전 원본 확인

In [167]:
origin.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: int64(5), str(1)
memory usage: 612.0 bytes

### 5. 범주형 데이터를 명목척도로 변환 (1)

In [168]:
컬럼단위_명목df = origin.copy()
컬럼단위_명목df['학년'] = 컬럼단위_명목df['학년'].astype('category')
컬럼단위_명목df['성별'] = 컬럼단위_명목df['성별'].astype('category')                
컬럼단위_명목df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      category
 1   성별      9 non-null      category
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: category(2), int64(4)
memory usage: 493.0 bytes

### 6. 범주형 데이터를 명목척도로 변환 (2)

In [169]:
범주형df = origin.astype({'학년':'category', '성별':'category'})
범주형df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      category
 1   성별      9 non-null      category
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: category(2), int64(4)
memory usage: 493.0 bytes

### 7. 범주형 데이터를 서열척도로 변환 (1)

In [170]:
컬럼단위_서열척도df = origin.copy()
컬럼단위_서열척도df['학년'] = 컬럼단위_서열척도df['학년'].astype(
    CategoricalDtype(categories= [1,2,3,4], ordered=True))
컬럼단위_서열척도df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      category
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: category(1), int64(4), str(1)
memory usage: 753.0 bytes

### 8. 범주형 데이터를 서열척도로 변환(2)

In [171]:
서열척도df = origin.astype({
    "학년": CategoricalDtype(categories=[1,2,3,4], ordered=True)                
})

서열척도df.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      category
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: category(1), int64(4), str(1)
memory usage: 753.0 bytes

## #04. 열의 이름 변경 

### 1. rename() 메서드의 사용

In [172]:
이름변경df = origin.rename(
    columns = {'국어':'kor', '영어':'eng', '수학':'math', '과학':'sci'}, 
    index = {'석영':'suk', '호영':'ho', '민철':'min', '수현':'su'}
)

이름변경df

     학년  성별  kor  eng  math  sci
이름
철수    1  남자   98   77    88   64
영희    2  여자   88  120    62   72
min   1  남자   92   70    83   79
su    3  여자   63   60    31   71
ho    4  남자   75   50    90   88
영호    4  남자   80   88    91   72
용식    2  남자   82   88    79   90
나영    1  여자   90   92    81   95
suk   1  남자   91   90    89   80

## #1. 연습문제

In [173]:
# 전부 다 안보고 head()
fruit_shop.head()

   판매일   과일 등급    가격  판매량
0    1   사과  A  1500   10
1    1  바나나  B  1000   15
2    1   사과  B  1200    5
3    2  복숭아  A  2500    8
4    2  바나나  A  1200   12

In [174]:
from jussam import load_data
from pandas import CategoricalDtype
from pandas import DataFrame

In [175]:
fruit_shop = load_data('fruit_shop')
fruit_shop

📚 어느 과일 가게의 매출을 정리한 가상의 데이터(인덱스와 메타데이터 없음)

    판매일   과일 등급    가격  Num_Sold
0     1   사과  A  1500        10
1     1  바나나  B  1000        15
2     1   사과  B  1200         5
3     2  복숭아  A  2500         8
4     2  바나나  A  1200        12
5     2   사과  C  1000        20
6     3   사과  A  1500        12
7     3  복숭아  B  2200        10
8     3  바나나  B  1000        18
9     4  바나나  A  1200        20
10    4   사과  B  1200        11
11    4  복숭아  A  2500        15

In [176]:
rows, cols = fruit_shop.shape
print("%d행 %d열의 %d차원 데이터" % (rows, cols, origin.ndim))

12행 5열의 2차원 데이터

In [177]:
fruit_shop.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   판매일       12 non-null     int64
 1   과일        12 non-null     str
 2   등급        12 non-null     str
 3   가격        12 non-null     int64
 4   Num_Sold  12 non-null     int64
dtypes: int64(3), str(2)
memory usage: 717.0 bytes

In [178]:
# 데이터 변수의 이름을 바꿀때는 rename

In [179]:
({'Num_Sold':'판매량'})

{'Num_Sold': '판매량'}

In [180]:
fruit_shop = fruit_shop.rename(columns = {"Num_Sold":"판매량"})
fruit_shop.head()

   판매일   과일 등급    가격  판매량
0    1   사과  A  1500   10
1    1  바나나  B  1000   15
2    1   사과  B  1200    5
3    2  복숭아  A  2500    8
4    2  바나나  A  1200   12

In [181]:
df = fruit_shop.copy()
df

    판매일   과일 등급    가격  판매량
0     1   사과  A  1500   10
1     1  바나나  B  1000   15
2     1   사과  B  1200    5
3     2  복숭아  A  2500    8
4     2  바나나  A  1200   12
5     2   사과  C  1000   20
6     3   사과  A  1500   12
7     3  복숭아  B  2200   10
8     3  바나나  B  1000   18
9     4  바나나  A  1200   20
10    4   사과  B  1200   11
11    4  복숭아  A  2500   15

In [182]:
df = df.astype({'과일':'category'})
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   판매일     12 non-null     int64
 1   과일      12 non-null     category
 2   등급      12 non-null     str
 3   가격      12 non-null     int64
 4   판매량     12 non-null     int64
dtypes: category(1), int64(3), str(1)
memory usage: 589.0 bytes

In [183]:
df = df.astype({'등급':'category'})
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   판매일     12 non-null     int64
 1   과일      12 non-null     category
 2   등급      12 non-null     category
 3   가격      12 non-null     int64
 4   판매량     12 non-null     int64
dtypes: category(2), int64(3)
memory usage: 521.0 bytes

In [184]:
df = df.astype({'등급': CategoricalDtype(categories=['A','B','C'], ordered=True)})
df

    판매일   과일 등급    가격  판매량
0     1   사과  A  1500   10
1     1  바나나  B  1000   15
2     1   사과  B  1200    5
3     2  복숭아  A  2500    8
4     2  바나나  A  1200   12
5     2   사과  C  1000   20
6     3   사과  A  1500   12
7     3  복숭아  B  2200   10
8     3  바나나  B  1000   18
9     4  바나나  A  1200   20
10    4   사과  B  1200   11
11    4  복숭아  A  2500   15

In [185]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   판매일     12 non-null     int64
 1   과일      12 non-null     category
 2   등급      12 non-null     category
 3   가격      12 non-null     int64
 4   판매량     12 non-null     int64
dtypes: category(2), int64(3)
memory usage: 520.0 bytes

In [ ]:
fruit_shop.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   판매일     12 non-null     int64
 1   과일      12 non-null     str
 2   등급      12 non-null     str
 3   가격      12 non-null     int64
 4   판매량     12 non-null     int64
dtypes: int64(3), str(2)
memory usage: 717.0 bytes

## #2. 연습문제

In [ ]:
# DataFrame 

# class time 

# data =

In [ ]:
# A1 : 62,60,63,59,61
# A2 : 62,67,71,64,65,66
# A3 : 68,66,71,67,68,69,70
# A4 : 58,62,60,59,61,63,64

In [ ]:
# class = [ "A1", "A2", "A3", "A4" ]

In [ ]:
# time = [ 62,60,63,59,61,
#     62,67,71,64,65,66,
#     68,66,71,67,68,69,70,
#     58,62,60,59,61,63,64 ]

In [ ]:
data = { 
    "class" : [ "A1","A1","A1","A1","A1",
               "A2","A2","A2","A2","A2","A2",
               "A3","A3","A3","A3","A3","A3","A3",
               "A4","A4","A4","A4","A4","A4","A4"
    ],

    "time": [ 62,60,63,59,61,
            62,67,71,64,65,66,
            68,66,71,67,68,69,70,
            58,62,60,59,61,63,64 ]
        
        } 

df= DataFrame(data)
df

   class  time
0     A1    62
1     A1    60
2     A1    63
3     A1    59
4     A1    61
5     A2    62
6     A2    67
7     A2    71
8     A2    64
9     A2    65
10    A2    66
11    A3    68
12    A3    66
13    A3    71
14    A3    67
15    A3    68
16    A3    69
17    A3    70
18    A4    58
19    A4    62
20    A4    60
21    A4    59
22    A4    61
23    A4    63
24    A4    64

In [ ]:
data = [

{"class":"A1", "time":62}, 
"class":"A1", "time":60 
"class":"A1", "time":63 
"class":"A1", "time":59 
"class":"A1", "time":61
"class":"A2", "time":62 
"class":"A2", "time":62 
"class":"A2", "time":62 
"class":"A2", "time":62 
"class":"A2", "time":62 
"class":"A2", "time":62 
"class":"A3", "time":62 
"class":"A3", "time":62 
"class":"A3", "time":62 
"class":"A3", "time":62 
"class":"A3", "time":62 
"class":"A3", "time":62 
"class":"A3", "time":62 
"class":"A3", "time":62 
"class":"A4", "time":62 
"class":"A4", "time":62 
"class":"A4", "time":62 
"class":"A4", "time":62 
"class":"A4", "time":62 
"class":"A4", "time":62 
"class":"A4", "time":62 
"class":"A4", "time":62 

]

In [ ]:
data = [
    {"class": "A1", "time": 62},
    {"class": "A1", "time": 60},
    {"class": "A1", "time": 63},
    {"class": "A1", "time": 59},
    {"class": "A1", "time": 61},
    {"class": "A2", "time": 62},
    {"class": "A2", "time": 67},
    {"class": "A2", "time": 71},
    {"class": "A2", "time": 64},
    {"class": "A2", "time": 65},
    {"class": "A2", "time": 66},
    {"class": "A3", "time": 68},
    {"class": "A3", "time": 66},
    {"class": "A3", "time": 71},
    {"class": "A3", "time": 67},
    {"class": "A3", "time": 68},
    {"class": "A3", "time": 69},
    {"class": "A3", "time": 70},
    {"class": "A4", "time": 58},
    {"class": "A4", "time": 62},
    {"class": "A4", "time": 60},
    {"class": "A4", "time": 59},
    {"class": "A4", "time": 61},
    {"class": "A4", "time": 63},
    {"class": "A4", "time": 64}
]

df = DataFrame(data)
df

   class  time
0     A1    62
1     A1    60
2     A1    63
3     A1    59
4     A1    61
5     A2    62
6     A2    67
7     A2    71
8     A2    64
9     A2    65
10    A2    66
11    A3    68
12    A3    66
13    A3    71
14    A3    67
15    A3    68
16    A3    69
17    A3    70
18    A4    58
19    A4    62
20    A4    60
21    A4    59
22    A4    61
23    A4    63
24    A4    64