# [LAB-04] 8. 데이터 재구조화 - 연습문제

## 라이브러리 참조

In [1]:
from jussam import load_data
from pandas import DataFrame, pivot_table, melt

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

## 연습문제 1 - 학생 흡연율 데이터 전처리

In [2]:
df = load_data("students_smoke")
df

📚 한 도시의 20개 중,고교를 대상으로 조사한 흡연율 자료 (인덱스와 메타데이터 없음)

    지역  구성   흡연율
0   도시   남 0.640
1   도시   여 0.450
2   농촌  공학 0.700
3   도시   남 0.850
4   농촌   남 0.720
5   도시   남 0.780
6   도시   여 0.620
7   도시   남 0.790
8   농촌   남 0.750
9   농촌  공학 0.810
10  농촌   여 0.560
11  도시   여 0.480
12  농촌   남 0.720
13  도시  공학 0.680
14  농촌   남 0.790
15  도시   남 0.900
16  농촌   여 0.340
17  도시   여 0.480
18  농촌   여 0.490
19  농촌  공학 0.760

In [3]:
pivot_table(df, index='지역', columns='구성', values='흡연율', aggfunc='mean')

구성    공학     남     여
지역
농촌 0.757 0.745 0.463
도시 0.680 0.792 0.507

## 연습문제 2 - 동네 아이스크림 가게 매출 분석 챌린지!

In [4]:
df = load_data('icecream_sales')
df

📚 '달콤 스쿱' 아이스크림 가게의 매출 데이터 (인덱스 없음)

         Date Flavor Topping  Price  Quantity
0  2023-07-01    초콜릿     아몬드   3500    20.000
1  2023-07-01    바닐라    초코시럽   3000    25.000
2  2023-07-01     딸기      연유   3200    18.000
3  2023-07-02   민트초코     초코칩   3800    15.000
4  2023-07-02    초콜릿     아몬드   3500    22.000
5  2023-07-02    바닐라    None   3000    30.000
6  2023-07-03     딸기      연유   3200    25.000
7  2023-07-03   민트초코     초코칩   3800       NaN
8  2023-07-03    바닐라    초코시럽   3000    28.000
9  2023-07-04    초콜릿     아몬드   3500    18.000
10 2023-07-04     딸기      연유   3200    22.000
11 2023-07-04   민트초코     초코칩   3800    17.000

### 1. 구조와 정보를 확인, 결측치가 있는지 확인, 결측치 행을 제거

#### 1) 구조와 정보 확인

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      12 non-null     datetime64[us]
 1   Flavor    12 non-null     object
 2   Topping   11 non-null     object
 3   Price     12 non-null     int64
 4   Quantity  11 non-null     float64
dtypes: datetime64[us](1), float64(1), int64(1), object(2)
memory usage: 612.0+ bytes

#### 2) 결측치가 있는지 확인

In [6]:
df.isna().sum()

Date        0
Flavor      0
Topping     1
Price       0
Quantity    1
dtype: int64

#### 3) 결측치 행 제거

In [7]:
df2 = df.dropna()
df2

         Date Flavor Topping  Price  Quantity
0  2023-07-01    초콜릿     아몬드   3500    20.000
1  2023-07-01    바닐라    초코시럽   3000    25.000
2  2023-07-01     딸기      연유   3200    18.000
3  2023-07-02   민트초코     초코칩   3800    15.000
4  2023-07-02    초콜릿     아몬드   3500    22.000
6  2023-07-03     딸기      연유   3200    25.000
8  2023-07-03    바닐라    초코시럽   3000    28.000
9  2023-07-04    초콜릿     아몬드   3500    18.000
10 2023-07-04     딸기      연유   3200    22.000
11 2023-07-04   민트초코     초코칩   3800    17.000

#### 2. 피벗 테이블

In [8]:
df3 = pivot_table(df2, index='Date', columns='Flavor', values='Quantity')
df3

Flavor         딸기   민트초코    바닐라    초콜릿
Date
2023-07-01 18.000    NaN 25.000 20.000
2023-07-02    NaN 15.000    NaN 22.000
2023-07-03 25.000    NaN 28.000    NaN
2023-07-04 22.000 17.000    NaN 18.000

### 3. 피벗 테이블을 다시 Long format으로 분리

In [9]:
df4 = df3.reset_index()
df4

Flavor       Date     딸기   민트초코    바닐라    초콜릿
0      2023-07-01 18.000    NaN 25.000 20.000
1      2023-07-02    NaN 15.000    NaN 22.000
2      2023-07-03 25.000    NaN 28.000    NaN
3      2023-07-04 22.000 17.000    NaN 18.000

In [10]:
df5 = melt(df4, id_vars=['Date'],
           value_vars=['딸기','민트초코','바닐라','초콜릿'],
           var_name='Flavor', value_name='Quantity')
df5

         Date Flavor  Quantity
0  2023-07-01     딸기    18.000
1  2023-07-02     딸기       NaN
2  2023-07-03     딸기    25.000
3  2023-07-04     딸기    22.000
4  2023-07-01   민트초코       NaN
5  2023-07-02   민트초코    15.000
6  2023-07-03   민트초코       NaN
7  2023-07-04   민트초코    17.000
8  2023-07-01    바닐라    25.000
9  2023-07-02    바닐라       NaN
10 2023-07-03    바닐라    28.000
11 2023-07-04    바닐라       NaN
12 2023-07-01    초콜릿    20.000
13 2023-07-02    초콜릿    22.000
14 2023-07-03    초콜릿       NaN
15 2023-07-04    초콜릿    18.000

## 연습문제 3 - 게임 토너먼트 최고 득점자 찾기

### 데이터 가져오기

In [11]:
df = load_data("game_scores")
df

📚 최근 열린 게임 토너먼트 경기 결과 데이터 (인덱스와 메타데이터 없음)

    player  stage1  stage2  stage3
0    Alice      85  92.000  88.000
1      Bob      78     NaN  95.000
2  Charlie      90  88.000  91.000
3    David      82  85.000     NaN
4      Eva      95  98.000  99.000

### 1. 각 스테이지 점수가 열로 구성된 데이터를, 선수와 스테이지 레벨에 따른 점수를 나타내는 형태로 재구조화하세요.

In [12]:
# 요구사항에 스테이지에 모두 참여한 선수만을 대상으로 하라고 했으므로 결측치 행을 제거해야 한다.
df1 = df.dropna()

df2 = df1.set_index('player')
df3 = DataFrame(df2.stack())
df3

                    0
player
Alice   stage1 85.000
        stage2 92.000
        stage3 88.000
Charlie stage1 90.000
        stage2 88.000
        stage3 91.000
Eva     stage1 95.000
        stage2 98.000
        stage3 99.000

### 2. 선수별 평균 점수를 계산하세요.

In [13]:
df4 = df3.reset_index()
df4.filter(['player', 0]).groupby('player').mean()

             0
player
Alice   88.333
Charlie 89.667
Eva     97.333