# [LAB-03] 4. 모델링

## #01. 준비작업

### 1. 패키지 설치

In [1]:
!pip install --upgrade xgboost

Requirement already satisfied: xgboost in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (3.4.1)
Requirement already satisfied: numpy in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from xgboost) (1.18.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [2]:
!pip install --upgrade lightgbm

Requirement already satisfied: lightgbm in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (4.7.0)
Requirement already satisfied: narwhals>=1.15 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from lightgbm) (2.15.0)
Requirement already satisfied: numpy>=1.21.3 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from lightgbm) (2.3.5)
Requirement already satisfied: scipy in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from lightgbm) (1.18.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [3]:
!pip install --upgrade catboost

Requirement already satisfied: catboost in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (1.2.10)
Requirement already satisfied: graphviz in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from catboost) (3.11.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from catboost) (2.3.5)
Requirement already satisfied: pandas<4.0,>=0.24 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from catboost) (2.3.3)
Requirement already satisfied: scipy in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from catboost) (1.18.0)
Requirement already satisfied: plotly in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from catboost) (6.5.1)
Requirement already satisfied: six in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from matplotlib->catboost) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=9 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from matplotlib->catboost) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from plotly->catboost) (2.15.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

### 2. 기본 라이브러리 참조

In [4]:
from jussam import load_data
from helpers import *
import datetime as dt
import os
import glob as gl   # 파일 목록을 리스트로 반환하는 파이썬 내장 모듈

# 훈련,검증 데이터 분리 함수
from sklearn.model_selection import train_test_split

# 하이퍼파라미터 튜닝
from sklearn.model_selection import GridSearchCV

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/
🔖 Version: 0.5.19

### 3. 머신러닝 학습 모델 라이브러리 참조

In [5]:
# 선형 계열 모델
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet

# 비선형 계열 모델
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

# 트리계열 모델
from sklearn.tree import DecisionTreeRegressor

# 앙상블 모델
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

### 4. 데이터 불러오기

- 파생변수를 포함한 최종 변수 채택 후 로그 변환과 라벨링이 완료된 데이터

In [6]:
# 분석용 데이터 전처리가 완료된 데이터 셋
origin = load_data("california_housing_feature_log_labelled")
df = my_qtcheck.set_type(origin, as_category=["is_age_capped", "is_income_capped", "ocean_area", "special_cluster"])

📚 캘리포니아 주택 가격 데이터셋의 파생변수 추가 버전에 대한 로그 변환 및 라벨링 처리 데이터 (출처: 자체 작업)

    field                     description
--  ------------------------  -------------------------------------------------
 0  housing_median_age        주택 중위 연령 (로그변환됨)
 1  rooms_per_person          인당 방 수 (로그변환됨)
 2  rooms_per_household       가구당 방 수 (로그변환됨)
 3  bedrooms_per_room         방당 침실 수 (로그변환됨)
 4  population_per_household  가구당 인구 (로그변환됨)
 5  income_per_person         인당 소득 (로그변환됨)
 6  is_age_capped             주택 연령 제한 여부(범주형: 제한안함=0, 제한함=1)
 7  is_income_capped          소득 제한 여부(범주형: 제한안함=0, 제한함=1)
 8  ocean_area                해양 지역 여부(범주형: COASTAL=0, INLAND=1)
 9  special_cluster           공간정보 클러스터 여부(범주형 0~4)
10  median_house_value        주택 중위 가격(종속변수, 로그변환됨)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20433 entries, 0 to 20432
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   housing_median_age        20433 non-null  int64
 1   rooms_per_person          20433 non-null  float64
 2   rooms_per_household       20433 non-null  float64
 3   bedrooms_per_room         20433 non-null  float64
 4   population_per_household  20433 non-null  float64
 5   income_per_person         20433 non-null  float64
 6   is_age_capped             20433 non-null  category
 7   is_income_capped          20433 non-null  category
 8   ocean_area                20433 non-null  category
 9   special_cluster           20433 non-null  category
 10  median_house_value        20433 non-null  float64
dtypes: category(4), float64(6), int64(1)
memory usage: 1.2 MB

### 5. 데이터에서 독립변수와 종속변수 분리

- 머신러닝에서는 독립변수를 feature, 종속변수를 target으로 명명한다.

In [7]:
feature = df.drop(columns=["median_house_value"])
target = df["median_house_value"]
feature.shape, target.shape

((20433, 10), (20433,))

### 6. 훈련, 검증 데이터 분리

In [8]:
# 훈련, 검증 데이터 분리
# 분류 문제인 경우 파라미터 추가 --> stratify=target
x_train, x_test, y_train, y_test = train_test_split(feature, target, test_size=0.2, random_state=RANDOM_STATE)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

((16346, 10), (4087, 10), (16346,), (4087,))

### 7. 학습을 완료한 모델이 저장될 폴더

In [9]:
timestemp = dt.datetime.now().strftime("%Y%m%d_%H%M%S")
workdir = f"ml_models/{timestemp}"

if not os.path.exists(workdir):
    os.makedirs(workdir)

## #02. 선형계열 모델

### 1. LinearRegressor

In [10]:
# 파이프라인 구축 -> 학습 -> 저장
linear = my_ml.fit_pipeline(
                model=LinearRegression(),  # <-- LinearRegressor 학습 모델
                x_train=x_train, y_train=y_train, 
                vif=True, 
                scale=False, 
                drop_first=True,
                save_path=f"{workdir}/linear.pkl")

linear

대상: 16346행 x 10열 | 모델: LinearRegression
명목형: ['is_age_capped', 'is_income_capped', 'ocean_area', 'special_cluster']
연속형: ['housing_median_age', 'rooms_per_person', 'rooms_per_household', 'bedrooms_per_room', 'population_per_household', 'income_per_person']

전처리 단계
  연속형: 다중공선성 제거(VIF >= 10.0)
  명목형: 더미변수 인코딩(drop_first=True)

모델 학습 완료: LinearRegression
모델 저장: ml_models/20260820_075728/linear.pkl

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('vif_selector',
                                                                   VIFSelector())]),
                                                  ['housing_median_age',
                                                   'rooms_per_person',
                                                   'rooms_per_household',
                                                   'bedrooms_per_room',
                                                   'population_per_household',
                                                   'income_per_person']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['is_age_capped',
                                                   'is_income_capped',
                                                   'ocean_area',
                                                   'special_cluster'])],
                                   verbose_feature_names_out=False)),
                ('model', LinearRegression())])

### 2. Ridge

In [11]:
# 파이프라인 구축 -> 학습 -> 저장
ridge = my_ml.fit_pipeline(
                model=Ridge(random_state=RANDOM_STATE),
                x_train=x_train, y_train=y_train,
                vif=True, 
                scale=True, 
                drop_first=True,
                save_path=f"{workdir}/ridge.pkl")

ridge

대상: 16346행 x 10열 | 모델: Ridge
명목형: ['is_age_capped', 'is_income_capped', 'ocean_area', 'special_cluster']
연속형: ['housing_median_age', 'rooms_per_person', 'rooms_per_household', 'bedrooms_per_room', 'population_per_household', 'income_per_person']

전처리 단계
  연속형: 다중공선성 제거(VIF >= 10.0) → 정규화(standard)
  명목형: 더미변수 인코딩(drop_first=True)

모델 학습 완료: Ridge
모델 저장: ml_models/20260820_075728/ridge.pkl

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('vif_selector',
                                                                   VIFSelector()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['housing_median_age',
                                                   'rooms_per_person',
                                                   'rooms_per_household',
                                                   'bedrooms_per_room',
                                                   'population_per_household',
                                                   'income_per_person']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['is_age_capped',
                                                   'is_income_capped',
                                                   'ocean_area',
                                                   'special_cluster'])],
                                   verbose_feature_names_out=False)),
                ('model', Ridge(random_state=3217))])

### 3. Lasso

In [12]:
lasso = my_ml.fit_pipeline(
                model=Lasso(random_state=RANDOM_STATE),
                x_train=x_train, y_train=y_train,
                vif=True, 
                scale=True, 
                drop_first=True,
                save_path=f"{workdir}/lasso.pkl")
lasso

대상: 16346행 x 10열 | 모델: Lasso
명목형: ['is_age_capped', 'is_income_capped', 'ocean_area', 'special_cluster']
연속형: ['housing_median_age', 'rooms_per_person', 'rooms_per_household', 'bedrooms_per_room', 'population_per_household', 'income_per_person']

전처리 단계
  연속형: 다중공선성 제거(VIF >= 10.0) → 정규화(standard)
  명목형: 더미변수 인코딩(drop_first=True)

모델 학습 완료: Lasso
모델 저장: ml_models/20260820_075728/lasso.pkl

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('vif_selector',
                                                                   VIFSelector()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['housing_median_age',
                                                   'rooms_per_person',
                                                   'rooms_per_household',
                                                   'bedrooms_per_room',
                                                   'population_per_household',
                                                   'income_per_person']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['is_age_capped',
                                                   'is_income_capped',
                                                   'ocean_area',
                                                   'special_cluster'])],
                                   verbose_feature_names_out=False)),
                ('model', Lasso(random_state=3217))])

### 4. ElasticNet

In [13]:
elasticnet = my_ml.fit_pipeline(
                model=ElasticNet(random_state=RANDOM_STATE),
                x_train=x_train, y_train=y_train,
                vif=True, 
                scale=True, 
                drop_first=True,
                save_path=f"{workdir}/elasticnet.pkl")
elasticnet

대상: 16346행 x 10열 | 모델: ElasticNet
명목형: ['is_age_capped', 'is_income_capped', 'ocean_area', 'special_cluster']
연속형: ['housing_median_age', 'rooms_per_person', 'rooms_per_household', 'bedrooms_per_room', 'population_per_household', 'income_per_person']

전처리 단계
  연속형: 다중공선성 제거(VIF >= 10.0) → 정규화(standard)
  명목형: 더미변수 인코딩(drop_first=True)

모델 학습 완료: ElasticNet
모델 저장: ml_models/20260820_075728/elasticnet.pkl

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('vif_selector',
                                                                   VIFSelector()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['housing_median_age',
                                                   'rooms_per_person',
                                                   'rooms_per_household',
                                                   'bedrooms_per_room',
                                                   'population_per_household',
                                                   'income_per_person']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['is_age_capped',
                                                   'is_income_capped',
                                                   'ocean_area',
                                                   'special_cluster'])],
                                   verbose_feature_names_out=False)),
                ('model', ElasticNet(random_state=3217))])

## #03. 비선형 계열 모델

### 1. KNN

In [14]:
knn = my_ml.fit_pipeline(
                model=KNeighborsRegressor(n_jobs=-1),
                x_train=x_train, y_train=y_train,
                vif=True, 
                scale=True, 
                drop_first=True,
                save_path=f"{workdir}/knn.pkl")

knn

대상: 16346행 x 10열 | 모델: KNeighborsRegressor
명목형: ['is_age_capped', 'is_income_capped', 'ocean_area', 'special_cluster']
연속형: ['housing_median_age', 'rooms_per_person', 'rooms_per_household', 'bedrooms_per_room', 'population_per_household', 'income_per_person']

전처리 단계
  연속형: 다중공선성 제거(VIF >= 10.0) → 정규화(standard)
  명목형: 더미변수 인코딩(drop_first=True)

모델 학습 완료: KNeighborsRegressor
모델 저장: ml_models/20260820_075728/knn.pkl

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('vif_selector',
                                                                   VIFSelector()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['housing_median_age',
                                                   'rooms_per_person',
                                                   'rooms_per_household',
                                                   'bedrooms_per_room',
                                                   'population_per_household',
                                                   'income_per_person']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['is_age_capped',
                                                   'is_income_capped',
                                                   'ocean_area',
                                                   'special_cluster'])],
                                   verbose_feature_names_out=False)),
                ('model', KNeighborsRegressor(n_jobs=-1))])

### 2. Support Vector Regressor

In [15]:
svr = my_ml.fit_pipeline(
                model=SVR(),
                x_train=x_train, y_train=y_train,
                vif=True,
                scale=True, 
                drop_first=True,
                save_path=f"{workdir}/svr.pkl")
svr

대상: 16346행 x 10열 | 모델: SVR
명목형: ['is_age_capped', 'is_income_capped', 'ocean_area', 'special_cluster']
연속형: ['housing_median_age', 'rooms_per_person', 'rooms_per_household', 'bedrooms_per_room', 'population_per_household', 'income_per_person']

전처리 단계
  연속형: 다중공선성 제거(VIF >= 10.0) → 정규화(standard)
  명목형: 더미변수 인코딩(drop_first=True)

모델 학습 완료: SVR
모델 저장: ml_models/20260820_075728/svr.pkl

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('vif_selector',
                                                                   VIFSelector()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['housing_median_age',
                                                   'rooms_per_person',
                                                   'rooms_per_household',
                                                   'bedrooms_per_room',
                                                   'population_per_household',
                                                   'income_per_person']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['is_age_capped',
                                                   'is_income_capped',
                                                   'ocean_area',
                                                   'special_cluster'])],
                                   verbose_feature_names_out=False)),
                ('model', SVR())])

## #04. 트리 계열 모델

### 1. Decision Tree

In [16]:
dtree = my_ml.fit_pipeline(
                model=DecisionTreeRegressor(random_state=RANDOM_STATE),
                x_train=x_train, y_train=y_train,
                vif=True, 
                encode=True, 
                save_path=f"{workdir}/dtree.pkl")
dtree

대상: 16346행 x 10열 | 모델: DecisionTreeRegressor
명목형: ['is_age_capped', 'is_income_capped', 'ocean_area', 'special_cluster']
연속형: ['housing_median_age', 'rooms_per_person', 'rooms_per_household', 'bedrooms_per_room', 'population_per_household', 'income_per_person']

전처리 단계
  연속형: 다중공선성 제거(VIF >= 10.0)
  명목형: 더미변수 인코딩(drop_first=False)

모델 학습 완료: DecisionTreeRegressor
모델 저장: ml_models/20260820_075728/dtree.pkl

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('vif_selector',
                                                                   VIFSelector())]),
                                                  ['housing_median_age',
                                                   'rooms_per_person',
                                                   'rooms_per_household',
                                                   'bedrooms_per_room',
                                                   'population_per_household',
                                                   'income_per_person']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['is_age_capped',
                                                   'is_income_capped',
                                                   'ocean_area',
                                                   'special_cluster'])],
                                   verbose_feature_names_out=False)),
                ('model', DecisionTreeRegressor(random_state=3217))])

## #05. 앙상블 모델

### 1. Random Forest

In [17]:
rf = my_ml.fit_pipeline(
                model=RandomForestRegressor(
                    random_state=RANDOM_STATE, n_jobs=-1),
                x_train=x_train, y_train=y_train,
                vif=True, 
                encode=True, 
                save_path=f"{workdir}/rf.pkl")
rf

대상: 16346행 x 10열 | 모델: RandomForestRegressor
명목형: ['is_age_capped', 'is_income_capped', 'ocean_area', 'special_cluster']
연속형: ['housing_median_age', 'rooms_per_person', 'rooms_per_household', 'bedrooms_per_room', 'population_per_household', 'income_per_person']

전처리 단계
  연속형: 다중공선성 제거(VIF >= 10.0)
  명목형: 더미변수 인코딩(drop_first=False)

모델 학습 완료: RandomForestRegressor
모델 저장: ml_models/20260820_075728/rf.pkl

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('vif_selector',
                                                                   VIFSelector())]),
                                                  ['housing_median_age',
                                                   'rooms_per_person',
                                                   'rooms_per_household',
                                                   'bedrooms_per_room',
                                                   'population_per_household',
                                                   'income_per_person']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['is_age_capped',
                                                   'is_income_capped',
                                                   'ocean_area',
                                                   'special_cluster'])],
                                   verbose_feature_names_out=False)),
                ('model', RandomForestRegressor(n_jobs=-1, random_state=3217))])

### 2. XGBoost

In [18]:
xgb = my_ml.fit_pipeline(
            model=XGBRegressor(
                random_state=RANDOM_STATE, n_jobs=-1),
            x_train=x_train, y_train=y_train,
            vif=True, 
            encode=True, 
            save_path=f"{workdir}/xgb.pkl")
xgb

대상: 16346행 x 10열 | 모델: XGBRegressor
명목형: ['is_age_capped', 'is_income_capped', 'ocean_area', 'special_cluster']
연속형: ['housing_median_age', 'rooms_per_person', 'rooms_per_household', 'bedrooms_per_room', 'population_per_household', 'income_per_person']

전처리 단계
  연속형: 다중공선성 제거(VIF >= 10.0)
  명목형: 더미변수 인코딩(drop_first=False)

모델 학습 완료: XGBRegressor
모델 저장: ml_models/20260820_075728/xgb.pkl

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('vif_selector',
                                                                   VIFSelector())]),
                                                  ['housing_median_age',
                                                   'rooms_per_person',
                                                   'rooms_per_household',
                                                   'bedrooms_per_room',
                                                   'population_per_household',
                                                   'income_per_person']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='i...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=-1,
                              num_parallel_tree=None, ...))])

### 3.  LightGBM

In [19]:
lgbm = my_ml.fit_pipeline(
            model=LGBMRegressor(
                    random_state=RANDOM_STATE, n_jobs=-1, verbose=-1),
            x_train=x_train, y_train=y_train,
            vif=True, 
            encode=True, 
            save_path=f"{workdir}/lgbm.pkl")
lgbm

대상: 16346행 x 10열 | 모델: LGBMRegressor
명목형: ['is_age_capped', 'is_income_capped', 'ocean_area', 'special_cluster']
연속형: ['housing_median_age', 'rooms_per_person', 'rooms_per_household', 'bedrooms_per_room', 'population_per_household', 'income_per_person']

전처리 단계
  연속형: 다중공선성 제거(VIF >= 10.0)
  명목형: 더미변수 인코딩(drop_first=False)

모델 학습 완료: LGBMRegressor
모델 저장: ml_models/20260820_075728/lgbm.pkl

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('vif_selector',
                                                                   VIFSelector())]),
                                                  ['housing_median_age',
                                                   'rooms_per_person',
                                                   'rooms_per_household',
                                                   'bedrooms_per_room',
                                                   'population_per_household',
                                                   'income_per_person']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['is_age_capped',
                                                   'is_income_capped',
                                                   'ocean_area',
                                                   'special_cluster'])],
                                   verbose_feature_names_out=False)),
                ('model',
                 LGBMRegressor(n_jobs=-1, random_state=3217, verbose=-1))])

### 4. CatBoost

In [20]:
catboost = my_ml.fit_pipeline(
            model=CatBoostRegressor(
                    random_state=RANDOM_STATE, verbose=0),
            x_train=x_train, y_train=y_train,
            vif=True, 
            encode=False,   # CatBoost는 자체적으로 범주형 처리하므로 encode=False
            save_path=f"{workdir}/catboost.pkl",
            # 이름이 `단계명__인자명` 형식인 인자는 모델의 fit 으로 그대로 전달된다
            model__cat_features=my_qtcheck.get_categorical_column_names(x_train))
catboost

대상: 16346행 x 10열 | 모델: CatBoostRegressor
명목형: ['is_age_capped', 'is_income_capped', 'ocean_area', 'special_cluster']
연속형: ['housing_median_age', 'rooms_per_person', 'rooms_per_household', 'bedrooms_per_room', 'population_per_household', 'income_per_person']

전처리 단계
  연속형: 다중공선성 제거(VIF >= 10.0)
  명목형: (변환 없음)

모델 학습 완료: CatBoostRegressor
모델 저장: ml_models/20260820_075728/catboost.pkl

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('vif_selector',
                                                                   VIFSelector())]),
                                                  ['housing_median_age',
                                                   'rooms_per_person',
                                                   'rooms_per_household',
                                                   'bedrooms_per_room',
                                                   'population_per_household',
                                                   'income_per_person']),
                                                 ('cat', 'passthrough',
                                                  ['is_age_capped',
                                                   'is_income_capped',
                                                   'ocean_area',
                                                   'special_cluster'])],
                                   verbose_feature_names_out=False)),
                ('model',
                 CatBoostRegressor(loss_function='RMSE', random_state=3217, verbose=0))])

## #06. 최고 성능 모델 선정

### 1. 학습 모델 파일 목록

In [21]:
# 작업폴더 내의 모든 pkl 파일 목록 확인
model_pickles = gl.glob(f"{workdir}/*.pkl")
print(model_pickles)

['ml_models/20260820_075728/catboost.pkl', 'ml_models/20260820_075728/elasticnet.pkl', 'ml_models/20260820_075728/rf.pkl', 'ml_models/20260820_075728/knn.pkl', 'ml_models/20260820_075728/lasso.pkl', 'ml_models/20260820_075728/ridge.pkl', 'ml_models/20260820_075728/dtree.pkl', 'ml_models/20260820_075728/xgb.pkl', 'ml_models/20260820_075728/linear.pkl', 'ml_models/20260820_075728/svr.pkl', 'ml_models/20260820_075728/lgbm.pkl']

### 2. 학습 모델 불러오기

In [22]:
models = {}                         # 모델명과 모델 객체를 저장할 딕셔너리

for p in model_pickles:
    model_name = p.split(".")[0]    # 파일 목록에서 파일명만 분리
    model = my_ml.load_model(p)     # 모델 로드
    models[model.name_] = model     # 모델명과 모델 객체를 딕셔너리에 저장

# 로드된 모델과 모델 객체의 타입 출력
for name, model in models.items():
    print(f"- {name}: {type(model)}")

- CatBoostRegressor: <class 'sklearn.pipeline.Pipeline'>
- ElasticNet: <class 'sklearn.pipeline.Pipeline'>
- RandomForestRegressor: <class 'sklearn.pipeline.Pipeline'>
- KNeighborsRegressor: <class 'sklearn.pipeline.Pipeline'>
- Lasso: <class 'sklearn.pipeline.Pipeline'>
- Ridge: <class 'sklearn.pipeline.Pipeline'>
- DecisionTreeRegressor: <class 'sklearn.pipeline.Pipeline'>
- XGBRegressor: <class 'sklearn.pipeline.Pipeline'>
- LinearRegression: <class 'sklearn.pipeline.Pipeline'>
- SVR: <class 'sklearn.pipeline.Pipeline'>
- LGBMRegressor: <class 'sklearn.pipeline.Pipeline'>

### 3. 특정 모델의 성능지표 확인

In [23]:
my_ml.reg_score(models['CatBoostRegressor'], x_test, y_test)

                     R2   MAE   MSE  RMSE  RMSLE  MAPE    MPE
Model
CatBoostRegressor 0.782 0.195 0.072 0.267  0.021 1.619 -0.047

### 4. 모델간 성능평가 비교

In [24]:
my_ml.reg_compare_models(models,               # 모델 객체들을 담은 딕셔너리
                         x_test,               # 검증 데이터의 독립 변수
                         y_test,               # 검증 데이터의 종속 변수
                         primary="RMSE",       # 주 지표
                         aux=["MAE", "R2"])    # 보조 지표

======================================================================
◆ Score Table Ranking : primary='RMSE', aux=['MAE', 'R2']
======================================================================

▲ step1: 주 지표(RMSE) 기준 정렬 — 낮을수록 좋음 (ASC)
    1. SVR            RMSE  =            0.265
    2. CatBoostRegressor RMSE  =            0.267
    3. LGBMRegressor  RMSE  =            0.270
    4. RandomForestRegressor RMSE  =            0.272
    5. XGBRegressor   RMSE  =            0.278
    6. KNeighborsRegressor RMSE  =            0.282
    7. LinearRegression RMSE  =            0.307
    8. Ridge          RMSE  =            0.307
    9. DecisionTreeRegressor RMSE  =            0.366
   10. ElasticNet     RMSE  =            0.574
   11. Lasso          RMSE  =            0.574

▲ step2: 근소 격차 그룹 묶기 (1등의 5% 이내)
   - 1등 RMSE   : 0.265
   - 허용 범위    : RMSE ≤ 0.278
   - 근소 격차 그룹 (4) : ['SVR', 'CatBoostRegressor', 'LGBMRegressor', 'RandomForestRegressor']
   - 그룹 외부     (7) : ['XGBRegressor', 'KNeighborsRegressor', 'LinearRegression', 'Ridge', 'DecisionTreeRegressor', 'ElasticNet', 'Lasso']

▲ step3: 보조 지표 결정적 결함 점검 (근소 격차 그룹 내부)
   - 그룹 1등 점수 / 결함 임계치:
       · MAE    best=     0.190   결함조건: row > 0.208  (1등 × 1.10)
       · R2     best=     0.787   결함조건: row < 0.737  (1등 − 0.05)
   - 모델별 결함:
       · SVR            0개 (결함 없음)
       · CatBoostRegressor 0개 (결함 없음)
       · LGBMRegressor  0개 (결함 없음)
       · RandomForestRegressor 0개 (결함 없음)

▲ step4: 최종 Rank
    1. SVR            [그룹 내]
    2. CatBoostRegressor [그룹 내]
    3. LGBMRegressor  [그룹 내]
    4. RandomForestRegressor [그룹 내]
    5. XGBRegressor   [그룹 외 · 주 지표 순]
    6. KNeighborsRegressor [그룹 외 · 주 지표 순]
    7. LinearRegression [그룹 외 · 주 지표 순]
    8. Ridge          [그룹 외 · 주 지표 순]
    9. DecisionTreeRegressor [그룹 외 · 주 지표 순]
   10. ElasticNet     [그룹 외 · 주 지표 순]
   11. Lasso          [그룹 외 · 주 지표 순]
======================================================================

,Rank,Group,Model,R2,MAE,MSE,RMSE,RMSLE,MAPE,MPE,RMSE_Gap
name,,,,,,,,,,,
SVR,1,Contender,SVR,0.787,0.190,0.070,0.265,0.020,1.574,0.012,0.000
CatBoostRegressor,2,Contender,CatBoostRegressor,0.782,0.195,0.072,0.267,0.021,1.619,-0.047,0.010
LGBMRegressor,3,Contender,LGBMRegressor,0.779,0.197,0.073,0.270,0.021,1.639,-0.051,0.019
RandomForestRegressor,4,Contender,RandomForestRegressor,0.774,0.198,0.074,0.272,0.021,1.641,-0.054,0.029
XGBRegressor,5,Outside,XGBRegressor,0.765,0.202,0.077,0.278,0.021,1.681,-0.053,0.051
KNeighborsRegressor,6,Outside,KNeighborsRegressor,0.759,0.203,0.079,0.282,0.022,1.682,-0.004,0.064
LinearRegression,7,Outside,LinearRegression,0.713,0.233,0.094,0.307,0.024,1.935,-0.087,0.160
Ridge,8,Outside,Ridge,0.713,0.233,0.094,0.307,0.024,1.935,-0.087,0.160
DecisionTreeRegressor,9,Outside,DecisionTreeRegressor,0.592,0.266,0.134,0.366,0.028,2.213,-0.007,0.383
ElasticNet,10,Outside,ElasticNet,-0.000,0.463,0.329,0.574,0.044,3.864,-0.273,1.166
Lasso,11,Outside,Lasso,-0.000,0.463,0.329,0.574,0.044,3.864,-0.273,1.166

## #08. 하이퍼파라미터 튜닝

### 1. LinearRegressor

In [25]:
# 튜닝 결과가 저장될 위치
output_dir = f"{workdir}_tuned"

In [26]:
%%time

# LinearRegression 은 규제 항이 없어 성능을 조절할 하이퍼파라미터가 사실상 없다.
# 아래 두 옵션이 가질 수 있는 값의 전부라, 이 그리드가 곧 전체 탐색 범위다.
# 즉 "튜닝으로 좋아지지 않는 모델"을 확인하는 것이 이 셀의 목적이다.
param_grid = {
    "model__fit_intercept": [True, False],   # 절편 사용 여부
    "model__positive": [True, False]         # 계수를 양수로 제한할지 여부
}

# 베이스모델 로드
model = my_ml.load_model(f"{workdir}/linear.pkl")

gs = GridSearchCV(estimator=model, param_grid=param_grid,
    cv=5, scoring="neg_root_mean_squared_error", n_jobs=-1)

# 탐색을 실제로 수행한다. 이 호출이 있어야 best_estimator_ 가 만들어지고,
# 이후 예측·성능비교가 가능해진다.
gs.fit(x_train, y_train)

# 튜닝이 완료된 객체에게 모델이름을 부여한다.
gs.name_ = f"{model.name_}_tuned"

# 튜닝된 모델을 저장한다.
my_ml.save_model(gs, f"{output_dir}/linear.pkl")

# 성능 평가
display(my_ml.reg_score(gs, x_test, y_test))

gs

                    R2   MAE   MSE  RMSE  RMSLE  MAPE    MPE
Model
LinearRegression 0.713 0.233 0.094 0.307  0.024 1.935 -0.087

CPU times: user 42.6 ms, sys: 14 ms, total: 56.6 ms
Wall time: 4.15 s

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(n_jobs=-1,
                                                          remainder='passthrough',
                                                          transformers=[('num',
                                                                         Pipeline(steps=[('vif_selector',
                                                                                          VIFSelector())]),
                                                                         ['housing_median_age',
                                                                          'rooms_per_person',
                                                                          'rooms_per_household',
                                                                          'bedrooms_per_room',
                                                                          'population_per_household',
                                                                          'income_per_person']),
                                                                        ('cat',
                                                                         Pipeline(steps=[('onehot',
                                                                                          OneHotEncoder(drop='first',
                                                                                                        handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         ['is_age_capped',
                                                                          'is_income_capped',
                                                                          'ocean_area',
                                                                          'special_cluster'])],
                                                          verbose_feature_names_out=False)),
                                       ('model', LinearRegression())]),
             n_jobs=-1,
             param_grid={'model__fit_intercept': [True, False],
                         'model__positive': [True, False]},
             scoring='neg_root_mean_squared_error')

### 2. Ridge

In [27]:
%%time

# [실제 탐색용] 20개 조합
# param_grid = {
#     "model__alpha": [0.01, 0.1, 1.0, 10.0, 100.0],
#     "model__solver": ["auto", "svd", "cholesky", "lsqr"]
# }

# [수업용] 8개 조합. alpha 가 클수록 계수를 0 쪽으로 강하게 눌러 분산을 줄인다.
param_grid = {
    "model__alpha": [0.1, 1.0, 10.0, 100.0],   # 규제 강도
    "model__solver": ["auto", "lsqr"]          # 최적화 알고리즘
}

# 베이스모델 로드
model = my_ml.load_model(f"{workdir}/ridge.pkl")

gs = GridSearchCV(estimator=model, param_grid=param_grid,
    cv=5, scoring="neg_root_mean_squared_error", n_jobs=-1)

# 탐색을 실제로 수행한다. 이 호출이 있어야 best_estimator_ 가 만들어지고,
# 이후 예측·성능비교가 가능해진다.
gs.fit(x_train, y_train)

# 튜닝이 완료된 객체에게 모델이름을 부여한다.
gs.name_ = f"{model.name_}_tuned"

# 튜닝된 모델을 저장한다.
my_ml.save_model(gs, f"{output_dir}/ridge.pkl")

# 성능 평가
display(my_ml.reg_score(gs, x_test, y_test))

gs

         R2   MAE   MSE  RMSE  RMSLE  MAPE    MPE
Model
Ridge 0.713 0.233 0.094 0.307  0.024 1.935 -0.087

CPU times: user 69 ms, sys: 24 ms, total: 93 ms
Wall time: 2.12 s

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(n_jobs=-1,
                                                          remainder='passthrough',
                                                          transformers=[('num',
                                                                         Pipeline(steps=[('vif_selector',
                                                                                          VIFSelector()),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['housing_median_age',
                                                                          'rooms_per_person',
                                                                          'rooms_per_household',
                                                                          'bedrooms_per_room',
                                                                          'population_per_household',
                                                                          'income_per_person']),
                                                                        ('cat',
                                                                         P...hot',
                                                                                          OneHotEncoder(drop='first',
                                                                                                        handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         ['is_age_capped',
                                                                          'is_income_capped',
                                                                          'ocean_area',
                                                                          'special_cluster'])],
                                                          verbose_feature_names_out=False)),
                                       ('model', Ridge(random_state=3217))]),
             n_jobs=-1,
             param_grid={'model__alpha': [0.1, 1.0, 10.0, 100.0],
                         'model__solver': ['auto', 'lsqr']},
             scoring='neg_root_mean_squared_error')

### 3. Lasso

In [28]:
%%time

# [실제 탐색용] 15개 조합
# param_grid = {
#     "model__alpha": [0.0001, 0.001, 0.01, 0.1, 1.0],
#     "model__max_iter": [1000, 5000, 10000]
# }

# 베이스모델 로드
model = my_ml.load_model(f"{workdir}/lasso.pkl")

# [수업용] 8개 조합. 기본값 alpha=1.0 은 이 데이터의 타깃 편차(약 0.57)에 비해 너무 강해
# 모든 계수가 0 이 되어 버린다. 작은 alpha 를 넣어야 모델이 살아난다.
param_grid = {
    "model__alpha": [0.0001, 0.001, 0.01, 0.1],   # 규제 강도 (L1)
    "model__max_iter": [1000, 5000]               # 좌표하강 반복 횟수
}

gs = GridSearchCV(estimator=model, param_grid=param_grid,
    cv=5, scoring="neg_root_mean_squared_error", n_jobs=-1)

# 탐색을 실제로 수행한다. 이 호출이 있어야 best_estimator_ 가 만들어지고,
# 이후 예측·성능비교가 가능해진다.
gs.fit(x_train, y_train)

# 튜닝이 완료된 객체에게 모델이름을 부여한다.
gs.name_ = f"{model.name_}_tuned"

# 튜닝된 모델을 저장한다.
my_ml.save_model(gs, f"{output_dir}/lasso.pkl")

# 성능 평가
display(my_ml.reg_score(gs, x_test, y_test))

gs

         R2   MAE   MSE  RMSE  RMSLE  MAPE    MPE
Model
Lasso 0.713 0.233 0.094 0.307  0.024 1.935 -0.087

CPU times: user 68.5 ms, sys: 21.7 ms, total: 90.2 ms
Wall time: 242 ms

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(n_jobs=-1,
                                                          remainder='passthrough',
                                                          transformers=[('num',
                                                                         Pipeline(steps=[('vif_selector',
                                                                                          VIFSelector()),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['housing_median_age',
                                                                          'rooms_per_person',
                                                                          'rooms_per_household',
                                                                          'bedrooms_per_room',
                                                                          'population_per_household',
                                                                          'income_per_person']),
                                                                        ('cat',
                                                                         P...ot',
                                                                                          OneHotEncoder(drop='first',
                                                                                                        handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         ['is_age_capped',
                                                                          'is_income_capped',
                                                                          'ocean_area',
                                                                          'special_cluster'])],
                                                          verbose_feature_names_out=False)),
                                       ('model', Lasso(random_state=3217))]),
             n_jobs=-1,
             param_grid={'model__alpha': [0.0001, 0.001, 0.01, 0.1],
                         'model__max_iter': [1000, 5000]},
             scoring='neg_root_mean_squared_error')

### 4. ElasticNet

In [29]:
%%time

# [실제 탐색용] 20개 조합
# param_grid = {
#     "model__alpha": [0.0001, 0.001, 0.01, 0.1, 1.0],
#     "model__l1_ratio": [0.1, 0.3, 0.5, 0.9]
# }

# [수업용] 8개 조합. l1_ratio 는 L1(Lasso)과 L2(Ridge)의 혼합 비율로,
# 1 에 가까울수록 Lasso, 0 에 가까울수록 Ridge 처럼 동작한다.
param_grid = {
    "model__alpha": [0.0001, 0.001, 0.01, 0.1],   # 규제 강도
    "model__l1_ratio": [0.2, 0.8]                 # L1 규제의 비중
}

# 베이스모델 로드
model = my_ml.load_model(f"{workdir}/elasticnet.pkl")

gs = GridSearchCV(estimator=model, param_grid=param_grid,
    cv=5, scoring="neg_root_mean_squared_error", n_jobs=-1)

# 탐색을 실제로 수행한다. 이 호출이 있어야 best_estimator_ 가 만들어지고,
# 이후 예측·성능비교가 가능해진다.
gs.fit(x_train, y_train)

# 튜닝이 완료된 객체에게 모델이름을 부여한다.
gs.name_ = f"{model.name_}_tuned"

# 튜닝된 모델을 저장한다.
my_ml.save_model(gs, f"{output_dir}/elasticnet.pkl")

# 성능 평가
display(my_ml.reg_score(gs, x_test, y_test))

gs

              R2   MAE   MSE  RMSE  RMSLE  MAPE    MPE
Model
ElasticNet 0.713 0.233 0.094 0.307  0.024 1.935 -0.087

CPU times: user 80.6 ms, sys: 25 ms, total: 106 ms
Wall time: 265 ms

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(n_jobs=-1,
                                                          remainder='passthrough',
                                                          transformers=[('num',
                                                                         Pipeline(steps=[('vif_selector',
                                                                                          VIFSelector()),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['housing_median_age',
                                                                          'rooms_per_person',
                                                                          'rooms_per_household',
                                                                          'bedrooms_per_room',
                                                                          'population_per_household',
                                                                          'income_per_person']),
                                                                        ('cat',
                                                                         P...,
                                                                                          OneHotEncoder(drop='first',
                                                                                                        handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         ['is_age_capped',
                                                                          'is_income_capped',
                                                                          'ocean_area',
                                                                          'special_cluster'])],
                                                          verbose_feature_names_out=False)),
                                       ('model',
                                        ElasticNet(random_state=3217))]),
             n_jobs=-1,
             param_grid={'model__alpha': [0.0001, 0.001, 0.01, 0.1],
                         'model__l1_ratio': [0.2, 0.8]},
             scoring='neg_root_mean_squared_error')

### 5. KNN

In [30]:
%%time

# [실제 탐색용] 24개 조합
# param_grid = {
#     "model__n_neighbors": [3, 5, 10, 20, 30, 50],
#     "model__weights": ["uniform", "distance"],
#     "model__p": [1, 2]
# }

# [수업용] 8개 조합. 이웃 수가 적으면 과대적합, 많으면 과소적합 쪽으로 기운다.
param_grid = {
    "model__n_neighbors": [5, 10, 20, 30],       # 참조할 이웃 수
    "model__weights": ["uniform", "distance"]    # 거리에 따른 가중 방식
}

# 베이스모델 로드
model = my_ml.load_model(f"{workdir}/knn.pkl")

gs = GridSearchCV(estimator=model, param_grid=param_grid,
    cv=5, scoring="neg_root_mean_squared_error", n_jobs=-1)

# 탐색을 실제로 수행한다. 이 호출이 있어야 best_estimator_ 가 만들어지고,
# 이후 예측·성능비교가 가능해진다.
gs.fit(x_train, y_train)

# 튜닝이 완료된 객체에게 모델이름을 부여한다.
gs.name_ = f"{model.name_}_tuned"

# 튜닝된 모델을 저장한다.
my_ml.save_model(gs, f"{output_dir}/knn.pkl")

# 성능 평가
display(my_ml.reg_score(gs, x_test, y_test))

gs

                       R2   MAE   MSE  RMSE  RMSLE  MAPE    MPE
Model
KNeighborsRegressor 0.775 0.197 0.074 0.272  0.021 1.633 -0.038

CPU times: user 1.23 s, sys: 34.5 ms, total: 1.27 s
Wall time: 750 ms

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(n_jobs=-1,
                                                          remainder='passthrough',
                                                          transformers=[('num',
                                                                         Pipeline(steps=[('vif_selector',
                                                                                          VIFSelector()),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['housing_median_age',
                                                                          'rooms_per_person',
                                                                          'rooms_per_household',
                                                                          'bedrooms_per_room',
                                                                          'population_per_household',
                                                                          'income_per_person']),
                                                                        ('cat',
                                                                         P...
                                                                                          OneHotEncoder(drop='first',
                                                                                                        handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         ['is_age_capped',
                                                                          'is_income_capped',
                                                                          'ocean_area',
                                                                          'special_cluster'])],
                                                          verbose_feature_names_out=False)),
                                       ('model',
                                        KNeighborsRegressor(n_jobs=-1))]),
             n_jobs=-1,
             param_grid={'model__n_neighbors': [5, 10, 20, 30],
                         'model__weights': ['uniform', 'distance']},
             scoring='neg_root_mean_squared_error')

### 6. Support Vector Machine

In [31]:
%%time

# [실제 탐색용] 27개 조합 --> 표본 수의 제곱에 비례해 학습 시간이 늘어나므로 매우 오래 걸린다
# param_grid = {
#     "model__C": [0.1, 1.0, 10.0],
#     "model__gamma": ["scale", 0.01, 0.1],
#     "model__epsilon": [0.05, 0.1, 0.2]
# }

# [수업용] SVR 은 이 노트북에서 가장 느린 모델이므로 튜닝 시간을 줄이기 위해 조합을 3개로 축소한다.
param_grid = {
    "model__C": [1.0],           # 오차 허용에 대한 벌점 (클수록 훈련 데이터에 밀착)
    "model__gamma": [0.01],      # RBF 커널의 영향 반경
    "model__epsilon": [0.1]      # 오차 허용 범위 (클수록 훈련 데이터에 밀착)
}

# 베이스모델 로드
model = my_ml.load_model(f"{workdir}/svr.pkl")

gs = GridSearchCV(estimator=model, param_grid=param_grid,
    cv=5, scoring="neg_root_mean_squared_error", n_jobs=-1)

# 탐색을 실제로 수행한다. 이 호출이 있어야 best_estimator_ 가 만들어지고,
# 이후 예측·성능비교가 가능해진다.
gs.fit(x_train, y_train)

# 튜닝이 완료된 객체에게 모델이름을 부여한다.
gs.name_ = f"{model.name_}_tuned"

# 튜닝된 모델을 저장한다.
my_ml.save_model(gs, f"{output_dir}/svr.pkl")

# 성능 평가
display(my_ml.reg_score(gs, x_test, y_test))

gs

         R2   MAE   MSE  RMSE  RMSLE  MAPE   MPE
Model
SVR   0.755 0.209 0.081 0.284  0.022 1.729 0.046

CPU times: user 4.52 s, sys: 351 ms, total: 4.87 s
Wall time: 9.03 s

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(n_jobs=-1,
                                                          remainder='passthrough',
                                                          transformers=[('num',
                                                                         Pipeline(steps=[('vif_selector',
                                                                                          VIFSelector()),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['housing_median_age',
                                                                          'rooms_per_person',
                                                                          'rooms_per_household',
                                                                          'bedrooms_per_room',
                                                                          'population_per_household',
                                                                          'income_per_person']),
                                                                        ('cat',
                                                                         Pipeline(steps=[('onehot',
                                                                                          OneHotEncoder(drop='first',
                                                                                                        handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         ['is_age_capped',
                                                                          'is_income_capped',
                                                                          'ocean_area',
                                                                          'special_cluster'])],
                                                          verbose_feature_names_out=False)),
                                       ('model', SVR())]),
             n_jobs=-1,
             param_grid={'model__C': [1.0], 'model__epsilon': [0.1],
                         'model__gamma': [0.01]},
             scoring='neg_root_mean_squared_error')

### 7. Decision Tree

In [32]:
%%time

# [실제 탐색용] 24개 조합
# param_grid = {
#     "model__max_depth": [4, 6, 10, 14, 20, None],
#     "model__min_samples_leaf": [1, 5, 10, 20]
# }

# [수업용] 8개 조합. 기본값(max_depth=None)은 잎이 순수해질 때까지 쪼개
# 훈련 R2 가 1.0 이 되는 전형적인 과대적합 상태다. 깊이를 제한해 이를 완화한다.
param_grid = {
    "model__max_depth": [6, 10, 14, None],   # 트리의 최대 깊이
    "model__min_samples_leaf": [1, 10]       # 잎 노드가 가져야 할 최소 표본 수
}

# 베이스모델 로드
model = my_ml.load_model(f"{workdir}/dtree.pkl")

gs = GridSearchCV(estimator=model, param_grid=param_grid,
    cv=5, scoring="neg_root_mean_squared_error", n_jobs=-1)

# 탐색을 실제로 수행한다. 이 호출이 있어야 best_estimator_ 가 만들어지고,
# 이후 예측·성능비교가 가능해진다.
gs.fit(x_train, y_train)

# 튜닝이 완료된 객체에게 모델이름을 부여한다.
gs.name_ = f"{model.name_}_tuned"

# 튜닝된 모델을 저장한다.
my_ml.save_model(gs, f"{output_dir}/dtree.pkl")

# 성능 평가
display(my_ml.reg_score(gs, x_test, y_test))

gs

                         R2   MAE   MSE  RMSE  RMSLE  MAPE    MPE
Model
DecisionTreeRegressor 0.749 0.210 0.083 0.287  0.022 1.743 -0.045

CPU times: user 117 ms, sys: 34.8 ms, total: 152 ms
Wall time: 2.36 s

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(n_jobs=-1,
                                                          remainder='passthrough',
                                                          transformers=[('num',
                                                                         Pipeline(steps=[('vif_selector',
                                                                                          VIFSelector())]),
                                                                         ['housing_median_age',
                                                                          'rooms_per_person',
                                                                          'rooms_per_household',
                                                                          'bedrooms_per_room',
                                                                          'population_per_household',
                                                                          'income_per_person']),
                                                                        ('cat',
                                                                         Pipeline(steps=[('onehot',
                                                                                          OneHotEncoder(handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         ['is_age_capped',
                                                                          'is_income_capped',
                                                                          'ocean_area',
                                                                          'special_cluster'])],
                                                          verbose_feature_names_out=False)),
                                       ('model',
                                        DecisionTreeRegressor(random_state=3217))]),
             n_jobs=-1,
             param_grid={'model__max_depth': [6, 10, 14, None],
                         'model__min_samples_leaf': [1, 10]},
             scoring='neg_root_mean_squared_error')

### 8. Random Forest

In [33]:
%%time

# [실제 탐색용] 18개 조합
# param_grid = {
#     "model__n_estimators": [100, 300, 500],
#     "model__max_depth": [10, 20, None],
#     "model__min_samples_leaf": [1, 5]
# }

# [수업용] 트리를 n_estimators 개 만큼 학습하므로 조합 하나가 비싸다.
# 4개 조합으로 줄였다 (SVR 과 함께 이 노트북에서 오래 걸리는 축에 속한다).
param_grid = {
    "model__n_estimators": [100, 300],     # 숲을 이루는 트리 개수
    "model__min_samples_leaf": [1, 5]      # 잎 노드가 가져야 할 최소 표본 수
}

# 베이스모델 로드
model = my_ml.load_model(f"{workdir}/rf.pkl")

gs = GridSearchCV(estimator=model, param_grid=param_grid,
    cv=5, scoring="neg_root_mean_squared_error", n_jobs=-1)

# 탐색을 실제로 수행한다. 이 호출이 있어야 best_estimator_ 가 만들어지고,
# 이후 예측·성능비교가 가능해진다.
gs.fit(x_train, y_train)

# 튜닝이 완료된 객체에게 모델이름을 부여한다.
gs.name_ = f"{model.name_}_tuned"

# 튜닝된 모델을 저장한다.
my_ml.save_model(gs, f"{output_dir}/rf.pkl")

# 성능 평가
display(my_ml.reg_score(gs, x_test, y_test))

gs

                         R2   MAE   MSE  RMSE  RMSLE  MAPE    MPE
Model
RandomForestRegressor 0.777 0.196 0.073 0.271  0.021 1.630 -0.061

CPU times: user 17.6 s, sys: 359 ms, total: 18 s
Wall time: 9.52 s

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(n_jobs=-1,
                                                          remainder='passthrough',
                                                          transformers=[('num',
                                                                         Pipeline(steps=[('vif_selector',
                                                                                          VIFSelector())]),
                                                                         ['housing_median_age',
                                                                          'rooms_per_person',
                                                                          'rooms_per_household',
                                                                          'bedrooms_per_room',
                                                                          'population_per_household',
                                                                          'income_per_person']),
                                                                        ('cat',
                                                                         Pipeline(steps=[('onehot',
                                                                                          OneHotEncoder(handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         ['is_age_capped',
                                                                          'is_income_capped',
                                                                          'ocean_area',
                                                                          'special_cluster'])],
                                                          verbose_feature_names_out=False)),
                                       ('model',
                                        RandomForestRegressor(n_jobs=-1,
                                                              random_state=3217))]),
             n_jobs=-1,
             param_grid={'model__min_samples_leaf': [1, 5],
                         'model__n_estimators': [100, 300]},
             scoring='neg_root_mean_squared_error')

### 9. XGBoost

In [34]:
%%time

# [실제 탐색용] 27개 조합
# param_grid = {
#     "model__n_estimators": [300, 600, 1000],
#     "model__max_depth": [3, 4, 6],
#     "model__learning_rate": [0.03, 0.05, 0.1]
# }

# [수업용] 8개 조합. learning_rate 를 낮추면 n_estimators 를 늘려야 하므로
# 두 값은 짝지어 움직인다는 점을 확인한다.
param_grid = {
    "model__n_estimators": [300, 600],        # 부스팅 라운드 수
    "model__max_depth": [4, 6],               # 트리 깊이
    "model__learning_rate": [0.05, 0.1]       # 각 트리의 반영 비율
}

# 베이스모델 로드
model = my_ml.load_model(f"{workdir}/xgb.pkl")

gs = GridSearchCV(estimator=model, param_grid=param_grid,
    cv=5, scoring="neg_root_mean_squared_error", n_jobs=-1)

# 탐색을 실제로 수행한다. 이 호출이 있어야 best_estimator_ 가 만들어지고,
# 이후 예측·성능비교가 가능해진다.
gs.fit(x_train, y_train)

# 튜닝이 완료된 객체에게 모델이름을 부여한다.
gs.name_ = f"{model.name_}_tuned"

# 튜닝된 모델을 저장한다.
my_ml.save_model(gs, f"{output_dir}/xgb.pkl")

# 성능 평가
display(my_ml.reg_score(gs, x_test, y_test))

gs

                R2   MAE   MSE  RMSE  RMSLE  MAPE    MPE
Model
XGBRegressor 0.779 0.196 0.073 0.269  0.021 1.632 -0.051

CPU times: user 1.28 s, sys: 10.8 s, total: 12 s
Wall time: 4.09 s

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(n_jobs=-1,
                                                          remainder='passthrough',
                                                          transformers=[('num',
                                                                         Pipeline(steps=[('vif_selector',
                                                                                          VIFSelector())]),
                                                                         ['housing_median_age',
                                                                          'rooms_per_person',
                                                                          'rooms_per_household',
                                                                          'bedrooms_per_room',
                                                                          'population_per_household',
                                                                          'income_per_person']),
                                                                        ('cat',
                                                                         Pipeline(steps=[('onehot',
                                                                                          One...
                                                     max_cat_to_onehot=None,
                                                     max_delta_step=None,
                                                     max_depth=None,
                                                     max_leaves=None,
                                                     min_child_weight=None,
                                                     missing=nan,
                                                     monotone_constraints=None,
                                                     multi_strategy=None,
                                                     n_estimators=None,
                                                     n_jobs=-1,
                                                     num_parallel_tree=None, ...))]),
             n_jobs=-1,
             param_grid={'model__learning_rate': [0.05, 0.1],
                         'model__max_depth': [4, 6],
                         'model__n_estimators': [300, 600]},
             scoring='neg_root_mean_squared_error')

### 10.  LightGBM

In [35]:
%%time

# [실제 탐색용] 27개 조합
# param_grid = {
#     "model__n_estimators": [300, 600, 1000],
#     "model__num_leaves": [15, 31, 63],
#     "model__learning_rate": [0.03, 0.05, 0.1]
# }

# [수업용] 8개 조합. LightGBM 은 깊이 대신 잎 개수(num_leaves)로 복잡도를 조절한다.
param_grid = {
    "model__n_estimators": [300, 600],        # 부스팅 라운드 수
    "model__num_leaves": [31, 63],            # 트리 하나가 가질 잎 개수
    "model__learning_rate": [0.05, 0.1]       # 각 트리의 반영 비율
}

# 베이스모델 로드
model = my_ml.load_model(f"{workdir}/lgbm.pkl")

gs = GridSearchCV(estimator=model, param_grid=param_grid,
    cv=5, scoring="neg_root_mean_squared_error", n_jobs=-1)

# 탐색을 실제로 수행한다. 이 호출이 있어야 best_estimator_ 가 만들어지고,
# 이후 예측·성능비교가 가능해진다.
gs.fit(x_train, y_train)

# 튜닝이 완료된 객체에게 모델이름을 부여한다.
gs.name_ = f"{model.name_}_tuned"

# 튜닝된 모델을 저장한다.
my_ml.save_model(gs, f"{output_dir}/lgbm.pkl")

# 성능 평가
display(my_ml.reg_score(gs, x_test, y_test))

gs

                 R2   MAE   MSE  RMSE  RMSLE  MAPE    MPE
Model
LGBMRegressor 0.779 0.197 0.073 0.269  0.021 1.636 -0.050

CPU times: user 3.52 s, sys: 40 s, total: 43.5 s
Wall time: 7min 23s

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(n_jobs=-1,
                                                          remainder='passthrough',
                                                          transformers=[('num',
                                                                         Pipeline(steps=[('vif_selector',
                                                                                          VIFSelector())]),
                                                                         ['housing_median_age',
                                                                          'rooms_per_person',
                                                                          'rooms_per_household',
                                                                          'bedrooms_per_room',
                                                                          'population_per_household',
                                                                          'income_per_person']),
                                                                        ('cat',
                                                                         Pipeline(steps=[('onehot',
                                                                                          One...,
                                                                                                        sparse_output=False))]),
                                                                         ['is_age_capped',
                                                                          'is_income_capped',
                                                                          'ocean_area',
                                                                          'special_cluster'])],
                                                          verbose_feature_names_out=False)),
                                       ('model',
                                        LGBMRegressor(n_jobs=-1,
                                                      random_state=3217,
                                                      verbose=-1))]),
             n_jobs=-1,
             param_grid={'model__learning_rate': [0.05, 0.1],
                         'model__n_estimators': [300, 600],
                         'model__num_leaves': [31, 63]},
             scoring='neg_root_mean_squared_error')

### 11. CatBoost

In [36]:
%%time

# [실제 탐색용] 36개 조합 x 5-fold = CatBoost 학습 180회 --> 수십 분 이상 소요
# param_grid = {
#     "model__iterations": [500, 1000, 2000],
#     "model__depth": [4, 6, 8, 10],
#     "model__learning_rate": [0.03, 0.05, 0.1]
# }

# [수업용] 각 하이퍼파라미터를 일부만 두어 조합을 축소한다.
# 수업 시간에 탐색 과정을 직접 돌려보기 위한 것이므로, 실제 분석에서는 위 범위를 쓴다.
param_grid = {
    "model__iterations": [500, 1000],
    "model__depth": [4, 6, 8],
    "model__learning_rate": [0.03, 0.05, 0.1]
}

# 베이스모델 로드
model = my_ml.load_model(f"{workdir}/catboost.pkl")

# 하이퍼파라미터 탐색을 위한 GridSearchCV 객체를 생성
gs = GridSearchCV(estimator=model, param_grid=param_grid,
    cv=5, scoring="neg_root_mean_squared_error", n_jobs=-1)

# 탐색을 실제로 수행한다.
# CatBoost 는 범주형 컬럼 목록을 fit 시점에 받으므로 여기서도 함께 넘겨야 한다.
gs.fit(x_train, y_train,
       model__cat_features=my_qtcheck.get_categorical_column_names(x_train))

# 튜닝이 완료된 객체에게 모델이름을 부여한다.
gs.name_ = f"{model.name_}_tuned"

# 튜닝이 완료된 모델을 저장한다.
my_ml.save_model(gs, f"{output_dir}/catboost.pkl")

# 성능 평가
display(my_ml.reg_score(gs, x_test, y_test))

/Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

                     R2   MAE   MSE  RMSE  RMSLE  MAPE    MPE
Model
CatBoostRegressor 0.786 0.193 0.070 0.265  0.020 1.603 -0.051

CPU times: user 40.8 s, sys: 48.7 s, total: 1min 29s
Wall time: 53.5 s

## #09. 최고 성능 모델 선정

### 1. 학습 모델 파일 목록

In [37]:
# 작업폴더 내의 모든 pkl 파일 목록 확인
model_pickles = gl.glob(f"{output_dir}/*.pkl")
print(model_pickles)

['ml_models/20260820_075728_tuned/catboost.pkl', 'ml_models/20260820_075728_tuned/elasticnet.pkl', 'ml_models/20260820_075728_tuned/rf.pkl', 'ml_models/20260820_075728_tuned/knn.pkl', 'ml_models/20260820_075728_tuned/lasso.pkl', 'ml_models/20260820_075728_tuned/ridge.pkl', 'ml_models/20260820_075728_tuned/dtree.pkl', 'ml_models/20260820_075728_tuned/xgb.pkl', 'ml_models/20260820_075728_tuned/linear.pkl', 'ml_models/20260820_075728_tuned/svr.pkl', 'ml_models/20260820_075728_tuned/lgbm.pkl']

### 2. 학습 모델 불러오기

In [38]:
models = {}

for p in model_pickles:
    # 파일 목록에서 파일명만 분리
    model_name = p.split(".")[0]

    # 모델 로드
    model = my_ml.load_model(p)

    # 모델명과 모델 객체를 딕셔너리에 저장
    models[model.name_] = model

for name, model in models.items():
    print(f"- {name}: {type(model)}")

- CatBoostRegressor_tuned: <class 'sklearn.model_selection._search.GridSearchCV'>
- ElasticNet_tuned: <class 'sklearn.model_selection._search.GridSearchCV'>
- RandomForestRegressor_tuned: <class 'sklearn.model_selection._search.GridSearchCV'>
- KNeighborsRegressor_tuned: <class 'sklearn.model_selection._search.GridSearchCV'>
- Lasso_tuned: <class 'sklearn.model_selection._search.GridSearchCV'>
- Ridge_tuned: <class 'sklearn.model_selection._search.GridSearchCV'>
- DecisionTreeRegressor_tuned: <class 'sklearn.model_selection._search.GridSearchCV'>
- XGBRegressor_tuned: <class 'sklearn.model_selection._search.GridSearchCV'>
- LinearRegression_tuned: <class 'sklearn.model_selection._search.GridSearchCV'>
- SVR_tuned: <class 'sklearn.model_selection._search.GridSearchCV'>
- LGBMRegressor_tuned: <class 'sklearn.model_selection._search.GridSearchCV'>

### 3. 모델간 성능평가 비교

In [39]:
my_ml.reg_compare_models(models,               # 모델 객체들을 담은 딕셔너리
                         x_test,               # 검증 데이터의 독립 변수
                         y_test,               # 검증 데이터의 종속 변수
                         primary="RMSE",       # 주 지표
                         aux=["MAE", "R2"])    # 보조 지표

======================================================================
◆ Score Table Ranking : primary='RMSE', aux=['MAE', 'R2']
======================================================================

▲ step1: 주 지표(RMSE) 기준 정렬 — 낮을수록 좋음 (ASC)
    1. CatBoostRegressor_tuned RMSE  =            0.265
    2. LGBMRegressor_tuned RMSE  =            0.269
    3. XGBRegressor_tuned RMSE  =            0.269
    4. RandomForestRegressor_tuned RMSE  =            0.271
    5. KNeighborsRegressor_tuned RMSE  =            0.272
    6. SVR_tuned      RMSE  =            0.284
    7. DecisionTreeRegressor_tuned RMSE  =            0.287
    8. LinearRegression_tuned RMSE  =            0.307
    9. Ridge_tuned    RMSE  =            0.307
   10. ElasticNet_tuned RMSE  =            0.307
   11. Lasso_tuned    RMSE  =            0.307

▲ step2: 근소 격차 그룹 묶기 (1등의 5% 이내)
   - 1등 RMSE   : 0.265
   - 허용 범위    : RMSE ≤ 0.278
   - 근소 격차 그룹 (5) : ['CatBoostRegressor_tuned', 'LGBMRegressor_tuned', 'XGBRegressor_tuned', 'RandomForestRegressor_tuned', 'KNeighborsRegressor_tuned']
   - 그룹 외부     (6) : ['SVR_tuned', 'DecisionTreeRegressor_tuned', 'LinearRegression_tuned', 'Ridge_tuned', 'ElasticNet_tuned', 'Lasso_tuned']

▲ step3: 보조 지표 결정적 결함 점검 (근소 격차 그룹 내부)
   - 그룹 1등 점수 / 결함 임계치:
       · MAE    best=     0.193   결함조건: row > 0.212  (1등 × 1.10)
       · R2     best=     0.786   결함조건: row < 0.736  (1등 − 0.05)
   - 모델별 결함:
       · CatBoostRegressor_tuned 0개 (결함 없음)
       · LGBMRegressor_tuned 0개 (결함 없음)
       · XGBRegressor_tuned 0개 (결함 없음)
       · RandomForestRegressor_tuned 0개 (결함 없음)
       · KNeighborsRegressor_tuned 0개 (결함 없음)

▲ step4: 최종 Rank
    1. CatBoostRegressor_tuned [그룹 내]
    2. LGBMRegressor_tuned [그룹 내]
    3. XGBRegressor_tuned [그룹 내]
    4. RandomForestRegressor_tuned [그룹 내]
    5. KNeighborsRegressor_tuned [그룹 내]
    6. SVR_tuned      [그룹 외 · 주 지표 순]
    7. DecisionTreeRegressor_tuned [그룹 외 · 주 지표 순]
    8. LinearRegression_tuned [그룹 외 · 주 지표 순]
    9. Ridge_tuned    [그룹 외 · 주 지표 순]
   10. ElasticNet_tuned [그룹 외 · 주 지표 순]
   11. Lasso_tuned    [그룹 외 · 주 지표 순]
======================================================================

,Rank,Group,Model,R2,MAE,MSE,RMSE,RMSLE,MAPE,MPE,RMSE_Gap
name,,,,,,,,,,,
CatBoostRegressor_tuned,1,Contender,CatBoostRegressor,0.786,0.193,0.070,0.265,0.020,1.603,-0.051,0.000
LGBMRegressor_tuned,2,Contender,LGBMRegressor,0.779,0.197,0.073,0.269,0.021,1.636,-0.050,0.016
XGBRegressor_tuned,3,Contender,XGBRegressor,0.779,0.196,0.073,0.269,0.021,1.632,-0.051,0.016
RandomForestRegressor_tuned,4,Contender,RandomForestRegressor,0.777,0.196,0.073,0.271,0.021,1.630,-0.061,0.021
KNeighborsRegressor_tuned,5,Contender,KNeighborsRegressor,0.775,0.197,0.074,0.272,0.021,1.633,-0.038,0.025
SVR_tuned,6,Outside,SVR,0.755,0.209,0.081,0.284,0.022,1.729,0.046,0.071
DecisionTreeRegressor_tuned,7,Outside,DecisionTreeRegressor,0.749,0.210,0.083,0.287,0.022,1.743,-0.045,0.084
LinearRegression_tuned,8,Outside,LinearRegression,0.713,0.233,0.094,0.307,0.024,1.935,-0.087,0.159
Ridge_tuned,9,Outside,Ridge,0.713,0.233,0.094,0.307,0.024,1.935,-0.087,0.159
ElasticNet_tuned,10,Outside,ElasticNet,0.713,0.233,0.094,0.307,0.024,1.935,-0.087,0.159
Lasso_tuned,11,Outside,Lasso,0.713,0.233,0.094,0.307,0.024,1.935,-0.087,0.159