# [LAB-03] 4. 데이터 확인하기

## #01. 준비작업

### 1. 라이브러리 설치

In [1]:
!pip install --upgrade jussam

Requirement already satisfied: jussam in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (0.5.17)
Requirement already satisfied: pandas in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from jussam) (3.0.3)
Requirement already satisfied: geopandas in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from jussam) (1.1.3)
Requirement already satisfied: requests in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from jussam) (2.33.1)
Requirement already satisfied: tabulate in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from jussam) (0.10.0)
Requirement already satisfied: numpy>=1.24 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from geopandas->jussam) (2.4.4)
Requirement already satisfied: pyogrio>=0.7.2 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from geopandas->jussam) (0.12.1)
Requirement already satisfied: packaging in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from geopandas->jussam) (26.0)
Requirement already satisfied: pyproj>=3.5.0 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from geopandas->jussam) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from geopandas->jussam) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from pandas->jussam) (2.9.0.post0)
Requirement already satisfied: certifi in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from pyogrio>=0.7.2->geopandas->jussam) (2026.2.25)
Requirement already satisfied: six>=1.5 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas->jussam) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from requests->jussam) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from requests->jussam) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/leekh/.pyenv/versions/3.13.9/lib/python3.13/site-packages (from requests->jussam) (2.6.3)

### 2. 라이브러리 참조

In [2]:
from jussam import load_data

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

### 3. 데이터 가져오기

- 가상의 과목별 점수 데이터 불러오기

In [3]:
origin = load_data('GRADE')
origin

📚 어느 학급의 과목별 점수를 조사한 가상의 데이터

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

## #02. 데이터 구조 확인

### 1. 데이터의 차원과 크기

- NumPy, Series와 동일한 기능

In [4]:
print("차원:", origin.ndim)
print("크기:", origin.shape)

차원: 2
크기: (9, 6)

### 2. 각 변수의 데이터 타입 확인

In [5]:
origin.dtypes

학년    int64
성별      str
국어    int64
영어    int64
수학    int64
과학    int64
dtype: object

### 3. 각 필드별 정보 확인

In [6]:
origin.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: int64(5), str(1)
memory usage: 612.0 bytes

## #03. 데이터 내용 확인

### 1. 특정 열의 데이터 확인

In [7]:
origin['국어']

이름
철수    98
영희    88
민철    92
수현    63
호영    75
영호    80
용식    82
나영    90
석영    91
Name: 국어, dtype: int64

### 2. 특정 "열"의 타입 확인 → Series

In [8]:
type(origin['국어'])

pandas.Series

### 3. 원하는 열만 추출하기

- 대괄호가 이중으로 표기된다.

In [9]:
df2 = origin[['국어', '영어', '수학']]
df2

    국어   영어  수학
이름
철수  98   77  88
영희  88  120  62
민철  92   70  83
수현  63   60  31
호영  75   50  90
영호  80   88  91
용식  82   88  79
나영  90   92  81
석영  91   90  89

## #04. 특정 행 접근

### 1. 인덱스 이름을 기반으로 접근하기

- **loc**: location (이름 기반 접근)

In [10]:
origin.loc['철수']

학년     1
성별    남자
국어    98
영어    77
수학    88
과학    64
Name: 철수, dtype: object

### 2. 특정 행에 대한 데이터 타입 확인

- Series 타입임을 확인할 수 있다.

In [11]:
type(origin.loc['철수'])

pandas.Series

### 3. 인덱스 번호를 기반으로 특정 행에 접근

- **iloc**: 인덱스 번호로 접근 (index-location)

In [12]:
origin.iloc[0]

학년     1
성별    남자
국어    98
영어    77
수학    88
과학    64
Name: 철수, dtype: object

### 4. 인덱스 번호로 접근할 경우 슬라이싱 가능

- `1~4`번째 전까지 행만 가져오기

In [13]:
origin.iloc[1:4]

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71

## #05.  단일 값 확인하기

### 1. **열 → 행** 순서로 접근

In [14]:
origin['국어']['철수']

np.int64(98)

### 2. **행 → 열** 순서로 접근

In [15]:
origin.loc['철수','국어']

np.int64(98)

### 3. 인덱스 번호 기반 데이터 접근

- **행 → 열** 순서로 접근함

In [16]:
# 1번째 행의 2번째 열 데이터
origin.iloc[1, 2]

np.int64(88)

### 4. 인덱스 번호로 접근할 경우 슬라이싱 가능

- 행에 대해서 모든 행 지정, 3번째 열 지정

In [17]:
# 모든 행에서 3번째 열만 가져옴
origin.iloc[:, 3]

이름
철수     77
영희    120
민철     70
수현     60
호영     50
영호     88
용식     88
나영     92
석영     90
Name: 영어, dtype: int64

## #06. 값의 변경

### 1. 단일값 변경

- **행 → 열** 순으로 접근하는 경우만 가능함

In [18]:
origin.loc['철수','국어'] = 100
origin

    학년  성별   국어   영어  수학  과학
이름
철수   1  남자  100   77  88  64
영희   2  여자   88  120  62  72
민철   1  남자   92   70  83  79
수현   3  여자   63   60  31  71
호영   4  남자   75   50  90  88
영호   4  남자   80   88  91  72
용식   2  남자   82   88  79  90
나영   1  여자   90   92  81  95
석영   1  남자   91   90  89  80

### 2. 열 단위 변경

- `replace(before, after)` 메서드를 사용하여 `88`을 `92`로 일괄 변경

In [19]:
origin['영어'] = origin['영어'].replace(88, 92)
origin

    학년  성별   국어   영어  수학  과학
이름
철수   1  남자  100   77  88  64
영희   2  여자   88  120  62  72
민철   1  남자   92   70  83  79
수현   3  여자   63   60  31  71
호영   4  남자   75   50  90  88
영호   4  남자   80   92  91  72
용식   2  남자   82   92  79  90
나영   1  여자   90   92  81  95
석영   1  남자   91   90  89  80

### 3. 조건에 맞는 행을 검색하여 특정 열 변경하기

- Series 객체의 표현식을 사용하여 조건에 맞는 행에 `loc` 프로퍼티로 접근한 후, 값을 변경할 컬럼을 지정한다.

In [20]:
origin.loc[origin['수학'] < 50, '수학'] = 0
origin

    학년  성별   국어   영어  수학  과학
이름
철수   1  남자  100   77  88  64
영희   2  여자   88  120  62  72
민철   1  남자   92   70  83  79
수현   3  여자   63   60   0  71
호영   4  남자   75   50  90  88
영호   4  남자   80   92  91  72
용식   2  남자   82   92  79  90
나영   1  여자   90   92  81  95
석영   1  남자   91   90  89  80

## #07. 데이터 일부만 확인

### 1. 상위 n건 확인

- 파라미터가 없을 경우 5개가 기본값
  - 실제로 다루게 되는 데이터 프레임은 수십만개의 행을 갖고 있을 수 있다.
  - 이 경우 한번에 출력할 수 없기 때문에 데이터의 일부만 출력하여 데이터의 형태를 가늠해야 한다.

In [21]:
origin.head(2)

    학년  성별   국어   영어  수학  과학
이름
철수   1  남자  100   77  88  64
영희   2  여자   88  120  62  72

### 2. 하위 n건 확인

- 파라미터가 없을 경우 5개가 기본값

In [22]:
origin.tail(2)

    학년  성별  국어  영어  수학  과학
이름
나영   1  여자  90  92  81  95
석영   1  남자  91  90  89  80

## #08. 기술 통계량 확인

### 1. 컬럼 단위 확인

- DataFrame의 각 컬럼은 Series 객체이므로 Series의 메서드를 그대로 사용 가능함

In [23]:
print("합계:", origin['국어'].sum())
print("평균:", origin['국어'].mean())
print("최대:", origin['국어'].max())
print("최소:", origin['국어'].min())
print("분산:", origin['국어'].var())
print("표준편차:", origin['국어'].std())
print("중앙값:", origin['국어'].median())
print("1사분위 수:", origin['국어'].quantile(0.25))
print("2사분위 수:", origin['국어'].quantile(0.5))
print("3사분위 수:", origin['국어'].quantile(0.75))

합계: 761
평균: 84.55555555555556
최대: 100
최소: 63
분산: 120.02777777777779
표준편차: 10.955718953029864
중앙값: 88.0
1사분위 수: 80.0
2사분위 수: 88.0
3사분위 수: 91.0

### 2. DataFrame 단위 확인

- 모든 연속형 컬럼에 대해서 일괄 계산한다.
- 계산할 수 없는 형태의 값도 계산되므로 주의가 필요하다.

In [24]:
origin.sum()

학년                    19
성별    남자여자남자여자남자남자남자여자남자
국어                   761
영어                   743
수학                   663
과학                   711
dtype: object

### 3. 컬럼 단위로 모든 기술 통계량 일괄 산출

In [25]:
origin['국어'].describe()

count     9.000
mean     84.556
std      10.956
min      63.000
25%      80.000
50%      88.000
75%      91.000
max     100.000
Name: 국어, dtype: float64

### 4. DataFrame 단위로 일괄 산출

- 연산이 가능한 연속형 변수만 추출해서 적용해야 한다.

In [26]:
# 연산이 가능한 컬럼만 추출
df2 = origin[['국어','영어','수학','과학']]
desc = df2.describe()
desc

           국어      영어     수학     과학
count   9.000   9.000  9.000  9.000
mean   84.556  82.556 73.667 79.000
std    10.956  20.863 29.026 10.283
min    63.000  50.000  0.000 64.000
25%    80.000  70.000 79.000 72.000
50%    88.000  90.000 83.000 79.000
75%    91.000  92.000 89.000 88.000
max   100.000 120.000 91.000 95.000

### 5. 전치 구하기

- 가로와 세로가 바뀐 새로운 데이터프레임을 생성할 수 있다.

In [27]:
t = desc.T
t

    count   mean    std    min    25%    50%    75%     max
국어  9.000 84.556 10.956 63.000 80.000 88.000 91.000 100.000
영어  9.000 82.556 20.863 50.000 70.000 90.000 92.000 120.000
수학  9.000 73.667 29.026  0.000 79.000 83.000 89.000  91.000
과학  9.000 79.000 10.283 64.000 72.000 79.000 88.000  95.000

## #09. 명목형 변수의 기술 통계량 확인

### 1. 빈도수 구하기 → 값의 종류별 수

- 예제 데이터에서 "성별", "학년" 등과 같이 연산을 수행할 수 없는 카테고리 성격의 데이터는 종류별 수량을 구해서 데이터 분포를 파악한다.

In [28]:
origin['성별'].value_counts()

성별
남자    6
여자    3
Name: count, dtype: int64

In [29]:
origin['학년'].value_counts()

학년
1    4
2    2
4    2
3    1
Name: count, dtype: int64

### 2. 명목형 변수 기술 통계량

- 학년의 경우 데이터 타입이 int이기 때문에 집계되지 않는다.
  - str, object, category 타입만 집계됨
- **count**: 총 도수
- **unique** : 값의 계급(종류) 수
- **top**: 최빈값
- **freq** : 최빈값의 데이터 수

In [30]:
origin.describe(include='object').T

/var/folders/wk/8tx_v8l94cqcwt2b6dzgdc2h0000gn/T/ipykernel_10124/2253586407.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  origin.describe(include='object').T

   count unique top freq
성별     9      2  남자    6

### 3. 학년을 포함한 명목형 기술 통계량 집계

- 학년 컬럼의 데이터 타입을 명목형으로 변경 후   
  기술통계량 집계 대상을 object 타입과 category 타입으로 지정한다.

In [31]:
origin['학년'] = origin['학년'].astype('category')
origin.describe(include=['object', 'category']).T

/var/folders/wk/8tx_v8l94cqcwt2b6dzgdc2h0000gn/T/ipykernel_10124/2901828846.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  origin.describe(include=['object', 'category']).T

   count unique top freq
학년     9      4   1    4
성별     9      2  남자    6