# [LAB 03 Pandas] 4. 데이터 확인하기

## #01. 준비작업 

### 1. 라이브러리 설치

In [1]:
!pip install --upgrade jussam

Requirement already satisfied: jussam in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (0.5.17)
Requirement already satisfied: pandas in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from jussam) (3.0.3)
Requirement already satisfied: geopandas in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from jussam) (1.1.3)
Requirement already satisfied: requests in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from jussam) (2.32.5)
Requirement already satisfied: tabulate in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from jussam) (0.10.0)
Requirement already satisfied: numpy>=1.24 in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from geopandas->jussam) (2.4.6)
Requirement already satisfied: pyogrio>=0.7.2 in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from geopandas->jussam) (0.12.1)
Requirement already satisfied: packaging in c:\users\itwill\appdata\roaming\python\python311\site-packages (from geopandas->jussam) (26.0)
Requirement already satisfied: pyproj>=3.5.0 in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from geopandas->jussam) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from geopandas->jussam) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from pandas->jussam) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from pandas->jussam) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from requests->jussam) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from requests->jussam) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from requests->jussam) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from requests->jussam) (2026.2.25)
Requirement already satisfied: six>=1.5 in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas->jussam) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### 2. 라이브러리 참조

In [2]:
from jussam import load_data

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/

### 3. 가상의 과목별 점수 데이터 불러오기

In [3]:
origin = load_data('GRADE')
origin

📚 어느 학급의 과목별 점수를 조사한 가상의 데이터

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

## #02. 데이터 구조 확인 

### 1. 데이터의 차원과 크기 
- NumPy, Series와 동일한 기능

In [4]:
print("차원:", origin.ndim)
print("크기:", origin.shape)

차원: 2
크기: (9, 6)

In [5]:
### 2. 각 변수의 데이터 타입 확인 
origin.dtypes

# dtype : object
# 각 컬럼의 타입들을 담은 Series 자체의 타입이 object라는 거임. 
# 컬럼 데이터 타입이 아님.

학년    int64
성별      str
국어    int64
영어    int64
수학    int64
과학    int64
dtype: object

In [6]:
### 3. 각 필드별 정보 확인 
origin.info()

# memory usage: 612.0 bytes   ← (문자열 인덱스라 + 없이 고정값으로 표시됨)
# 9 non-null = 9개 행 중에 null(결측값)이 0개, 전부 값 있다는 뜻.

# 만약 결측값이 있었으면:
#  0   학년      7 non-null      int64   ← 9명 중 2명 결측

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: int64(5), str(1)
memory usage: 612.0 bytes

In [7]:
# 컬럼 하나 뽑으면 무조건 Series야.
# pythontype(origin['국어'])     # → pandas.Series
# type(origin['성별'])     # → pandas.Series
# type(origin['학년'])     # → pandas.Series

# 타입이 바뀌는 건 뽑는 방식이 달라질 때야:
# 코드결과 타입
# origin['국어']                     pandas.Series
# origin[['국어']]                   pandas.DataFrame
# origin[['국어', '영어']]           pandas.DataFrame
# origin['국어'].values              numpy.ndarray

# 대괄호 한 겹이면 Series, 두 겹이면 DataFrame이야.
# pythonorigin['국어']    # Series  ← 1차원
# origin[['국어']]  # DataFrame ← 2차원 (컬럼 1개짜리 표)

# 지금 단계에서 기억할 건 이것만: 컬럼 하나 뽑으면 Series, 여러 개 뽑으면 DataFrame.

In [8]:
## #03. 데이터 내용 확인 
### 1. 특정 "열"의 데이터 확인 
origin['국어']

이름
철수    98
영희    88
민철    92
수현    63
호영    75
영호    80
용식    82
나영    90
석영    91
Name: 국어, dtype: int64

In [9]:
# 이름은 인덱스라서 그래.
# 이름        ← 인덱스 이름 (index.name)
# 철수    98
# 영희    88
# ...
# Name: 국어   ← 이건 컬럼 이름
# 인덱스는 컬럼이 아니니까 옆에 나란히 안 나오고, 위에 따로 찍히는 거야.

# 비교해보면:
# python# 이름이 인덱스일 때
# origin['국어']
# # 이름
# # 철수    98   ← 인덱스가 왼쪽에 레이블로만 붙음

# # 이름이 일반 컬럼일 때 (set_index 안 했을 때)
# origin['국어']
# # 0    98
# # 1    88      ← 인덱스가 그냥 숫자
# 이름이 인덱스로 지정돼 있어서 숫자 대신 철수/영희로 보이는 거고, 이름 자체가 컬럼으로 출력되진 않는 거야.

In [10]:
### 2. 특정 "열"의 타입 확인 -> Series 
type(origin['국어'])

pandas.Series

In [11]:
type(origin[['국어']])

pandas.DataFrame

In [12]:
type(origin[['국어', '영어']])

pandas.DataFrame

In [13]:
type(origin['국어'].values)

numpy.ndarray

### 3. 원하는 열만 추출하기 
- 대괄호가 이중으로 표기된다.

In [14]:
df2 = origin[['국어', '영어', '수학']]
df2

    국어   영어  수학
이름
철수  98   77  88
영희  88  120  62
민철  92   70  83
수현  63   60  31
호영  75   50  90
영호  80   88  91
용식  82   88  79
나영  90   92  81
석영  91   90  89

In [ ]:
# 왜 대괄호 겹이 달라지면 타입이 다를까

# origin['국어']에서 대괄호 안에 뭘 넣는지가 핵심이야.

# python
# origin['국어']     # 문자열 → Series 반환
# origin[['국어']]   # 리스트 → DataFrame 반환
# DataFrame한테 문자열을 주면 "이 컬럼 하나 줘" → Series
# DataFrame한테 리스트를 주면 "이 컬럼들 줘" → DataFrame

# 리스트 하나짜리여도 리스트는 리스트라서 DataFrame으로 돌아와.

# 1차원 vs 2차원으로 이해하면

# Series    → 1차원 (값만 있음)
#             철수    98
#             영희    88

# DataFrame → 2차원 (행 + 열)
#             이름    국어
#             철수    98
#             영희    88
# 컬럼 하나를 뽑아도 표 형태를 유지하고 싶으면 [[ ]], 그냥 값만 보고 싶으면 [ ].

# 이게 왜 중요하냐면

# 나중에 머신러닝에서:

# python
# X = df[['국어', '영어', '수학']]   # DataFrame → 입력 피처
# y = df['성적']                      # Series → 정답 레이블
# sklearn이 X는 DataFrame(2차원), y는 Series(1차원)으로 받거든. 대괄호 겹 틀리면 에러 남.

# 취업해조 때 Random Forest 돌릴 때도 이 구조 썼을 거야.

# 한 줄 요약: [ ] 안에 문자열이냐 리스트냐가 Series/DataFrame을 가르는 거고, 이게 분석이랑 ML 전반에 계속 나오는 패턴이야.

## #04. 특정 행 접근 

### 1. 인덱스 이름으로 접근하기 
- loc : location(이름 기반 접근)

In [15]:
origin.loc['철수']

학년     1
성별    남자
국어    98
영어    77
수학    88
과학    64
Name: 철수, dtype: object

### 2. 특정 행의 데이터 타입 확인 
- Series 타입임을 확인할 수 있다.

In [16]:
type(origin.loc['철수'])

# 데이터프레임은 가로(행)과 세로(열)이 모두 Series 타입으로 구성된 객체이다. 
# 그러므로 행, 열이 모두 Series 객체의 모든 메서드를 포함하고 있다.

pandas.Series

### 3. 인덱스 번호를 기반으로 접근 
- lioc : 인덱스 번호로 접근 (index - location)

In [17]:
origin.iloc[0]

학년     1
성별    남자
국어    98
영어    77
수학    88
과학    64
Name: 철수, dtype: object

### 4. 인덱스 번호로 접근할 경우 슬라이싱 간으 
- 1~4번째 행 가져오기

In [18]:
origin.iloc[1:4]

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71

## #05. 단일 값 확인하기

### 1. 열 -> 행 순서로 접근

In [19]:
origin['국어']['철수']

# "numpy가 제공하는 int64(64비트 정수) 타입만 98이라는 값" 이라는 의미 
# -> 일반 정수 타입과 동일

np.int64(98)

### 2. 행 -> 열 순서로 접근

In [20]:
origin.loc['철수', '국어']

np.int64(98)

### 3. 인덱스 번호 기반 데이터 접근 
- 행 -> 열 순서로 접근함

In [21]:
# 1번째 행의 2번째 열 데이터 
origin.iloc[1,2]

np.int64(88)

### 4. 인덱스 번호로 접근할 경우 슬라이싱 가능 
- 행에 대해서 모든 행 지정, 3번째 열 지정

In [22]:
# 모든 행에서 3번째 열만 가져옴 
origin.iloc[:, 3]

이름
철수     77
영희    120
민철     70
수현     60
호영     50
영호     88
용식     88
나영     92
석영     90
Name: 영어, dtype: int64

## #06. 값의 변경 

### 1. 단일 값 변경 : 행 -> 열 순으로 접근하는 경우만 변경 가능함

In [23]:
origin.loc['철수', '국어'] = 100
origin

    학년  성별   국어   영어  수학  과학
이름
철수   1  남자  100   77  88  64
영희   2  여자   88  120  62  72
민철   1  남자   92   70  83  79
수현   3  여자   63   60  31  71
호영   4  남자   75   50  90  88
영호   4  남자   80   88  91  72
용식   2  남자   82   88  79  90
나영   1  여자   90   92  81  95
석영   1  남자   91   90  89  80

### 2. 열 단위 변경 
- 'replace(before, after)' 메서드를 사용하여, '88' 을 '92'로 일관 변경

In [24]:
origin['영어'] = origin['영어'].replace(88, 92)
origin

    학년  성별   국어   영어  수학  과학
이름
철수   1  남자  100   77  88  64
영희   2  여자   88  120  62  72
민철   1  남자   92   70  83  79
수현   3  여자   63   60  31  71
호영   4  남자   75   50  90  88
영호   4  남자   80   92  91  72
용식   2  남자   82   92  79  90
나영   1  여자   90   92  81  95
석영   1  남자   91   90  89  80

### 3. 조건에 맞는 행을 검색하여 특정 열 변경하기 
- Series 객체의 표현식을 사용하여, 조건에 맞는 행에 'loc' 프로퍼티로 접근한 후, \
값을 변경할 컬럼을 지정한다.

In [25]:
origin.loc[origin['수학']<50, '수학'] =0 
origin

    학년  성별   국어   영어  수학  과학
이름
철수   1  남자  100   77  88  64
영희   2  여자   88  120  62  72
민철   1  남자   92   70  83  79
수현   3  여자   63   60   0  71
호영   4  남자   75   50  90  88
영호   4  남자   80   92  91  72
용식   2  남자   82   92  79  90
나영   1  여자   90   92  81  95
석영   1  남자   91   90  89  80

## #07. 데이터 일부만 확인 

### 1. 상위 n건 확인 
- 파라미터가 생략될 경우 기본값 5

In [26]:
origin.head(2)

    학년  성별   국어   영어  수학  과학
이름
철수   1  남자  100   77  88  64
영희   2  여자   88  120  62  72

### 2. 하위 n건 확인

In [27]:
origin.tail(2)

    학년  성별  국어  영어  수학  과학
이름
나영   1  여자  90  92  81  95
석영   1  남자  91  90  89  80

## #08. 기술 통계량 확인 

### 1. 컬럼 단위 확인 
- DataFrame 의 컬럼은 Series 객체 이므로 Series의 메서드를 그대로 사용 가능함

In [28]:
print("합계:", origin['국어'].sum())
print("평균:", origin['국어'].mean())
print("최대:", origin['국어'].max())
print("최소:", origin['국어'].min())
print("분산:", origin['국어'].var())
print("표준편차:", origin['국어'].std())
print("중앙값:", origin['국어'].median())
print("1사분위 수:", origin['국어'].quantile(0.75))
print("2사분위 수:", origin['국어'].quantile(0.25))
print("3사분위 수:", origin['국어'].quantile(0.75))

합계: 761
평균: 84.55555555555556
최대: 100
최소: 63
분산: 120.02777777777779
표준편차: 10.955718953029864
중앙값: 88.0
1사분위 수: 91.0
2사분위 수: 80.0
3사분위 수: 91.0

### 2. DataFrame 단위 확인 
- 모든 컬럼에 대해서 일관 계산한다.
- 계산할 수 없는 형태의 값도 계산되므로 주의가 필요하다

In [29]:
origin.sum()

학년                    19
성별    남자여자남자여자남자남자남자여자남자
국어                   761
영어                   743
수학                   663
과학                   711
dtype: object

### 3. 컬럼 단위로 모든 기술 통계량 일괄 산출

In [30]:
origin['국어'].describe()

count     9.000
mean     84.556
std      10.956
min      63.000
25%      80.000
50%      88.000
75%      91.000
max     100.000
Name: 국어, dtype: float64

### 4. DataFrame 단위로 일괄 산출
- 연산이 가능한 열만 추출해서 적용해야 한다.

In [31]:
# 연산이 가능한 컬럼만 추출 
df2 = origin[['국어', '영어', '수학', '과학']]
desc = df2.describe()
desc

           국어      영어     수학     과학
count   9.000   9.000  9.000  9.000
mean   84.556  82.556 73.667 79.000
std    10.956  20.863 29.026 10.283
min    63.000  50.000  0.000 64.000
25%    80.000  70.000 79.000 72.000
50%    88.000  90.000 83.000 79.000
75%    91.000  92.000 89.000 88.000
max   100.000 120.000 91.000 95.000

### 5. 전치 구하기 
- 가로와 세로가 바뀐 새로운 데이터프레임을 생성할 수 있다.

In [32]:
t = desc.T
t

    count   mean    std    min    25%    50%    75%     max
국어  9.000 84.556 10.956 63.000 80.000 88.000 91.000 100.000
영어  9.000 82.556 20.863 50.000 70.000 90.000 92.000 120.000
수학  9.000 73.667 29.026  0.000 79.000 83.000 89.000  91.000
과학  9.000 79.000 10.283 64.000 72.000 79.000 88.000  95.000

## #09. 명목형 변수의 기술 통계량 확인 

### 1. 빈도수 구하기 -> 값의 종류별 수 
- 예제 데이터에서 "성별', "학년" 등과 같이 연산을 수행할 수 없는 카테고리 성격의 데이터는 종류별 수량을 구해서 데이터 분포를 파악한다.

In [33]:
origin['성별'].value_counts()

성별
남자    6
여자    3
Name: count, dtype: int64

In [34]:
origin['학년'].value_counts()

학년
1    4
2    2
4    2
3    1
Name: count, dtype: int64

### 2. 명목형 변수의 기술 통계량 
- 학년의 경우 데이터 타입이 INT이기 때문에 집계되지 않는다. 
    - str, object, category 타입만 집계됨 
- count : 총 도수 
- unique : 값의 계급(종류) 수 
- top : 최빈값 
- freq : 최빈값의 데이터 수

In [35]:
origin.describe(include = 'object').T

C:\Users\itwill\AppData\Local\Temp\ipykernel_17584\2777324801.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  origin.describe(include = 'object').T

   count unique top freq
성별     9      2  남자    6

### 1. 학년을 포함한 명목형 기술 통계량 집계 
- 학년 컬럼의 데이터 타입을 명목형으로 변경 후 \
기술 통계량 집계 대상을 object타입과 category 타입으로 지정한다.

In [36]:
origin['학년'] = origin['학년'].astype('category')
origin.describe(include= ['object', 'category']).T

C:\Users\itwill\AppData\Local\Temp\ipykernel_17584\3107020179.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  origin.describe(include= ['object', 'category']).T

   count unique top freq
학년     9      4   1    4
성별     9      2  남자    6