In [313]:
# 16:30 에 다음 수업시작

# [LAB 03] Pandas DataFrame 자료형

In [314]:
# # 생성 방법 3가지
# DataFrame(2차원리스트, index=[], columns=[])
# DataFrame(딕셔너리)          # key → 컬럼명
# DataFrame(딕셔너리 리스트)   # key → 컬럼명

# # 인덱스 조작 2가지
# df.set_index('컬럼명')       # 컬럼 → 인덱스로
# df.reset_index()             # 인덱스 → 컬럼으로

# # 외부 파일
# read_csv("경로", encoding="euc-kr", index_col='컬럼명')
# read_excel("경로", index_col='컬럼명')

## #01. 준비작업

In [315]:
from pandas import DataFrame, read_csv, read_excel

## #02. DataFrame 생성하기

### 1. 2차원 리스트를 DataFrame으로 변환
- 특별한 옵션을지정하지 않을 경우 인덱스는 0부터 시작되는 일련번호 형식으로 구성된다.

In [316]:
# 어느 학급의 성적을 표현한 2차원 리스트 
grade_data = [
    [1, "남자", 98, 77, 88, 64], 
    [2, "여자", 88, 90, 62, 72], 
    [1, "남자", 92, 70, 83, 79], 
    [3, "여자", 63, 60, 31, 70], 
    [4, "남자", 75, 50, 90, 88]     
]

# 2차원 리스트를 데이터프레임으로 변환
# -> 학생별 점수 표현 
df = DataFrame(grade_data)
df

   0   1   2   3   4   5
0  1  남자  98  77  88  64
1  2  여자  88  90  62  72
2  1  남자  92  70  83  79
3  3  여자  63  60  31  70
4  4  남자  75  50  90  88

### 2. 인덱스와 컬럼 이름 지정하기

In [317]:
# 인덱스 이름으로 사용할 리스트 
i_names = ['철수', '영희', '민철', '수현', '호영' ]

# 컬럼 이름으로 사용할 리스트 
c_names = ['학년', '성별', '국어', '영어', '수학', '과학']

# 인덱스와 컬럼이름 지정하기 
df = DataFrame(grade_data, index=i_names, columns=c_names)
df

    학년  성별  국어  영어  수학  과학
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

### 3. 리스트를 원소로 갖는 딕셔너리로 DataFrame 생성 
- 딕셔너리의 key가 컬럼이름으로 구성된다.

In [318]:
# 어느 학급의 성적표를 표현한 딕셔너리 
grade_dic = {
    '학년':[1,2,1,3,4],
    '성별':['남자', '여자', '남자', '여자', '남자'],
    '국어':[98, 88, 92, 63, 75],
    '영어':[77, 90, 70, 60, 50], 
    '수학':[88, 62, 83, 31, 90], 
    '과학':[64, 72, 79, 70, 88]         
}

# 딕셔너리 key가 컬럼(열) 이름이 된다.
df = DataFrame(grade_dic)
df

   학년  성별  국어  영어  수학  과학
0   1  남자  98  77  88  64
1   2  여자  88  90  62  72
2   1  남자  92  70  83  79
3   3  여자  63  60  31  70
4   4  남자  75  50  90  88

### 4. 인덱스와 인덱스 이름과 제목을 지정한 DataFrame
- grade_dic은 직전코드 블록에서 생성한 객체

In [319]:
# 인덱스 지정하기 
df = DataFrame(grade_dic, 
               index=['철수', '영희', '민철', '수현', '호영'])

# 인덱스 제목 지정하기 
df.index.name = '이름'
df

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

### 5. 딕셔너리를 원소로 갖는 리스트를 활용한 DataFrame 생성 
- 딕셔너리의 키는 항상 컬럼이름이 된다.

In [320]:
grade_list = [
    {"이름":"철수", "학년":1, "성별":"남자", "국어":98, "영어":77, "수학":88,"과학":64},
    {"이름":"영희", "학년":2, "성별":"여자", "국어":88, "영어":90, "수학":62,"과학":72},
    {"이름":"민철", "학년":1, "성별":"남자", "국어":92, "영어":70, "수학":83,"과학":83},
    {"이름":"수현", "학년":3, "성별":"여자", "국어":63, "영어":60, "수학":31,"과학":70},
    {"이름":"호영", "학년":4, "성별":"남자", "국어":75, "영어":50, "수학":90,"과학":88},
]

df=DataFrame(grade_list)
df

   이름  학년  성별  국어  영어  수학  과학
0  철수   1  남자  98  77  88  64
1  영희   2  여자  88  90  62  72
2  민철   1  남자  92  70  83  83
3  수현   3  여자  63  60  31  70
4  호영   4  남자  75  50  90  88

## #03. 인덱스 다루기 

### 1. 이미 생성된 DataFrame의 특정 컬럼을 index로 지정하기 
- 원본은 변화 없고, 변경사항이 적용된 복사본이 리턴된다.

In [321]:
df2 = df.set_index('이름') # 직전 페이지에서 생성한 df객체 
df2 # 아까 만든 '이름' 열이 인덱스로 가서, 제일 왼쪽 열이 됨

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  83
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

In [322]:
# 리턴, 함수가 실행되고 나서 결과물을 돌려주는 것이 리턴이야.

df2 = df.set_index('이름')
#    ↑ 여기서 받는 게 "리턴값을 받는다" = 리턴 받는다
# 리턴값을 변수에 안 담으면 그냥 사라져.
df2

# 이렇게 하면:

# df → 원본, 손대지 않음
# df2 → 변경사항 적용된 복사본

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  83
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

In [323]:
df.set_index('이름')   # 리턴값 안 받음 → 결과가 버려짐

# 이렇게 하면:

# df 자체가 바뀜 → 원본이 덮어씌워짐
# 리턴값 없음

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  83
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

In [324]:
# Jupyter라서, 코드가 똑같이 실행되는 것 처럼 보임.
# pythondf.set_index('이름')   # 셀 마지막 줄이면 자동 출력됨
# Jupyter는 셀 마지막 줄의 리턴값을 자동으로 화면에 보여줘. 그래서 실행은 되고 결과도 눈에 보이는데, 그게 저장된 게 아니야.

# 비유하자면:
# pythondf.set_index('이름')      # 결과를 눈으로만 보고 버린 것
# df2 = df.set_index('이름') # 결과를 변수에 담아서 보관한 것
# 계산기에서 3 + 4 눌러서 7 화면에 뜨는 거랑, 그 7을 어딘가 적어두는 거랑 다른 거랑 같아.

# 그래서 Jupyter에서 헷갈리는 거야. .py 파일로 실행하면:
# pythondf.set_index('이름')   # 아무것도 안 보임, 진짜로 버려짐
# 완전히 사라져서 차이가 바로 보이거든. Jupyter가 친절하게 보여줘서 저장된 것처럼 착각하게 만드는 거야.

### 2. inplace = True : 복사본을 생성하지 않고, 원본에 즉시 반영하기 
- 리턴값이 없다.
- 원본 데이터를 변경하는 것은 권장하지 않는 방법이다.

In [325]:
df.set_index('이름', inplace = True)
df

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  83
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

In [326]:
df.reset_index(drop = True) # 인덱스였던, '이름' 열이 사라짐

   학년  성별  국어  영어  수학  과학
0   1  남자  98  77  88  64
1   2  여자  88  90  62  72
2   1  남자  92  70  83  83
3   3  여자  63  60  31  70
4   4  남자  75  50  90  88

### 3. 인덱스 해제하기 
- 인덱스를 일반 컬럼으로 되돌린 복사본을 리턴한다.
- 일련번호 형식의 인덱스가 새롭게 생성된다.
- 마찬가지로 inplace = True 파라미터를 사용하면 리턴되는 객체 없이 원본에 즉시 반영된다.

In [327]:
df3 = df.reset_index() # df가 다시 원상복구 됨.
df3

   이름  학년  성별  국어  영어  수학  과학
0  철수   1  남자  98  77  88  64
1  영희   2  여자  88  90  62  72
2  민철   1  남자  92  70  83  83
3  수현   3  여자  63  60  31  70
4  호영   4  남자  75  50  90  88

### 4. reset_index() 사용시 주의사항 
- reset_index()는 기존의 인덱스를 컬럼으로 되돌리면서 \
일련번호 인덱스를 새롭게 만들기 때문에 \
df3에서 인덱스를 제거하면 오히려 새로운 컬럼이 추가되는 결과를 가져온다.

In [328]:
df3.reset_index() # 리턴을 받지 않았으므로, 결과는 출력만 하고 버려진다.

   index  이름  학년  성별  국어  영어  수학  과학
0      0  철수   1  남자  98  77  88  64
1      1  영희   2  여자  88  90  62  72
2      2  민철   1  남자  92  70  83  83
3      3  수현   3  여자  63  60  31  70
4      4  호영   4  남자  75  50  90  88

### 5. 인덱스를 해제하면서 기존 인덱스 제거하기 
- drop = True 파라미터를 적용하면 기존의 인덱스를 일반 컬럼으로 변환하지 않고 삭제한다.
- 하지만 모든 DataFrame에는 반드시 인덱스가 항상 존재해야 하기 때문에,
일련번호 형식의 인덱스가 새롭게 생성된다.

In [329]:
df3.reset_index(drop = True)

   이름  학년  성별  국어  영어  수학  과학
0  철수   1  남자  98  77  88  64
1  영희   2  여자  88  90  62  72
2  민철   1  남자  92  70  83  83
3  수현   3  여자  63  60  31  70
4  호영   4  남자  75  50  90  88

## #04. 외부파일로부터 데이터 프레임 생성

### 1. csv 파일을 데이터 프레임으로 가져오기 
- pandas의 read_csv()함수를 사용한다.
- 로컬에 위치한 파일을 상대, 절대 경로방식으로 가져올 수 있으며, \
온라인 상의 파일을 URL 기반으로 가져올 수도 있다. 
- CSV 파일의 첫 행이 데이터 프레임의 컬럼이름으로 사용된다.

In [330]:
df = read_csv("https://data.juyounga.kr/data/grade.csv", encoding="euc-kr")

df

   이름  학년  성별  국어   영어  수학  과학
0  철수   1  남자  98   77  88  64
1  영희   2  여자  88  120  62  72
2  민철   1  남자  92   70  83  79
3  수현   3  여자  63   60  31  71
4  호영   4  남자  75   50  90  88
5  영호   4  남자  80   88  91  72
6  용식   2  남자  82   88  79  90
7  나영   1  여자  90   92  81  95
8  석영   1  남자  91   90  89  80

### 2. 인덱스로 사용할 열의 이름 지정하기 
- 데이터 파일을 가져오는 과정에서 인덱스로 사용할 열 이름을 미리 지정할 수 있다.

In [331]:
df = read_csv("https://data.juyounga.kr/data/grade.csv", encoding="euc-kr", index_col='이름')

df

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### 3. 엑셀 파일 처리를 위한 패키지 설치

In [332]:
!pip install --upgrade openpyxl xlrd

Requirement already satisfied: openpyxl in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (3.1.5)
Requirement already satisfied: xlrd in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (2.0.2)
Requirement already satisfied: et-xmlfile in c:\users\itwill\appdata\local\programs\python\python311\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [333]:
df = read_excel("https://data.juyounga.kr/data/grade.xlsx" , index_col='이름')

In [334]:
#1. 2차원 리스트를 DataFrame으로 변환 

data = [
    [1,"남자","98"], 
    [2,"여자", 88]
]

df = DataFrame(data)
df

i_names = ["철수", "영희"]
c_names = ["학년","성별","국어"]

df = DataFrame(data, index = i_names, columns = c_names)
df.index.name = "이름"
df

    학년  성별  국어
이름
철수   1  남자  98
영희   2  여자  88