## #01. 연습문제

### 1. 데이터 로드

In [10]:
from jussam import load_data
from helpers import my_qtcheck

In [11]:
origin = load_data("housing")
origin

📚 주택 가격 데이터셋. 주택 면적, 침실 수, 가구 비치 여부, 주요 도로와의 근접성 등 특정 요소를 기반으로 주택 가격을 예측하는 간단하면서도 도전적인 프로젝트입니다. 데이터셋은 작지만, 다중공선성이 매우 높아 예측 모델 구축에 어려움이 있습니다. 이러한 난관을 극복하고 괜찮은 예측 모델을 만들 수 있을까요? (출처: https://www.kaggle.com/datasets/yasserh/housing-prices-dataset)

    field             description
--  ----------------  ----------------------------------------------------------------------------------------------------------------------------------------------------------------
 0  price             주택 가격 (USD 달러) - 예측 대상 변수
 1  area              주택 면적 (제곱 단위) - 주택의 건축 면적
 2  bedrooms          침실 수 (개수) - 주택의 침실 개수
 3  bathrooms         욕실 수 (개수) - 주택의 욕실 개수
 4  stories           주택 층 수 (개수) - 주택의 총 지상 층수
 5  mainroad          주요 도로 인접 여부 (이진형: Yes/No 또는 0/1) - 주택이 주요 도로에 인접해 있는지 여부
 6  guestroom         게스트룸 보유 여부 (이진형: Yes/No 또는 0/1) - 손님용 방이 있는지 여부
 7  basement          지하실 보유 여부 (이진형: Yes/No 또는 0/1) - 지하실이 있는지 여부
 8  hotwaterheating   온수 난방 시스템 보유 여부 (이진형: Yes/No 또는 0/1) - 온수 난방 시스템이 설치되어 있는지 여부
 9  airconditioning   에어컨 보유 여부 (이진형: Yes/No 또는 0/1) - 에어컨이 설치되어 있는지 여부
10  parking           주차 공간 수 (개수) - 주택에 제공되는 주차 공간의 수
11  prefarea          선호 지역 여부 (이진형: Yes/No 또는 0/1) - 주택이 선호되는 지역에 위치해 있는지 여부
12  furnishingstatus  가구 비치 여부 (범주형: Furnished, Semi-furnished, Unfurnished) - 주택이 가구가 완비된 상태인지, 반쯤 완비된 상태인지, 아니면 가구가 없는 상태인지를 나타냅니다.

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [12]:
origin.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 69.2 KB

### 2. 자료형 점검 및 변환

In [13]:
df1 = origin.copy()

In [14]:
# df1['mainroad'] = df1["mainroad"].astype("category")
# df1['guestroom'] = df1["guestroom"].astype("category")
# df1['basement'] = df1["basement"].astype("category")
# df1['hotwaterheating'] = df1["hotwaterheating"].astype("category")
# df1['airconditioning'] = df1["airconditioning"].astype("category")
# df1['prefarea'] = df1["prefarea"].astype("category")
# df1['furnishingstatus'] = df1["furnishingstatus"].astype("category")


# df1.info()

In [15]:
df1 = my_qtcheck.set_type(df1, as_category=['mainroad', 'guestroom', 'basement','hotwaterheating',
                                            'airconditioning', 'prefarea','furnishingstatus' ])

df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    category
 6   guestroom         545 non-null    category
 7   basement          545 non-null    category
 8   hotwaterheating   545 non-null    category
 9   airconditioning   545 non-null    category
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    category
 12  furnishingstatus  545 non-null    category
dtypes: category(7), int64(6)
memory usage: 29.6 KB
<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    category
 6   guestroom         545 non-null    category
 7   basement          545 non-null    category
 8   hotwaterheating   545 non-null    category
 9   airconditioning   545 non-null    category
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    category
 12  furnishingstatus  545 non-null    category
dtypes: category(7), int64(6)
memory usage: 29.6 KB

### 2. 중복 점검

In [23]:
df2 = my_qtcheck.check_duplicates(df1)
df2.head()

중복된 행의 수 : 0

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [22]:
my_qtcheck.check_missing_values(df2)

                  Missing Count  Missing Ratio (%)
price                         0              0.000
area                          0              0.000
bedrooms                      0              0.000
bathrooms                     0              0.000
stories                       0              0.000
mainroad                      0              0.000
guestroom                     0              0.000
basement                      0              0.000
hotwaterheating               0              0.000
airconditioning               0              0.000
parking                       0              0.000
prefarea                      0              0.000
furnishingstatus              0              0.000

In [ ]:
df2.to_excel("housing_qtcheck.xlsx", index=False)

### 3. 형식, 표기, 단위 점검

mainroad
yes    468
no      77
Name: count, dtype: int64

In [26]:
df2["mainroad"].value_counts()
df2['guestroom'].value_counts()
df2['basement'].value_counts()
df2['hotwaterheating'].value_counts()
df2['airconditioning'].value_counts() 
df2['prefarea'].value_counts() 
df2['furnishingstatus'].value_counts()

furnishingstatus
semi-furnished    227
unfurnished       178
furnished         140
Name: count, dtype: int64

### 기술 통계량 확인

In [27]:
categoty_desc = my_qtcheck.categorical_summary(df2, save_path="housing_qtcheck.xlsx")
categoty_desc

컬럼 'mainroad'의 value_counts():

          count
mainroad
no           77
yes         468

컬럼 'guestroom'의 value_counts():

           count
guestroom
no           448
yes           97

컬럼 'basement'의 value_counts():

          count
basement
no          354
yes         191

컬럼 'hotwaterheating'의 value_counts():

                 count
hotwaterheating
no                 520
yes                 25

컬럼 'airconditioning'의 value_counts():

                 count
airconditioning
no                 373
yes                172

컬럼 'prefarea'의 value_counts():

          count
prefarea
no          417
yes         128

컬럼 'furnishingstatus'의 value_counts():

                  count
furnishingstatus
furnished           140
semi-furnished      227
unfurnished         178

,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus
count,545,545,545,545,545,545,545
unique,2,2,2,2,2,2,3
top,yes,no,no,no,no,no,semi-furnished
freq,468,448,354,520,373,417,227

In [28]:
desc_df = my_qtcheck.numerical_summary(df2, save_path="housing_qtcheck.xlsx")
desc_df

,count,mean,std,min,25%,50%,75%,max,rel_diff,rdiff_flag,iqr,upper_bound,lower_bound,upper_outliers,upper_outliers_ratio,lower_outliers,lower_outliers_ratio,outliers,outliers_ratio,skew,skew_interpret,kurt,kurt_interpret,log_need
price,545.000,4766729.248,1870439.616,1750000.000,3430000.000,4340000.000,5740000.000,13300000.000,0.098,similar,2310000.000,9205000.000,-35000.000,15,0.028,0,0.000,15,0.028,1.212,right tail,1.960,leptokurtic,log1p
area,545.000,5150.541,2170.141,1650.000,3600.000,4600.000,6360.000,16200.000,0.120,diff,2760.000,10500.000,-540.000,12,0.022,0,0.000,12,0.022,1.321,right tail,2.751,leptokurtic,log1p
bedrooms,545.000,2.965,0.738,1.000,2.000,3.000,3.000,6.000,0.012,similar,1.000,4.500,0.500,12,0.022,0,0.000,12,0.022,0.496,symmetric,0.728,leptokurtic,none
bathrooms,545.000,1.286,0.502,1.000,1.000,1.000,2.000,4.000,0.286,diff,1.000,3.500,-0.500,1,0.002,0,0.000,1,0.002,1.589,right tail,2.165,leptokurtic,log1p
stories,545.000,1.806,0.867,1.000,1.000,2.000,2.000,4.000,0.097,similar,1.000,3.500,-0.500,41,0.075,0,0.000,41,0.075,1.082,right tail,0.679,leptokurtic,log1p
parking,545.000,0.694,0.862,0.000,0.000,0.000,1.000,3.000,inf,large_diff,1.000,2.500,-1.500,12,0.022,0,0.000,12,0.022,0.842,right tail,-0.573,platykurtic,none

In [29]:
desc_df.T

,price,area,bedrooms,bathrooms,stories,parking
count,545.000,545.000,545.000,545.000,545.000,545.000
mean,4766729.248,5150.541,2.965,1.286,1.806,0.694
std,1870439.616,2170.141,0.738,0.502,0.867,0.862
min,1750000.000,1650.000,1.000,1.000,1.000,0.000
25%,3430000.000,3600.000,2.000,1.000,1.000,0.000
50%,4340000.000,4600.000,3.000,1.000,2.000,0.000
75%,5740000.000,6360.000,3.000,2.000,2.000,1.000
max,13300000.000,16200.000,6.000,4.000,4.000,3.000
rel_diff,0.098,0.120,0.012,0.286,0.097,inf
rdiff_flag,similar,diff,similar,diff,similar,large_diff
iqr,2310000.000,2760.000,1.000,1.000,1.000,1.000
upper_bound,9205000.000,10500.000,4.500,3.500,3.500,2.500
lower_bound,-35000.000,-540.000,0.500,-0.500,-0.500,-1.500
upper_outliers,15,12,12,1,41,12
upper_outliers_ratio,0.028,0.022,0.022,0.002,0.075,0.022
lower_outliers,0,0,0,0,0,0
lower_outliers_ratio,0.000,0.000,0.000,0.000,0.000,0.000
outliers,15,12,12,1,41,12
outliers_ratio,0.028,0.022,0.022,0.002,0.075,0.022
skew,1.212,1.321,0.496,1.589,1.082,0.842
skew_interpret,right tail,right tail,symmetric,right tail,right tail,right tail
kurt,1.960,2.751,0.728,2.165,0.679,-0.573
kurt_interpret,leptokurtic,leptokurtic,leptokurtic,leptokurtic,leptokurtic,platykurtic
log_need,log1p,log1p,none,log1p,log1p,none